camp_triggers = {
	['Reinforce 152 Filo'] = {
		['condition'] = 'true',
		['action'] = 'Action.AirUnitReinforce("152 Filo")',
		['active'] = true,
	},
	['North Cyprus-Turkish Force 2 move 5'] = {
		['condition'] = 'Return.CampFlag(805) and (Return.Mission() >= Return.CampFlag(805) + 9) and (Return.TargetAlive("North Cyprus-Turkish Force 2") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("North Cyprus-Turkish Force 2 T5.stm")',
			[2] = 'Action.Text("Heavy Turkish column 2 stopped moving in Larnaca city")',
			[4] = 'Action.SetCampFlag(832, Return.Mission())',
			[3] = 'Action.AddImage("NCTF2-5.png")',
		},
		['active'] = false,
	},
	['Larnaca Airbase Captured'] = {
		['condition'] = 'Return.CampFlag(801) and (Return.Mission() >= Return.CampFlag(801) + 4) and (Return.TargetAlive("Larnaca Turkish Assault Force 1") > 40)',
		['once'] = true,
		['action'] = {
			[2] = 'Action.TemplateActive("Larnaca Turkish Assault Force 1 T2.stm")',
			[3] = 'Action.SideBase("red", "Larnaca Airbase")',
			[1] = 'Action.TemplateActive("Larnaca Cyprus defenses T2.stm")',
			[4] = 'Action.Text("Larnaca Airbase has been captured by Turkish forces.")',
			[5] = 'Action.SetCampFlag(804, Return.Mission())',
		},
		['active'] = true,
	},
	['Turkish Naval Convoi 1 in port'] = {
		['condition'] = 'Return.CampFlag(801) and (Return.Mission() >= Return.CampFlag(801) + 6) and (Return.TargetAlive("Turkish Naval Convoy 1") > 40)',
		['once'] = true,
		['action'] = {
			[6] = 'Action.Text("Turkish naval forces are shipping reinforcement to Cyprus. One convoy is unloading troops in Famagusta port in East Cyprus")',
			[2] = 'Action.TemplateActive("North Cyprus-Turkish Force 2 T1.stm")',
			[8] = 'Action.SetCampFlag(805, Return.Mission())',
			[3] = 'Action.TargetActive("North Cyprus-Turkish Force 2", true)',
			[1] = 'Action.TemplateActive("Turkish Naval Convoy 1 T3.stm")',
			[4] = 'Action.TemplateActive("Turkish Hawk Battery 2 T1.stm")',
			[5] = 'Action.TargetActive("Turkish Hawk Battery 2", true)',
			[7] = 'Action.AddImage("NCTF2-1.png")',
		},
		['active'] = true,
	},
	['Greek Expeditionary Force 1 move 3'] = {
		['condition'] = 'Return.CampFlag(808) and (Return.Mission() >= Return.CampFlag(808) + 5) and (Return.TargetAlive("Greek Expeditionary Force 1") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("Greek Expeditionary Force 1 T3.stm")',
			[2] = 'Action.AddImage("GEF1-3.png")',
			[3] = 'Action.Text("Greek Expeditionary column 1 is still moving ")',
		},
		['active'] = false,
	},
	['Cyprus Defense Force 3 move 2'] = {
		['condition'] = 'Return.CampFlag(801) and (Return.Mission() >= Return.CampFlag(801) + 5) and (Return.TargetAlive("Cyprus Defense Force 3") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("Cyprus Defense Force 3 T2.stm")',
			[2] = 'Action.AddImage("CDF3-2.png")',
			[3] = 'Action.Text("Cyprus Defense Force 3 is still moving")',
		},
		['active'] = true,
	},
	['Cyprus Defense Force 4 move 2'] = {
		['condition'] = 'Return.CampFlag(801) and (Return.Mission() >= Return.CampFlag(801) + 5) and (Return.TargetAlive("Cyprus Defense Force 4") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("Cyprus Defense Force 4 T2.stm")',
			[2] = 'Action.AddImage("CDF4-2.png")',
			[3] = 'Action.Text("Cyprus Defense Force 4 is still moving")',
		},
		['active'] = true,
	},
	['North Cyprus Force 2 initial positions'] = {
		['condition'] = 'Return.Mission() > 0',
		['once'] = true,
		['action'] = {
			[2] = 'Action.TargetActive("North Cyprus Force 2", true)',
			[3] = 'Action.Text("North Cyprus columns crossed the No man s land and are coming from the close south west of Nicosia")',
			[1] = 'Action.TemplateActive("North Cyprus Force 2 T1.stm")',
			[4] = 'Action.TemplateActive("Cyprus Border Force 3 T1.stm")',
			[5] = 'Action.TargetActive("Cyprus Border Force 3", true)',
		},
		['active'] = false,
	},
	['Larnaca Turkish Assault Force Victory'] = {
		['condition'] = '(Return.Mission() > 23) and Return.CampFlag(804) and Return.CampFlag(843) and (Return.TargetAlive("Greek Expeditionary Force 3") < Return.TargetAlive("Larnaca Turkish Assault Force 1"))',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("Greek Expeditionary Force 3 T2.stm")',
			[2] = 'Action.SetCampFlag(855, 1)',
		},
		['active'] = true,
	},
	['North Cyprus Force 3 move 2'] = {
		['condition'] = 'Return.Mission() > 1 and (Return.Mission() < 3 and Return.TargetAlive("North Cyprus Force 3") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("North Cyprus Force 3 T2.stm")',
			[2] = 'Action.Text("North Cyprus columns are still moving in the south east of Nicosia")',
			[3] = 'Action.TemplateActive("Cyprus Border Force 4 T2.stm")',
		},
		['active'] = false,
	},
	['North Cyprus Force 2 move 2'] = {
		['condition'] = 'Return.Mission() > 1 and (Return.Mission() < 3 and Return.TargetAlive("North Cyprus Force 2") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("North Cyprus Force 2 T2.stm")',
			[2] = 'Action.Text("North Cyprus columns are still moving in the south west suburbs of Nicosia")',
			[3] = 'Action.TemplateActive("Cyprus Border Force 3 T2.stm")',
		},
		['active'] = false,
	},
	['North Cyprus Force 4 move 3'] = {
		['condition'] = 'Return.Mission() > 2 and (Return.TargetAlive("North Cyprus Force 4") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("North Cyprus Force 4 T3.stm")',
			[2] = 'Action.Text("North Cyprus columns are still moving in the south east suburbs of Nicosia")',
			[3] = 'Action.TemplateActive("Cyprus Border Force 5 T3.stm")',
		},
		['active'] = false,
	},
	['North Cyprus Force 3 stop'] = {
		['condition'] = 'Return.TargetAlive("North Cyprus Force 3") < 40',
		['once'] = true,
		['action'] = {
			[1] = 'Action.Text("North Cyprus columns to the close South east of Nicosia took heavy losses and are stopped")',
		},
		['active'] = true,
	},
	['Greek Naval Convoy activation-134.Filo on Cyprus'] = {
		['condition'] = 'Return.CampFlag(801) and (Return.Mission() >= Return.CampFlag(801) + 3)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.AirUnitBase("134.Filo", "Gecitkale Airbase")',
			[2] = 'Action.TemplateActive("Greek Naval Convoy T1.stm")',
			[4] = 'Action.Text("Greek naval forces are shipping reinforcement to Cyprus.")',
			[3] = 'Action.TargetActive("Greek Naval Convoy", true)',
		},
		['active'] = true,
	},
	['Greek Naval Convoy 2 in port after NCF victory'] = {
		['condition'] = 'Return.CampFlag(802) and (Return.Mission() >= Return.CampFlag(802) + 5) and (Return.TargetAlive("Greek Naval Convoy 2") > 40)',
		['once'] = true,
		['action'] = {
			[6] = 'Action.AddImage("GEF2-1.png")',
			[2] = 'Action.TemplateActive("Greek Expeditionary Force 2 T1.stm")',
			[3] = 'Action.TargetActive("Greek Expeditionary Force 2", true)',
			[1] = 'Action.TemplateActive("Greek Naval Convoy 2 T3.stm")',
			[4] = 'Action.TemplateActive("Greek Limassol defenses T1.stm")',
			[5] = 'Action.Text("Greek naval forces are shipping reinforcement to Cyprus. One convoy is unloading troops in Limassol harbor")',
			[7] = 'Action.SetCampFlag(809, Return.Mission())',
		},
		['active'] = false,
	},
	['Helicopters Hind Squadron Move after Greece Involvement'] = {
		['condition'] = 'Return.CampFlag(802) and (Return.Mission() >= Return.CampFlag(802) + 1)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.AirUnitBase("450 M-E/P-1", "Paphos Airbase")',
			[2] = 'Action.Text("North Cyprus columns are circling Lakatamia airbase. Despite Greece involvement we must retreat our frontline helicopters unit to Paphos airbase")',
			[3] = 'Action.SetCampFlag(803, Return.Mission())',
		},
		['active'] = false,
	},
	['Greek Expeditionary Force 4 airborn Stats'] = {
		['condition'] = 'Return.PlaceLogistic("Paphos Airbase") < 60000 ',
		['once'] = false,
		['action'] = {
			[1] = 'Action.LogisticObjectif("Paphos Airbase", 60000)',
		},
		['active'] = true,
	},
	['Greek Naval Convoy mouvement after NCF victory'] = {
		['condition'] = 'Return.CampFlag(802) and (Return.Mission() >= Return.CampFlag(802) + 2) and (Return.TargetAlive("Greek Naval Convoy") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("Greek Naval Convoy T2.stm")',
			[2] = 'Action.Text("Greek naval forces are shipping reinforcement to Cyprus.")',
		},
		['active'] = false,
	},
	['After EWR-Jaguar Destroyed'] = {
		['condition'] = 'Return.TargetAlive("EWR-Jaguar") == 0',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TargetActive("Gecitkale Airbase Alert", false)',
		},
		['active'] = true,
	},
	['Campaign End Victory 1'] = {
		['condition'] = '(Return.Mission() > 26) and (Return.CampFlag(851) + Return.CampFlag(852) + Return.CampFlag(853) + Return.CampFlag(854) + Return.CampFlag(855) + Return.CampFlag(856)) < 3',
		['once'] = false,
		['action'] = {
			[2] = 'Action.Text("Cyprus Forces repulse the turkish assault with Greek forces help. They are trying to negociate a cease fire now.")',
			[3] = 'Action.AddImage("Newspaper_Victory_blue.jpg", "blue")',
			[1] = 'Action.CampaignEnd("win")',
			[4] = 'Action.AddImage("Newspaper_Defeat_red.jpg", "red")',
			[5] = 'NoMoreNewspaper = true',
		},
		['active'] = true,
	},
	['Cyprus Defense Force 1 move 3 after North Cyprus attack'] = {
		['condition'] = 'Return.CampFlag(802) and (Return.Mission() >= Return.CampFlag(802) + 5) and (Return.TargetAlive("Cyprus Defense Force 1") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("Cyprus Defense Force 1 T3.stm")',
			[2] = 'Action.AddImage("CDF1-3.png")',
			[4] = 'Action.SetCampFlag(821, Return.Mission())',
			[3] = 'Action.Text("Cyprus Defense Force 1 reached defensives positions")',
		},
		['active'] = false,
	},
	['Cyprus Defense Force 3 stop'] = {
		['condition'] = 'Return.TargetAlive("Cyprus Defense Force 3") < 40',
		['once'] = true,
		['action'] = {
			[1] = 'Action.Text("Cyprus Defense Force 3 took heavy losses and is stopped")',
		},
		['active'] = true,
	},
	['Turkish Naval Convoi 2 mouvement'] = {
		['condition'] = 'Return.CampFlag(801) and (Return.Mission() >= Return.CampFlag(801) + 5) and (Return.TargetAlive("Turkish Naval Convoy 2") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("Turkish Naval Convoy 2 T2.stm")',
			[2] = 'Action.Text("Turkish naval forces are shipping reinforcement to Cyprus. One convoy is near Kyrenia port in North Cyprus")',
		},
		['active'] = true,
	},
	['Turkish Naval Convoi 1 mouvement'] = {
		['condition'] = 'Return.CampFlag(801) and (Return.Mission() >= Return.CampFlag(801) + 4) and (Return.TargetAlive("Turkish Naval Convoy 1") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("Turkish Naval Convoy 1 T2.stm")',
			[2] = 'Action.Text("Turkish naval forces are shipping reinforcement to Cyprus. One convoy is near a Famagusta port in East Cyprus")',
		},
		['active'] = true,
	},
	['Reinforce 134.Filo'] = {
		['condition'] = 'true',
		['action'] = 'Action.AirUnitReinforce("134.Filo")',
		['active'] = true,
	},
	['Greek Naval Convoy in port after NCF victory'] = {
		['condition'] = 'Return.CampFlag(802) and (Return.Mission() >= Return.CampFlag(802) + 4) and (Return.TargetAlive("Greek Naval Convoy") > 40)',
		['once'] = true,
		['action'] = {
			[6] = 'Action.Text("Greek naval forces are shipping reinforcement to Cyprus. One convoy is unloading troops and a Hawk battery in Paphos harbor")',
			[2] = 'Action.TemplateActive("Greek Expeditionary Force 1 T1.stm")',
			[8] = 'Action.SetCampFlag(808, Return.Mission())',
			[3] = 'Action.TargetActive("Greek Expeditionary Force 1", true)',
			[1] = 'Action.TemplateActive("Greek Naval Convoy T3.stm")',
			[4] = 'Action.TemplateActive("Greek Hawk Battery 1 T1.stm")',
			[5] = 'Action.TargetActive("Greek Hawk Battery 1", true)',
			[7] = 'Action.AddImage("GEF1-1.png")',
		},
		['active'] = false,
	},
	['Turkish Naval Convoi 1 in port after Greece involvement'] = {
		['condition'] = 'Return.CampFlag(802) and (Return.Mission() >= Return.CampFlag(802) + 6) and (Return.TargetAlive("Turkish Naval Convoy 1") > 40)',
		['once'] = true,
		['action'] = {
			[6] = 'Action.Text("Turkish naval forces are shipping reinforcement to Cyprus. One convoy is unloading troops in Famagusta port in East Cyprus")',
			[2] = 'Action.TemplateActive("North Cyprus-Turkish Force 2 T1.stm")',
			[8] = 'Action.SetCampFlag(805, Return.Mission())',
			[3] = 'Action.TargetActive("North Cyprus-Turkish Force 2", true)',
			[1] = 'Action.TemplateActive("Turkish Naval Convoy 1 T3.stm")',
			[4] = 'Action.TemplateActive("Turkish Hawk Battery 2 T1.stm")',
			[5] = 'Action.TargetActive("Turkish Hawk Battery 2", true)',
			[7] = 'Action.AddImage("NCTF2-1.png")',
		},
		['active'] = false,
	},
	['North Cyprus Force 3 initial positions'] = {
		['condition'] = 'Return.Mission() >0',
		['once'] = true,
		['action'] = {
			[2] = 'Action.TargetActive("North Cyprus Force 3", true)',
			[3] = 'Action.Text("North Cyprus columns crossed the No man s land and are coming from the close South east of Nicosia")',
			[1] = 'Action.TemplateActive("North Cyprus Force 3 T1.stm")',
			[4] = 'Action.TemplateActive("Cyprus Border Force 4 T1.stm")',
			[5] = 'Action.TargetActive("Cyprus Border Force 4", true)',
		},
		['active'] = false,
	},
	['Cyprus Defense Force 1 stop'] = {
		['condition'] = 'Return.TargetAlive("Cyprus Defense Force 1") < 40',
		['once'] = true,
		['action'] = {
			[1] = 'Action.Text("Cyprus Defense Force 1 took heavy losses and is stopped")',
		},
		['active'] = true,
	},
	['Greek Expeditionary Force 1 stop'] = {
		['condition'] = 'Return.TargetAlive("Greek Expeditionary Force 1") < 40',
		['once'] = true,
		['action'] = {
			[1] = 'Action.Text("Greek Expeditionary column 1 took heavy losses and is stopped")',
		},
		['active'] = true,
	},
	['Turkish Naval Convoi 2 activation after Greece involvement'] = {
		['condition'] = 'Return.CampFlag(802) and (Return.Mission() >= Return.CampFlag(802) + 3)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("Turkish Naval Convoy 2 T1.stm")',
			[2] = 'Action.TargetActive("Turkish Naval Convoy 2", true)',
			[3] = 'Action.Text("Turkish naval forces are shipping reinforcement to Cyprus. One convoy just lived Turkish coasts to rejoin south east port in Cyprus")',
		},
		['active'] = false,
	},
	['Cyprus Defense Force 2 stop'] = {
		['condition'] = 'Return.TargetAlive("Cyprus Defense Force 2") < 40',
		['once'] = true,
		['action'] = {
			[1] = 'Action.Text("Cyprus Defense Force 2 took heavy losses and is stopped")',
		},
		['active'] = true,
	},
	['Turkish Naval Convoi 2 in port'] = {
		['condition'] = 'Return.CampFlag(801) and (Return.Mission() >= Return.CampFlag(801) + 7) and (Return.TargetAlive("Turkish Naval Convoy 2") > 40)',
		['once'] = true,
		['action'] = {
			[6] = 'Action.SetCampFlag(806, Return.Mission())',
			[2] = 'Action.TemplateActive("North Cyprus-Turkish Force 3 T1.stm")',
			[3] = 'Action.TargetActive("North Cyprus-Turkish Force 3", true)',
			[1] = 'Action.TemplateActive("Turkish Naval Convoy 2 T3.stm")',
			[4] = 'Action.Text("Turkish naval forces are shipping reinforcement to Cyprus. One convoy is unloading troops in Kyrenia port in North Cyprus")',
			[5] = 'Action.AddImage("NCTF3-1.png")',
		},
		['active'] = true,
	},
	['Cyprus Defense Force 5 move 2'] = {
		['condition'] = 'Return.CampFlag(801) and (Return.Mission() >= Return.CampFlag(801) + 5) and (Return.TargetAlive("Cyprus Defense Force 5") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("Cyprus Defense Force 5 T2.stm")',
			[2] = 'Action.AddImage("CDF5-2.png")',
			[3] = 'Action.Text("Cyprus Defense Force 5 is still moving")',
		},
		['active'] = true,
	},
	['North Cyprus-Turkish Force 1 retreat 4'] = {
		['condition'] = '(Return.Mission() > 23) and Return.CampFlag(831) and (Return.CampFlag(824) or Return.CampFlag(823)) and (Return.TargetAlive("Cyprus Defense Force 4") == Return.TargetAlive("North Cyprus-Turkish Force 1") or Return.TargetAlive("Cyprus Defense Force 3") == Return.TargetAlive("North Cyprus-Turkish Force 1"))',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("North Cyprus-Turkish Force 1 T2.stm")',
			[2] = 'Action.SetCampFlag(851, 0)',
		},
		['active'] = true,
	},
	['Larnaca Turkish Assault Force retreat 4'] = {
		['condition'] = '(Return.Mission() > 23) and Return.CampFlag(804) and Return.CampFlag(843) and (Return.TargetAlive("Greek Expeditionary Force 3") == Return.TargetAlive("Larnaca Turkish Assault Force 1"))',
		['once'] = true,
		['action'] = {
			[2] = 'Action.SideBase("blue", "Larnaca Airbase")',
			[3] = 'Action.TemplateActive("Larnaca Cyprus defenses T1.stm")',
			[1] = 'Action.TemplateActive("Larnaca Turkish Assault Force 1 T1.stm")',
			[4] = 'Action.TemplateActive("Larnaca Turkish AA T2.stm")',
			[5] = 'Action.SetCampFlag(855, 0)',
		},
		['active'] = false,
	},
	['Helicopters Gazelle Squadron near front move'] = {
		['condition'] = 'Return.CampFlag(801) and (Return.Mission() >= Return.CampFlag(801) + 2)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.AirUnitBase("450 M-E/P-2", "FARP-Dallas")',
			[2] = 'Action.Text("After Gazelle quick Paphos Airbase redeployment, we decided to use a mountain FARP to be closer from the frontline. FARP-Dallas will be perfect for that. FARP_Dallas position is 17 NM from EWR-Eyeball to 115° just near FARP-London")',
		},
		['active'] = true,
	},
	['Reinforce EC 331'] = {
		['condition'] = 'true',
		['action'] = 'Action.AirUnitReinforce("EC 331")',
		['active'] = true,
	},
	['North Cyprus-Turkish Force 1 retreat'] = {
		['condition'] = '(Return.Mission() > 23) and Return.CampFlag(831) and (Return.CampFlag(824) or Return.CampFlag(823)) and (Return.TargetAlive("Cyprus Defense Force 4") > Return.TargetAlive("North Cyprus-Turkish Force 1") or Return.TargetAlive("Cyprus Defense Force 3") > Return.TargetAlive("North Cyprus-Turkish Force 1"))',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("North Cyprus-Turkish Force 1 T2.stm")',
			[2] = 'Action.SetCampFlag(851, 0)',
		},
		['active'] = true,
	},
	['Greek Expeditionary Force 3 Activation'] = {
		['condition'] = 'Return.CampFlag(809) and (Return.Mission() >= Return.CampFlag(809) + 1) and (Return.TargetAlive("Greek Naval Convoy 2") > 40)',
		['once'] = true,
		['action'] = {
			[2] = 'Action.TargetActive("Greek Expeditionary Force 3", true)',
			[3] = 'Action.Text("Greek naval forces are shipping reinforcement to Cyprus. One convoy is unloading troops in Limassol harbor")',
			[1] = 'Action.TemplateActive("Greek Expeditionary Force 3 T1.stm")',
			[4] = 'Action.AddImage("GEF2-3-1.png")',
			[5] = 'Action.SetCampFlag(810, Return.Mission())',
		},
		['active'] = false,
	},
	['North Cyprus Force 1 stop'] = {
		['condition'] = 'Return.TargetAlive("North Cyprus Force 1") < 40',
		['once'] = true,
		['action'] = {
			[1] = 'Action.Text("North Cyprus columns to the far South west of Nicosia took heavy losses and are stopped")',
		},
		['active'] = true,
	},
	['Campaign End Victory 2'] = {
		['condition'] = 'GroundTarget["blue"].percent < 60',
		['once'] = false,
		['action'] = {
			[2] = 'Action.Text("Cyprus forces were able to inflict great losses to Turkish Army with the precious help of Greek forces")',
			[3] = 'Action.AddImage("Newspaper_Victory_blue.jpg", "blue")',
			[1] = 'Action.CampaignEnd("win")',
			[4] = 'Action.AddImage("Newspaper_Defeat_red.jpg", "red")',
			[5] = 'NoMoreNewspaper = true',
		},
		['active'] = true,
	},
	['North Cyprus-Turkish Force 4 airborn Stats'] = {
		['condition'] = 'Return.PlaceLogistic("Ercan Airbase") < 60000 ',
		['once'] = false,
		['action'] = {
			[1] = 'Action.LogisticObjectif("Ercan Airbase", 60000)',
		},
		['active'] = true,
	},
	['Campaign End Loss'] = {
		['condition'] = 'Return.AirUnitAlive("450 M-E/P-1") < 2',
		['once'] = false,
		['action'] = {
			[2] = 'Action.Text("Ongoing combat operations have exhausted 450 M-E/P-1. Loss rate has reached a level where reinforcements are no longer able to sustain combat operations. Your unit has been wiped out by the enemy.")',
			[3] = 'Action.AddImage("Newspaper_Victory_red.jpg", "red")',
			[1] = 'Action.CampaignEnd("loss")',
			[4] = 'Action.AddImage("Newspaper_Defeat_blue.jpg", "blue")',
			[5] = 'NoMoreNewspaper = true',
		},
		['active'] = true,
	},
	['North Cyprus-Turkish Force 4 Victory 2'] = {
		['condition'] = '(Return.Mission() > 23) and Return.CampFlag(834) and ((Return.CampFlag(822) == nil) or (Return.CampFlag(842) == nil))',
		['once'] = true,
		['action'] = {
			[1] = 'Action.SetCampFlag(854, 1)',
		},
		['active'] = true,
	},
	['Turkish Artillery Force 1 activation'] = {
		['condition'] = 'Return.CampFlag(801) and (Return.Mission() > Return.CampFlag(801) + 1)',
		['once'] = false,
		['action'] = {
			[1] = 'Action.TemplateActive("Turkish Artillery Force 1 T1.stm","Turkish Artillery Force 1 T2.stm","Turkish Artillery Force 1 T3.stm")',
			[2] = 'Action.TargetActive("Turkish Artillery Force 1", true)',
			[4] = 'Action.AddImage("TurkishArtillery.png")',
			[3] = 'Action.Text("A Turkish artillery battery is pounding Lakatamia Airbase, it seems to move often so it will be difficult to localize it")',
		},
		['active'] = true,
	},
	['Turkish CAP activation after Greece involvement'] = {
		['condition'] = 'Return.CampFlag(802) and (Return.Mission() >= Return.CampFlag(802) + 2)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TargetActive("CAP-1-Turkish", true)',
			[2] = 'Action.Text("It seems that enemy aircraft CAP are active over North part of Cyprus")',
		},
		['active'] = false,
	},
	['Campaign End Loss 2'] = {
		['condition'] = 'GroundTarget["red"].percent < 40',
		['once'] = false,
		['action'] = {
			[2] = 'Action.Text("Turkish airforce was able to destroy enough Greek and Cyprus forces to decide them to ask for a cease fire  and stop any Air missions. This is a bitter failure for the people of Cyprus ")',
			[3] = 'Action.AddImage("Newspaper_Victory_red.jpg", "red")',
			[1] = 'Action.CampaignEnd("loss")',
			[4] = 'Action.AddImage("Newspaper_Defeat_blue.jpg", "blue")',
			[5] = 'NoMoreNewspaper = true',
		},
		['active'] = true,
	},
	['Cyprus Defense Force 2 move 3'] = {
		['condition'] = 'Return.CampFlag(801) and (Return.Mission() >= Return.CampFlag(801) + 7) and (Return.TargetAlive("Cyprus Defense Force 2") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("Cyprus Defense Force 2 T3.stm")',
			[2] = 'Action.AddImage("CDF2-3.png")',
			[4] = 'Action.SetCampFlag(822, Return.Mission())',
			[3] = 'Action.Text("Cyprus Defense Force 2 reached defensives positions")',
		},
		['active'] = true,
	},
	['Repair'] = {
		['condition'] = 'true',
		['action'] = 'Action.AirUnitRepair()',
		['active'] = true,
	},
	['Greek Expeditionary Force 1 move 4'] = {
		['condition'] = 'Return.CampFlag(808) and (Return.Mission() >= Return.CampFlag(808) + 7) and (Return.TargetAlive("Greek Expeditionary Force 1") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("Greek Expeditionary Force 1 T4.stm")',
			[2] = 'Action.Text("Greek Expeditionary column 1 stopped 20 nm West of Nicosia ")',
			[4] = 'Action.SetCampFlag(841, Return.Mission())',
			[3] = 'Action.AddImage("GEF1-4.png")',
		},
		['active'] = false,
	},
	['Cyprus Defense Forces activation after North Cyprus attack'] = {
		['condition'] = 'Return.CampFlag(802)',
		['once'] = true,
		['action'] = {
			[7] = 'Action.TemplateActive("Cyprus Defense Force 4 T1.stm")',
			[1] = 'Action.TemplateActive("Cyprus Defense Force 1 T1.stm")',
			[2] = 'Action.TargetActive("Cyprus Defense Force 1", true)',
			[4] = 'Action.TargetActive("Cyprus Defense Force 2", true)',
			[8] = 'Action.TargetActive("Cyprus Defense Force 4", true)',
			[9] = 'Action.TemplateActive("Cyprus Defense Force 5 T1.stm")',
			[5] = 'Action.TemplateActive("Cyprus Defense Force 3 T1.stm")',
			[10] = 'Action.TargetActive("Cyprus Defense Force 5", true)',
			[3] = 'Action.TemplateActive("Cyprus Defense Force 2 T1.stm")',
			[6] = 'Action.TargetActive("Cyprus Defense Force 3", true)',
			[12] = 'Action.Text("After North Cyprus attack our Defense Forces have been mobilized and are moving to the frontline")',
			[11] = 'Action.AddImage("CDF.png")',
		},
		['active'] = false,
	},
	['Greek Naval Convoy 2 in port'] = {
		['condition'] = 'Return.CampFlag(801) and (Return.Mission() >= Return.CampFlag(801) + 8) and (Return.TargetAlive("Greek Naval Convoy 2") > 40)',
		['once'] = true,
		['action'] = {
			[7] = 'Action.Text("Greek naval forces are shipping reinforcement to Cyprus. One convoy is unloading troops in Limassol harbor")',
			[1] = 'Action.TemplateActive("Greek Naval Convoy 2 T3.stm")',
			[2] = 'Action.TemplateActive("Greek Expeditionary Force 2 T1.stm")',
			[4] = 'Action.TemplateActive("Greek Expeditionary Force 3 T1.stm")',
			[8] = 'Action.AddImage("GEF2-3-1.png")',
			[9] = 'Action.SetCampFlag(809, Return.Mission())',
			[5] = 'Action.TargetActive("Greek Expeditionary Force 3", true)',
			[3] = 'Action.TargetActive("Greek Expeditionary Force 2", true)',
			[6] = 'Action.TemplateActive("Greek Limassol defenses T1.stm")',
		},
		['active'] = true,
	},
	['North Cyprus Force 1 move 2'] = {
		['condition'] = 'Return.Mission() > 1 and (Return.TargetAlive("North Cyprus Force 1") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("North Cyprus Force 1 T2.stm")',
			[2] = 'Action.Text("North Cyprus columns are still moving in the south west suburbs of Nicosia")',
			[4] = 'Action.TemplateActive("Cyprus Border Force 2 T2.stm")',
			[3] = 'Action.TemplateActive("Cyprus Border Force 1 T2.stm")',
		},
		['active'] = false,
	},
	['Campaign End Loss 1'] = {
		['condition'] = '(Return.Mission() > 26) and (Return.CampFlag(851) + Return.CampFlag(852) + Return.CampFlag(853) + Return.CampFlag(854) + Return.CampFlag(855) + Return.CampFlag(856)) > 2',
		['once'] = false,
		['action'] = {
			[2] = 'Action.Text("North Cyprus Forces gain lot of territories with Turkish forces help. We will have to negociate a cease fire in really bad conditions")',
			[3] = 'Action.AddImage("Newspaper_Victory_red.jpg", "red")',
			[1] = 'Action.CampaignEnd("loss")',
			[4] = 'Action.AddImage("Newspaper_Defeat_blue.jpg", "blue")',
			[5] = 'NoMoreNewspaper = true',
		},
		['active'] = true,
	},
	['Turkish involvement'] = {
		['condition'] = '((Return.TargetAlive("North Cyprus Force 1") < 40 and Return.TargetAlive("North Cyprus Force 2") < 40) or (Return.TargetAlive("North Cyprus Force 3") < 40 and Return.TargetAlive("North Cyprus Force 4") < 40)) and ( Return.CampFlag(802) == nil or Return.CampFlag(802) <= 0)',
		['once'] = true,
		['action'] = {
			[7] = 'Action.TargetActive("Airlift Ercan Airbase 3", true)',
			[1] = 'Action.AirUnitActive("111.Filo", true)',
			[2] = 'Action.AirUnitActive("134.Filo", true)',
			[4] = 'Action.AirUnitActive("2nd-2 KHA", true)',
			[8] = 'Action.Text("North Cyprus columns have been crippled but it seems that turkish forces will try to rescue their allies sending heavy reinforcements")',
			[9] = 'Action.SetCampFlag(801, Return.Mission())',
			[5] = 'Action.TargetActive("CAP-1-Turkish", true)',
			[3] = 'Action.AirUnitActive("2nd KHA", true)',
			[6] = 'Action.TargetActive("Airlift Ercan Airbase 2", true)',
		},
		['active'] = true,
	},
	['Larnaca Airbase Captured after Greece involvement'] = {
		['condition'] = 'Return.CampFlag(802) and (Return.Mission() >= Return.CampFlag(802) + 6) and (Return.TargetAlive("Larnaca Turkish Assault Force 1") > 40)',
		['once'] = true,
		['action'] = {
			[2] = 'Action.TemplateActive("Larnaca Turkish Assault Force 1 T2.stm")',
			[3] = 'Action.SideBase("red", "Larnaca Airbase")',
			[1] = 'Action.TemplateActive("Larnaca Cyprus defenses T2.stm")',
			[4] = 'Action.Text("Larnaca Airbase has been captured by Turkish forces.")',
			[5] = 'Action.SetCampFlag(804, Return.Mission())',
		},
		['active'] = false,
	},
	['Helicopters Gazelle Squadron Move after Greece involvement'] = {
		['condition'] = 'Return.CampFlag(802) and (Return.Mission() >= Return.CampFlag(802) + 4)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.AirUnitBase("450 M-E/P-2", "Paphos Airbase")',
			[2] = 'Action.Text("Larnaca airbase is under attack. Despite Greece involvement we must retreat our Gazelle frontline helicopters unit to Paphos airbase")',
		},
		['active'] = false,
	},
	['North Cyprus-Turkish Force 1 Victory'] = {
		['condition'] = '(Return.Mission() > 23) and Return.CampFlag(831) and (Return.CampFlag(824) or Return.CampFlag(823)) and (Return.TargetAlive("Cyprus Defense Force 4") < Return.TargetAlive("North Cyprus-Turkish Force 1") or Return.TargetAlive("Cyprus Defense Force 3") < Return.TargetAlive("North Cyprus-Turkish Force 1"))',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("Cyprus Defense Force 4 T2.stm")',
			[2] = 'Action.TemplateActive("Cyprus Defense Force 3 T2.stm")',
			[3] = 'Action.SetCampFlag(851, 1)',
		},
		['active'] = true,
	},
	['North Cyprus Force 2 move 3'] = {
		['condition'] = 'Return.Mission() > 2 and (Return.TargetAlive("North Cyprus Force 2") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("North Cyprus Force 2 T3.stm")',
			[2] = 'Action.Text("North Cyprus columns are still moving in the south west suburbs of Nicosia")',
			[3] = 'Action.TemplateActive("Cyprus Border Force 3 T3.stm")',
		},
		['active'] = false,
	},
	['Helicopters Hind Squadron near front move'] = {
		['condition'] = 'Return.CampFlag(803) and (Return.Mission() >= Return.CampFlag(803) + 1)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.AirUnitBase("450 M-E/P-1", "FARP-London")',
			[2] = 'Action.Text("After Hind quick Paphos Airbase redeployment, we decided to use a mountain FARP to be closer from the frontline. FARP-London will be perfect for that. FARP_London position is 16 NM from EWR-Eyeball to 115° just near FARP-Dallas")',
		},
		['active'] = false,
	},
	['Reinforce 111.Filo'] = {
		['condition'] = 'true',
		['action'] = 'Action.AirUnitReinforce("111.Filo")',
		['active'] = true,
	},
	['Turkish Naval Convoi 1 activation'] = {
		['condition'] = 'Return.CampFlag(801) and (Return.Mission() >= Return.CampFlag(801) + 2)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("Turkish Naval Convoy 1 T1.stm")',
			[2] = 'Action.TargetActive("Turkish Naval Convoy 1", true)',
			[3] = 'Action.Text("Turkish naval forces are shipping reinforcement to Cyprus. One convoy just lived Turkish coasts to rejoin south east port in Cyprus")',
		},
		['active'] = true,
	},
	['Blue Ground Target Briefing Intel'] = {
		['condition'] = 'true',
		['action'] = 'Action.AddGroundTargetIntel("blue")',
		['active'] = true,
	},
	['Reinforce 2nd-2 KHA'] = {
		['condition'] = 'true',
		['action'] = 'Action.AirUnitReinforce("2nd-2 KHA")',
		['active'] = true,
	},
	['Greek Naval Convoy 2 mouvement'] = {
		['condition'] = 'Return.CampFlag(801) and (Return.Mission() >= Return.CampFlag(801) + 6) and (Return.TargetAlive("Greek Naval Convoy 2") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("Greek Naval Convoy 2 T2.stm")',
			[2] = 'Action.Text("Greek naval forces are shipping reinforcement to Cyprus.")',
		},
		['active'] = true,
	},
	['Cyprus Defense Force 2 move 2'] = {
		['condition'] = 'Return.CampFlag(801) and (Return.Mission() >= Return.CampFlag(801) + 5) and (Return.TargetAlive("Cyprus Defense Force 2") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("Cyprus Defense Force 2 T2.stm")',
			[2] = 'Action.AddImage("CDF2-2.png")',
			[3] = 'Action.Text("Cyprus Defense Force 2 is still moving")',
		},
		['active'] = true,
	},
	['Larnaca Airbase Turkish AA Defenses'] = {
		['condition'] = 'Return.CampFlag(804)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("Larnaca Turkish AA T1.stm")',
		},
		['active'] = false,
	},
	['Reinforce 2nd KHA'] = {
		['condition'] = 'true',
		['action'] = 'Action.AirUnitReinforce("2nd KHA")',
		['active'] = true,
	},
	['Cyprus Border Force 6 initial positions'] = {
		['condition'] = 'Return.Mission() > 0',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("Cyprus Border Force 6 T1.stm")',
			[2] = 'Action.TargetActive("Cyprus Border Force 6", true)',
		},
		['active'] = false,
	},
	['Cyprus Defense Force 2 move 3 after North Cyprus attack'] = {
		['condition'] = 'Return.CampFlag(802) and (Return.Mission() >= Return.CampFlag(802) + 5) and (Return.TargetAlive("Cyprus Defense Force 2") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("Cyprus Defense Force 2 T3.stm")',
			[2] = 'Action.AddImage("CDF2-3.png")',
			[4] = 'Action.SetCampFlag(822, Return.Mission())',
			[3] = 'Action.Text("Cyprus Defense Force 2 reached defensives positions")',
		},
		['active'] = false,
	},
	['North Cyprus-Turkish Force 2 retreat 4'] = {
		['condition'] = '(Return.Mission() > 23) and Return.CampFlag(832) and (Return.CampFlag(821) or Return.CampFlag(842)) and (Return.TargetAlive("Greek Expeditionary Force 2") == Return.TargetAlive("North Cyprus-Turkish Force 2") or Return.TargetAlive("Cyprus Defense Force 1") == Return.TargetAlive("North Cyprus-Turkish Force 2"))',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("North Cyprus-Turkish Force 4 T2.stm")',
			[2] = 'Action.SetCampFlag(852, 0)',
		},
		['active'] = true,
	},
	['Reinforce 450 M-E/P-1'] = {
		['condition'] = 'true',
		['action'] = 'Action.AirUnitReinforce("450 M-E/P-1")',
		['active'] = true,
	},
	['North Cyprus-Turkish Force 4 airborn activation'] = {
		['condition'] = 'Return.PlaceLogistic("Ercan Airbase") > 60000 and (Return.CampFlag(801) or Return.CampFlag(802))',
		['once'] = true,
		['action'] = {
			[2] = 'Action.TargetActive("North Cyprus-Turkish Force 4", true)',
			[3] = 'Action.Text("Heavy Turkish Force 4 is readying in Ercan airbase")',
			[1] = 'Action.TemplateActive("North Cyprus-Turkish Force 4 T1.stm")',
			[4] = 'Action.AddImage("NCTF4-1.png")',
			[5] = 'Action.SetCampFlag(807, Return.Mission())',
		},
		['active'] = true,
	},
	['Cyprus Defense Force 3 move 3 after North Cyprus attack'] = {
		['condition'] = 'Return.CampFlag(802) and (Return.Mission() >= Return.CampFlag(802) + 5) and (Return.TargetAlive("Cyprus Defense Force 3") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("Cyprus Defense Force 3 T3.stm")',
			[2] = 'Action.AddImage("CDF3-3.png")',
			[4] = 'Action.SetCampFlag(823, Return.Mission())',
			[3] = 'Action.Text("Cyprus Defense Force 3 reached defensives positions")',
		},
		['active'] = false,
	},
	['GroundUnitRepair'] = {
		['condition'] = 'true',
		['action'] = 'Action.GroundUnitRepair()',
		['active'] = true,
	},
	['Turkish Artillery ops'] = {
		['condition'] = '(Return.Mission() > 23) and (Return.TargetAlive("Turkish Artillery Force 1") >= 20)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.SetCampFlag(856, 1)',
		},
		['active'] = false,
	},
	['North Cyprus-Turkish Force 1 initial positions after Greece involvement'] = {
		['condition'] = 'Return.CampFlag(802) and (Return.Mission() >= Return.CampFlag(802) + 2)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("North Cyprus-Turkish Force 1 T1.stm")',
			[2] = 'Action.TargetActive("North Cyprus-Turkish Force 1", true)',
			[4] = 'Action.AddImage("NCTF1-1.png")',
			[3] = 'Action.Text("An heavy Turkish column has been detected on the main road between Famagusta and Nicosia just South of Gecitkale airbase. It seems that turkish army will get fully involved in this war. Be careful Turkish forces learned quickly from their allies defeat and heavy Air defenses are part of their columns now.")',
		},
		['active'] = false,
	},
	['Larnaca Turkish Assault Force retreat 3'] = {
		['condition'] = '(Return.Mission() > 23) and (Return.CampFlag(804) == nil) and (Return.CampFlag(843) == nil)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.SetCampFlag(855, 0)',
		},
		['active'] = true,
	},
	['Cyprus Border Force 1 initial positions'] = {
		['condition'] = 'Return.Mission() > 0',
		['once'] = true,
		['action'] = {
			[2] = 'Action.TargetActive("Cyprus Border Force 1", true)',
			[3] = 'Action.TemplateActive("Ercan Airbase Defenses T1.stm")',
			[1] = 'Action.TemplateActive("Cyprus Border Force 1 T1.stm")',
			[4] = 'Action.TemplateActive("Larnaca Cyprus defenses T1.stm")',
			[5] = 'Action.TargetActive("Larnaca Cyprus defenses", true)',
		},
		['active'] = false,
	},
	['North Cyprus-Turkish Force 1 move 4'] = {
		['condition'] = 'Return.CampFlag(801) and (Return.Mission() >= Return.CampFlag(801) + 7) and (Return.TargetAlive("North Cyprus-Turkish Force 1") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("North Cyprus-Turkish Force 1 T4.stm")',
			[2] = 'Action.Text("Heavy Turkish column 1 stopped moving near ")',
			[4] = 'Action.SetCampFlag(831, Return.Mission())',
			[3] = 'Action.AddImage("NCTF1-4.png")',
		},
		['active'] = true,
	},
	['Cyprus Defense Force 5 stop'] = {
		['condition'] = 'Return.TargetAlive("Cyprus Defense Force 5") < 40',
		['once'] = true,
		['action'] = {
			[1] = 'Action.Text("Cyprus Defense Force 5 took heavy losses and is stopped")',
		},
		['active'] = true,
	},
	['North Cyprus-Turkish Force 3 retreat 3'] = {
		['condition'] = '(Return.Mission() > 23) and (Return.CampFlag(833) == nil) and ((Return.CampFlag(825) == nil) or (Return.CampFlag(841) == nil))',
		['once'] = true,
		['action'] = {
			[1] = 'Action.SetCampFlag(853, 0)',
		},
		['active'] = true,
	},
	['North Cyprus Force First Victory - Greece involvement'] = {
		['condition'] = 'Return.Mission() > 4 and ((Return.TargetAlive("North Cyprus Force 1") > 40 or Return.TargetAlive("North Cyprus Force 2") > 40) and (Return.TargetAlive("North Cyprus Force 3") > 40 or Return.TargetAlive("North Cyprus Force 4") > 40))',
		['once'] = true,
		['action'] = {
			[7] = 'Action.TargetActive("CAP-1-Greek", true)',
			[1] = 'Action.AirUnitActive("EC 331", true)',
			[2] = 'Action.TargetActive("Paphos Airbase Alert", true)',
			[4] = 'Action.TargetActive("Paphos Airbase Alert 3", true)',
			[8] = 'Action.Text("North Cyprus columns are circling Nicosia and will soon be able to capture the city. Greece can t tolerate that and decided to help Cyprus. EC 331 is sent to help Cyprus to destroy North Cyprus forces with its Mirage 2000C and soon more Ground forces will be projected to protect Cyprus")',
			[9] = 'Action.SetCampFlag(802, Return.Mission())',
			[5] = 'Action.TargetActive("Airlift Paphos Airbase 2", true)',
			[3] = 'Action.TargetActive("Paphos Airbase Alert 2", true)',
			[6] = 'Action.TargetActive("Airlift Paphos Airbase 3", true)',
		},
		['active'] = false,
	},
	['Cyprus Defense Force 4 move 3 after North Cyprus attack'] = {
		['condition'] = 'Return.CampFlag(802) and (Return.Mission() >= Return.CampFlag(802) + 5) and (Return.TargetAlive("Cyprus Defense Force 4") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("Cyprus Defense Force 4 T3.stm")',
			[2] = 'Action.AddImage("CDF4-3.png")',
			[4] = 'Action.SetCampFlag(824, Return.Mission())',
			[3] = 'Action.Text("Cyprus Defense Force 4 reached defensives positions")',
		},
		['active'] = false,
	},
	['North Cyprus-Turkish Force 2 retreat 3'] = {
		['condition'] = '(Return.Mission() > 23) and (Return.CampFlag(832) == nil) and ((Return.CampFlag(821) == nil) or (Return.CampFlag(842) == nil))',
		['once'] = true,
		['action'] = {
			[1] = 'Action.SetCampFlag(852, 0)',
		},
		['active'] = true,
	},
	['North Cyprus-Turkish Force 2 Victory'] = {
		['condition'] = '(Return.Mission() > 23) and Return.CampFlag(832) and (Return.CampFlag(821) or Return.CampFlag(842)) and (Return.TargetAlive("Greek Expeditionary Force 2") < Return.TargetAlive("North Cyprus-Turkish Force 2") or Return.TargetAlive("Cyprus Defense Force 1") < Return.TargetAlive("North Cyprus-Turkish Force 2"))',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("Cyprus Defense Force 1 T2.stm")',
			[2] = 'Action.TemplateActive("Greek Expeditionary Force 2 T2.stm")',
			[3] = 'Action.SetCampFlag(852, 1)',
		},
		['active'] = true,
	},
	['Turkish Artillery Force 1 activation after Greece involvement'] = {
		['condition'] = 'Return.CampFlag(802) and (Return.Mission() > Return.CampFlag(802) + 5)',
		['once'] = false,
		['action'] = {
			[1] = 'Action.TemplateActive("Turkish Artillery Force 1 T1.stm","Turkish Artillery Force 1 T2.stm","Turkish Artillery Force 1 T3.stm")',
			[2] = 'Action.TargetActive("Turkish Artillery Force 1", true)',
			[4] = 'Action.AddImage("TurkishArtillery.png")',
			[3] = 'Action.Text("A Turkish artillery battery is pounding Lakatamia Airbase, it seems to move often so it will be difficult to localize it")',
		},
		['active'] = true,
	},
	['Turkish Naval Convoi 1 mouvement after Greece involvement'] = {
		['condition'] = 'Return.CampFlag(802) and (Return.Mission() >= Return.CampFlag(802) + 4) and (Return.TargetAlive("Turkish Naval Convoy 1") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("Turkish Naval Convoy 1 T2.stm")',
			[2] = 'Action.Text("Turkish naval forces are shipping reinforcement to Cyprus. One convoy is near Famagusta port in East Cyprus")',
		},
		['active'] = false,
	},
	['North Cyprus-Turkish Force 2 move 4'] = {
		['condition'] = 'Return.CampFlag(805) and (Return.Mission() >= Return.CampFlag(805) + 7) and (Return.TargetAlive("North Cyprus-Turkish Force 2") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("North Cyprus-Turkish Force 2 T4.stm")',
			[2] = 'Action.AddImage("NCTF2-4.png")',
			[3] = 'Action.Text("Heavy Turkish column 2 is still moving on the road between Kingsfield Airbase and Larnaca City")',
		},
		['active'] = false,
	},
	['Cyprus Defense Force 1 move 2'] = {
		['condition'] = 'Return.CampFlag(801) and (Return.Mission() >= Return.CampFlag(801) + 5) and (Return.TargetAlive("Cyprus Defense Force 1") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("Cyprus Defense Force 1 T2.stm")',
			[2] = 'Action.AddImage("CDF1-2.png")',
			[3] = 'Action.Text("Cyprus Defense Force 1 is still moving")',
		},
		['active'] = true,
	},
	['Cyprus Defense Force 4 stop'] = {
		['condition'] = 'Return.TargetAlive("Cyprus Defense Force 4") < 40',
		['once'] = true,
		['action'] = {
			[1] = 'Action.Text("Cyprus Defense Force 4 took heavy losses and is stopped")',
		},
		['active'] = true,
	},
	['North Cyprus-Turkish Force 4 retreat 4'] = {
		['condition'] = '(Return.Mission() > 23) and Return.CampFlag(834) and (Return.CampFlag(822) or Return.CampFlag(842)) and (Return.TargetAlive("Greek Expeditionary Force 2") == Return.TargetAlive("North Cyprus-Turkish Force 4") or Return.TargetAlive("Cyprus Defense Force 2") == Return.TargetAlive("North Cyprus-Turkish Force 4"))',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("North Cyprus-Turkish Force 4 T2.stm")',
			[2] = 'Action.SetCampFlag(854, 0)',
		},
		['active'] = true,
	},
	['North Cyprus-Turkish Force 3 retreat'] = {
		['condition'] = '(Return.Mission() > 23) and Return.CampFlag(833) and (Return.CampFlag(825) or Return.CampFlag(841)) and (Return.TargetAlive("Greek Expeditionary Force 1") > Return.TargetAlive("North Cyprus-Turkish Force 3") or Return.TargetAlive("Cyprus Defense Force 5") > Return.TargetAlive("North Cyprus-Turkish Force 3"))',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("North Cyprus-Turkish Force 3 T2.stm")',
			[2] = 'Action.SetCampFlag(853, 0)',
		},
		['active'] = true,
	},
	['Greek Expeditionary Force 4 move 4'] = {
		['condition'] = 'Return.CampFlag(811) and (Return.Mission() >= Return.CampFlag(811) + 6) and (Return.TargetAlive("Greek Expeditionary Force 4") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("Greek Expeditionary Force 4 T4.stm")',
			[2] = 'Action.Text("Greek Expeditionary column 4 is Stopped 5 nm south west of Lakatamia airbase")',
			[4] = 'Action.SetCampFlag(844, Return.Mission())',
			[3] = 'Action.AddImage("GEF4-4.png")',
		},
		['active'] = false,
	},
	['Greek Expeditionary Force 4 move 2'] = {
		['condition'] = 'Return.CampFlag(811) and (Return.Mission() >= Return.CampFlag(811) + 2) and (Return.TargetAlive("Greek Expeditionary Force 4") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("Greek Expeditionary Force 4 T2.stm")',
			[2] = 'Action.AddImage("GEF4-2.png")',
			[3] = 'Action.Text("Greek Expeditionary column 4 is still moving ")',
		},
		['active'] = false,
	},
	['Greek Expeditionary Force 1 move 2'] = {
		['condition'] = 'Return.CampFlag(808) and (Return.Mission() >= Return.CampFlag(808) + 3) and (Return.TargetAlive("Greek Expeditionary Force 1") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("Greek Expeditionary Force 1 T2.stm")',
			[2] = 'Action.AddImage("GEF1-2.png")',
			[3] = 'Action.Text("Greek Expeditionary column 1 is still moving ")',
		},
		['active'] = false,
	},
	['North Cyprus-Turkish Force 2 Victory 2'] = {
		['condition'] = '(Return.Mission() > 23) and Return.CampFlag(832) and ((Return.CampFlag(821) == nil) or (Return.CampFlag(842) == nil))',
		['once'] = true,
		['action'] = {
			[1] = 'Action.SetCampFlag(852, 1)',
		},
		['active'] = true,
	},
	['Greek Expeditionary Force 4 airborn activation'] = {
		['condition'] = 'Return.PlaceLogistic("Paphos Airbase") > 60000 and (Return.CampFlag(801) or Return.CampFlag(802))',
		['once'] = true,
		['action'] = {
			[2] = 'Action.TargetActive("Greek Expeditionary Force 4", true)',
			[3] = 'Action.Text("Greek Expeditionary Force 4 is readying in Paphos airbase")',
			[1] = 'Action.TemplateActive("Greek Expeditionary Force 4 T1.stm")',
			[4] = 'Action.AddImage("GEF4-1.png")',
			[5] = 'Action.SetCampFlag(811, Return.Mission())',
		},
		['active'] = false,
	},
	['Turkish Naval Convoi 2 in port after Greece involvement'] = {
		['condition'] = 'Return.CampFlag(802) and (Return.Mission() >= Return.CampFlag(802) + 7) and (Return.TargetAlive("Turkish Naval Convoy 2") > 40)',
		['once'] = true,
		['action'] = {
			[6] = 'Action.SetCampFlag(806, Return.Mission())',
			[2] = 'Action.TemplateActive("North Cyprus-Turkish Force 3 T1.stm")',
			[3] = 'Action.TargetActive("North Cyprus-Turkish Force 3", true)',
			[1] = 'Action.TemplateActive("Turkish Naval Convoy 2 T3.stm")',
			[4] = 'Action.Text("Turkish naval forces are shipping reinforcement to Cyprus. One convoy is unloading troops in Kyrenia port in North Cyprus")',
			[5] = 'Action.AddImage("NCTF3-1.png")',
		},
		['active'] = false,
	},
	['Greek Expeditionary Force 3 stop'] = {
		['condition'] = 'Return.TargetAlive("Greek Expeditionary Force 3") < 40',
		['once'] = true,
		['action'] = {
			[1] = 'Action.Text("Greek Expeditionary column 3 took heavy losses and is stopped")',
		},
		['active'] = true,
	},
	['North Cyprus Forces no more targeted'] = {
		['condition'] = 'Return.CampFlag(801)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TargetActive("North Cyprus Force 1", false)',
			[2] = 'Action.TargetActive("North Cyprus Force 2", false)',
			[4] = 'Action.TargetActive("North Cyprus Force 4", false)',
			[3] = 'Action.TargetActive("North Cyprus Force 3", false)',
		},
		['active'] = true,
	},
	['Larnaca Turkish Assault Force Victory 2'] = {
		['condition'] = '(Return.Mission() > 23) and Return.CampFlag(804) and (Return.CampFlag(843) == nil)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.SetCampFlag(855, 1)',
		},
		['active'] = true,
	},
	['North Cyprus-Turkish Force 2 stop'] = {
		['condition'] = 'Return.TargetAlive("North Cyprus-Turkish Force 2") < 40',
		['once'] = true,
		['action'] = {
			[1] = 'Action.Text("Heavy Turkish column 2 took heavy losses and is stopped")',
		},
		['active'] = true,
	},
	['North Cyprus-Turkish Force 1 stop'] = {
		['condition'] = 'Return.TargetAlive("North Cyprus-Turkish Force 1") < 40',
		['once'] = true,
		['action'] = {
			[1] = 'Action.Text("Heavy Turkish column 1 took heavy losses and is stopped")',
		},
		['active'] = true,
	},
	['Red Ground Target Briefing Intel'] = {
		['condition'] = 'true',
		['action'] = 'Action.AddGroundTargetIntel("red")',
		['active'] = true,
	},
	['Reinforce 3rd KHA'] = {
		['condition'] = 'true',
		['action'] = 'Action.AirUnitReinforce("3rd KHA")',
		['active'] = true,
	},
	['Cyprus Defense Force 1 move 3'] = {
		['condition'] = 'Return.CampFlag(801) and (Return.Mission() >= Return.CampFlag(801) + 7) and (Return.TargetAlive("Cyprus Defense Force 1") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("Cyprus Defense Force 1 T3.stm")',
			[2] = 'Action.AddImage("CDF1-3.png")',
			[4] = 'Action.SetCampFlag(821, Return.Mission())',
			[3] = 'Action.Text("Cyprus Defense Force 1 reached defensives positions")',
		},
		['active'] = true,
	},
	['North Cyprus-Turkish Force 3 retreat 2'] = {
		['condition'] = '(Return.Mission() > 23) and (Return.CampFlag(833) == nil) and (Return.CampFlag(825) or Return.CampFlag(841))',
		['once'] = true,
		['action'] = {
			[1] = 'Action.SetCampFlag(853, 0)',
		},
		['active'] = true,
	},
	['Helicopters Gazelle Squadron near front move after Greece involvement'] = {
		['condition'] = 'Return.CampFlag(802) and (Return.Mission() >= Return.CampFlag(802) + 5)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.AirUnitBase("450 M-E/P-2", "FARP-Dallas")',
			[2] = 'Action.Text("After Gazelle quick Paphos Airbase redeployment, we decided to use a mountain FARP to be closer from the frontline. FARP-Dallas will be perfect for that. FARP_Dallas position is 17 NM from EWR-Eyeball to 115° just near FARP-London")',
		},
		['active'] = false,
	},
	['Turkish Naval Convoi 1 activation after Greece involvement'] = {
		['condition'] = 'Return.CampFlag(802) and (Return.Mission() >= Return.CampFlag(802) + 2)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("Turkish Naval Convoy 1 T1.stm")',
			[2] = 'Action.TargetActive("Turkish Naval Convoy 1", true)',
			[3] = 'Action.Text("Turkish naval forces are shipping reinforcement to Cyprus. One convoy just lived Turkish coasts to rejoin south east port in Cyprus")',
		},
		['active'] = false,
	},
	['Greek Expeditionary Force 3 move 4'] = {
		['condition'] = 'Return.CampFlag(810) and (Return.Mission() >= Return.CampFlag(810) + 6) and (Return.TargetAlive("Greek Expeditionary Force 3") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("Greek Expeditionary Force 3 T4.stm")',
			[2] = 'Action.Text("Greek Expeditionary column 3 stopped 5nm south west of Larnaca Airbase")',
			[4] = 'Action.SetCampFlag(843, Return.Mission())',
			[3] = 'Action.AddImage("GEF3-4.png")',
		},
		['active'] = false,
	},
	['Campaign first destructions'] = {
		['condition'] = 'GroundTarget["blue"].percent < 100',
		['once'] = true,
		['action'] = {
			[1] = 'Action.Text("First targets have been destroyed. Keep up the good work")',
			[2] = 'Action.Text("Les premières cibles ont été détruites. Continuez votre bon travail")',
		},
		['active'] = true,
	},
	['North Cyprus-Turkish Force 2 move 3'] = {
		['condition'] = 'Return.CampFlag(805) and (Return.Mission() >= Return.CampFlag(805) + 5) and (Return.TargetAlive("North Cyprus-Turkish Force 2") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("North Cyprus-Turkish Force 2 T3.stm")',
			[2] = 'Action.AddImage("NCTF2-3.png")',
			[3] = 'Action.Text("Heavy Turkish column 2 is still moving 5 nm East of Kingsfield airbase")',
		},
		['active'] = false,
	},
	['North Cyprus Force 4 stop 1'] = {
		['condition'] = 'Return.TargetAlive("North Cyprus Force 4") < 40',
		['once'] = true,
		['action'] = {
			[1] = 'Action.Text("North Cyprus columns to the far South east of Nicosia took heavy losses and are stopped")',
		},
		['active'] = true,
	},
	['North Cyprus-Turkish Force 3 Victory 2'] = {
		['condition'] = '(Return.Mission() > 23) and Return.CampFlag(833) and ((Return.CampFlag(825) == nil) or (Return.CampFlag(841) == nil))',
		['once'] = true,
		['action'] = {
			[1] = 'Action.SetCampFlag(853, 1)',
		},
		['active'] = true,
	},
	['North Cyprus Force 3 move 3'] = {
		['condition'] = 'Return.Mission() > 2 and (Return.TargetAlive("North Cyprus Force 3") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("North Cyprus Force 3 T3.stm")',
			[2] = 'Action.Text("North Cyprus columns are still moving in the south east suburbs of Nicosia")',
			[3] = 'Action.TemplateActive("Cyprus Border Force 4 T3.stm")',
		},
		['active'] = false,
	},
	['North Cyprus-Turkish Force 3 move 2'] = {
		['condition'] = 'Return.CampFlag(806) and (Return.Mission() >= Return.CampFlag(806) + 3) and (Return.TargetAlive("North Cyprus-Turkish Force 3") > 40)',
		['once'] = true,
		['action'] = {
			[2] = 'Action.AddImage("NCTF3-2.png")',
			[3] = 'Action.TemplateActive("Turkish Naval Convoy 2 T1.stm")',
			[1] = 'Action.TemplateActive("North Cyprus-Turkish Force 3 T2.stm")',
			[4] = 'Action.TargetActive("Turkish Naval Convoy 2", false)',
			[5] = 'Action.Text("Heavy Turkish column 3 is still moving on the main road south of Pinarbashi Airbase")',
		},
		['active'] = false,
	},
	['North Cyprus-Turkish Force 1 retreat 3'] = {
		['condition'] = '(Return.Mission() > 23) and (Return.CampFlag(831) == nil) and ((Return.CampFlag(824) == nil) or (Return.CampFlag(823) == nil))',
		['once'] = true,
		['action'] = {
			[1] = 'Action.SetCampFlag(851, 0)',
		},
		['active'] = true,
	},
	['North Cyprus-Turkish Force 3 move 3'] = {
		['condition'] = 'Return.CampFlag(806) and (Return.Mission() >= Return.CampFlag(806) + 5) and (Return.TargetAlive("North Cyprus-Turkish Force 3") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("North Cyprus-Turkish Force 3 T3.stm")',
			[2] = 'Action.AddImage("NCTF3-3.png")',
			[3] = 'Action.Text("Heavy Turkish column 3 is still moving on the main road 15 nm west of Nicosia")',
		},
		['active'] = false,
	},
	['Reinforce 356th Tactical Transport Squadron'] = {
		['condition'] = 'true',
		['action'] = 'Action.AirUnitReinforce("356th Tactical Transport Squadron")',
		['active'] = true,
	},
	['Greek Expeditionary Force 3 move 2'] = {
		['condition'] = 'Return.CampFlag(810) and (Return.Mission() >= Return.CampFlag(810) + 2) and (Return.TargetAlive("Greek Expeditionary Force 3") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("Greek Expeditionary Force 3 T2.stm")',
			[2] = 'Action.AddImage("GEF3-2.png")',
			[3] = 'Action.Text("Greek Expeditionary column 3 is still moving ")',
		},
		['active'] = false,
	},
	['Turkish Artillery out'] = {
		['condition'] = '(Return.Mission() > 23) and (Return.TargetAlive("Turkish Artillery Force 1") < 20)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.SetCampFlag(856, 0)',
		},
		['active'] = true,
	},
	['Greek Expeditionary Force 2 stop'] = {
		['condition'] = 'Return.TargetAlive("Greek Expeditionary Force 2") < 40',
		['once'] = true,
		['action'] = {
			[1] = 'Action.Text("Greek Expeditionary column 2 took heavy losses and is stopped")',
		},
		['active'] = true,
	},
	['Campaign 40 percents destructions'] = {
		['condition'] = 'GroundTarget["blue"].percent < 60',
		['once'] = true,
		['action'] = {
			[1] = 'Action.Text("Enemy targets have sustained great damages. Strike missions are really efficient and we will win this war soon")',
			[2] = 'Action.Text("Les cibles ennemies ont subi de gros dégâts. Les attaques au sol sont vraiment efficaces et nous gagnerons bientôt cette guerre")',
		},
		['active'] = true,
	},
	['Greek Expeditionary Force 2 move 4'] = {
		['condition'] = 'Return.CampFlag(809) and (Return.Mission() >= Return.CampFlag(809) + 7) and (Return.TargetAlive("Greek Expeditionary Force 2") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("Greek Expeditionary Force 2 T4.stm")',
			[2] = 'Action.Text("Greek Expeditionary column 2 stopped 5nm west of Larnaca City ")',
			[4] = 'Action.SetCampFlag(842, Return.Mission())',
			[3] = 'Action.AddImage("GEF2-4.png")',
		},
		['active'] = false,
	},
	['Greek Air Force interception activation'] = {
		['condition'] = 'Return.CampFlag(801) and (Return.Mission() >= Return.CampFlag(801) + 1)',
		['once'] = true,
		['action'] = {
			[6] = 'Action.TargetActive("Airlift Paphos Airbase 3", true)',
			[2] = 'Action.TargetActive("Paphos Airbase Alert", true)',
			[8] = 'Action.Text("Greek Air Force sent EC 331 with its Mirage 2000C to protect Cyprus and intensify airlift missions")',
			[3] = 'Action.TargetActive("Paphos Airbase Alert 2", true)',
			[1] = 'Action.AirUnitActive("EC 331", true)',
			[4] = 'Action.TargetActive("Paphos Airbase Alert 3", true)',
			[5] = 'Action.TargetActive("Airlift Paphos Airbase 2", true)',
			[7] = 'Action.TargetActive("CAP-1-Greek", true)',
		},
		['active'] = true,
	},
	['Cyprus Defense Force 3 move 3'] = {
		['condition'] = 'Return.CampFlag(801) and (Return.Mission() >= Return.CampFlag(801) + 7) and (Return.TargetAlive("Cyprus Defense Force 3") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("Cyprus Defense Force 3 T3.stm")',
			[2] = 'Action.AddImage("CDF3-3.png")',
			[4] = 'Action.SetCampFlag(823, Return.Mission())',
			[3] = 'Action.Text("Cyprus Defense Force 3 reached defensives positions")',
		},
		['active'] = true,
	},
	['Cyprus Defense Forces activation'] = {
		['condition'] = 'Return.CampFlag(801) and (Return.Mission() >= Return.CampFlag(801) + 2)',
		['once'] = true,
		['action'] = {
			[7] = 'Action.TemplateActive("Cyprus Defense Force 4 T1.stm")',
			[1] = 'Action.TemplateActive("Cyprus Defense Force 1 T1.stm")',
			[2] = 'Action.TargetActive("Cyprus Defense Force 1", true)',
			[4] = 'Action.TargetActive("Cyprus Defense Force 2", true)',
			[8] = 'Action.TargetActive("Cyprus Defense Force 4", true)',
			[9] = 'Action.TemplateActive("Cyprus Defense Force 5 T1.stm")',
			[5] = 'Action.TemplateActive("Cyprus Defense Force 3 T1.stm")',
			[10] = 'Action.TargetActive("Cyprus Defense Force 5", true)',
			[3] = 'Action.TemplateActive("Cyprus Defense Force 2 T1.stm")',
			[6] = 'Action.TargetActive("Cyprus Defense Force 3", true)',
			[12] = 'Action.Text("After Turkish direct involment our Defense Forces have been mobilized and are moving to the frontline")',
			[11] = 'Action.AddImage("CDF.png")',
		},
		['active'] = true,
	},
	['North Cyprus-Turkish Force 2 move 2'] = {
		['condition'] = 'Return.CampFlag(805) and (Return.Mission() >= Return.CampFlag(805) + 3) and (Return.TargetAlive("North Cyprus-Turkish Force 2") > 40)',
		['once'] = true,
		['action'] = {
			[2] = 'Action.AddImage("NCTF2-2.png")',
			[3] = 'Action.TemplateActive("Turkish Naval Convoy 1 T1.stm")',
			[1] = 'Action.TemplateActive("North Cyprus-Turkish Force 2 T2.stm")',
			[4] = 'Action.TargetActive("Turkish Naval Convoy 1", false)',
			[5] = 'Action.Text("Heavy Turkish column 2 is still moving just south of Famagusta")',
		},
		['active'] = false,
	},
	['Cyprus Defense Force 5 move 3'] = {
		['condition'] = 'Return.CampFlag(801) and (Return.Mission() >= Return.CampFlag(801) + 7) and (Return.TargetAlive("Cyprus Defense Force 5") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("Cyprus Defense Force 5 T3.stm")',
			[2] = 'Action.AddImage("CDF5-3.png")',
			[4] = 'Action.SetCampFlag(825, Return.Mission())',
			[3] = 'Action.Text("Cyprus Defense Force 5 reached defensives positions")',
		},
		['active'] = true,
	},
	['North Cyprus-Turkish Force 1 initial positions'] = {
		['condition'] = 'Return.CampFlag(801) and (Return.Mission() >= Return.CampFlag(801) + 1)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("North Cyprus-Turkish Force 1 T1.stm")',
			[2] = 'Action.TargetActive("North Cyprus-Turkish Force 1", true)',
			[4] = 'Action.AddImage("NCTF1-1.png")',
			[3] = 'Action.Text("An heavy Turkish column has been detected on the main road between Famagusta and Nicosia just South of Gecitkale airbase. It seems that turkish army will get fully involved in this war. Be careful Turkish forces learned quickly from their allies defeat and heavy Air defenses are part of their columns now.")',
		},
		['active'] = true,
	},
	['North Cyprus-Turkish Force 1 move 3 after Greece involvement'] = {
		['condition'] = 'Return.CampFlag(802) and (Return.Mission() >= Return.CampFlag(802) + 6) and (Return.TargetAlive("North Cyprus-Turkish Force 1") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("North Cyprus-Turkish Force 1 T3.stm")',
			[2] = 'Action.Text("Heavy Turkish column 1 is still moving few miles west of Nicosia")',
			[3] = 'Action.AddImage("NCTF1-3.png")',
		},
		['active'] = false,
	},
	['North Cyprus-Turkish Force 1 move 4 after Greece involvement'] = {
		['condition'] = 'Return.CampFlag(802) and (Return.Mission() >= Return.CampFlag(802) + 8) and (Return.TargetAlive("North Cyprus-Turkish Force 1") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("North Cyprus-Turkish Force 1 T4.stm")',
			[2] = 'Action.Text("Heavy Turkish column 1 stopped 10 nm west of Nicosia ")',
			[4] = 'Action.SetCampFlag(831, Return.Mission())',
			[3] = 'Action.AddImage("NCTF1-4.png")',
		},
		['active'] = false,
	},
	['Helicopters Gazelle Squadron Move'] = {
		['condition'] = 'Return.CampFlag(801) and (Return.Mission() >= Return.CampFlag(801) + 2)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.AirUnitBase("450 M-E/P-2", "Paphos Airbase")',
			[2] = 'Action.Text("After our initial victory over North Cyprus invaders, Turkish sent massive reinforcement to help their allies and Larnaca airbase is under attack. We must retreat our Gazelle frontline helicopters unit to Paphos airbase")',
		},
		['active'] = true,
	},
	['Larnaca Turkish Assault Force retreat 2'] = {
		['condition'] = '(Return.Mission() > 23) and (Return.CampFlag(804) == nil) and Return.CampFlag(843)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.SetCampFlag(855, 0)',
		},
		['active'] = true,
	},
	['Cyprus Defense Force 1 move 2 after North Cyprus attack'] = {
		['condition'] = 'Return.CampFlag(802) and (Return.Mission() >= Return.CampFlag(802) + 3) and (Return.TargetAlive("Cyprus Defense Force 1") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("Cyprus Defense Force 1 T2.stm")',
			[2] = 'Action.AddImage("CDF1-2.png")',
			[3] = 'Action.Text("Cyprus Defense Force 1 is still moving")',
		},
		['active'] = false,
	},
	['Cyprus Defense Force 2 move 2 after North Cyprus attack'] = {
		['condition'] = 'Return.CampFlag(802) and (Return.Mission() >= Return.CampFlag(802) + 3) and (Return.TargetAlive("Cyprus Defense Force 2") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("Cyprus Defense Force 2 T2.stm")',
			[2] = 'Action.AddImage("CDF2-2.png")',
			[3] = 'Action.Text("Cyprus Defense Force 2 is still moving")',
		},
		['active'] = false,
	},
	['Cyprus Defense Force 5 move 2 after North Cyprus attack'] = {
		['condition'] = 'Return.CampFlag(802) and (Return.Mission() >= Return.CampFlag(802) + 3) and (Return.TargetAlive("Cyprus Defense Force 5") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("Cyprus Defense Force 5 T2.stm")',
			[2] = 'Action.AddImage("CDF5-2.png")',
			[3] = 'Action.Text("Cyprus Defense Force 5 is still moving")',
		},
		['active'] = false,
	},
	['Nord Cyprus Stinger Reinforcement activation after Greece involvement'] = {
		['condition'] = 'Return.CampFlag(802) and (Return.Mission() >= Return.CampFlag(802) + 2)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("Nord Cyprus Stinger Reinforcement.stm")',
			[2] = 'Action.Text("Intels advice all our forces that large number of Stinger manpads were spread all over the Pro-Turkish territory so fly very carefully to avoid cities where they should try to ambush you")',
		},
		['active'] = false,
	},
	['Cyprus Defense Force 5 move 3 after North Cyprus attack'] = {
		['condition'] = 'Return.CampFlag(802) and (Return.Mission() >= Return.CampFlag(802) + 5) and (Return.TargetAlive("Cyprus Defense Force 5") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("Cyprus Defense Force 5 T3.stm")',
			[2] = 'Action.AddImage("CDF5-3.png")',
			[4] = 'Action.SetCampFlag(825, Return.Mission())',
			[3] = 'Action.Text("Cyprus Defense Force 5 reached defensives positions")',
		},
		['active'] = false,
	},
	['North Cyprus-Turkish Force 4 move 3'] = {
		['condition'] = 'Return.CampFlag(807) and (Return.Mission() >= Return.CampFlag(807) + 5) and (Return.TargetAlive("North Cyprus-Turkish Force 4") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("North Cyprus-Turkish Force 4 T3.stm")',
			[2] = 'Action.Text("Heavy Turkish column 4 stopped moving along a river 6 nm south east of Lakatamia airbase")',
			[4] = 'Action.SetCampFlag(834, Return.Mission())',
			[3] = 'Action.AddImage("NCTF4-3.png")',
		},
		['active'] = true,
	},
	['Gecitkale Airbase Alert activation'] = {
		['condition'] = '(Return.CampFlag(801) and (Return.Mission() >= Return.CampFlag(801) + 8)) and (Return.TargetAlive("EWR-Jaguar") > 20)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TargetActive("Gecitkale Airbase Alert", true)',
		},
		['active'] = true,
	},
	['North Cyprus Force 4 move 2'] = {
		['condition'] = 'Return.Mission() > 1 and (Return.Mission() < 3 and Return.TargetAlive("North Cyprus Force 4") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("North Cyprus Force 4 T2.stm")',
			[2] = 'Action.Text("North Cyprus columns are still moving in the south east of Nicosia")',
			[3] = 'Action.TemplateActive("Cyprus Border Force 5 T2.stm")',
		},
		['active'] = false,
	},
	['Campaign 50 percents destructions'] = {
		['condition'] = 'GroundTarget["blue"].percent < 50',
		['once'] = true,
		['action'] = {
			[1] = 'Action.Text("More than half of our targets are neutralized. Intelligence think that the enemy will ask for a cease fire soon")',
			[2] = 'Action.Text("Plus de la moitié de nos cibles sont neutralisées. Les renseignements pensent que l ennemi demandera bientôt un cessez-le-feu")',
		},
		['active'] = true,
	},
	['North Cyprus Force 4 initial positions'] = {
		['condition'] = 'Return.Mission() >0',
		['once'] = true,
		['action'] = {
			[2] = 'Action.TargetActive("North Cyprus Force 4", true)',
			[3] = 'Action.Text("North Cyprus columns crossed the No man s land and are coming from the far South east of Nicosia")',
			[1] = 'Action.TemplateActive("North Cyprus Force 4 T1.stm")',
			[4] = 'Action.TemplateActive("Cyprus Border Force 5 T1.stm")',
			[5] = 'Action.TargetActive("Cyprus Border Force 5", true)',
		},
		['active'] = false,
	},
	['North Cyprus-Turkish Force 1 Victory 2'] = {
		['condition'] = '(Return.Mission() > 23) and Return.CampFlag(831) and ((Return.CampFlag(824) == nil) or (Return.CampFlag(823) == nil))',
		['once'] = true,
		['action'] = {
			[1] = 'Action.SetCampFlag(851, 1)',
		},
		['active'] = true,
	},
	['Greek Naval Convoy mouvement'] = {
		['condition'] = 'Return.CampFlag(801) and (Return.Mission() >= Return.CampFlag(801) + 5) and (Return.TargetAlive("Greek Naval Convoy") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("Greek Naval Convoy T2.stm")',
			[2] = 'Action.Text("Greek naval forces are shipping reinforcement to Cyprus.")',
		},
		['active'] = true,
	},
	['Greek Naval Convoy activation after NCF victory'] = {
		['condition'] = 'Return.CampFlag(802)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("Greek Naval Convoy T1.stm")',
			[2] = 'Action.TargetActive("Greek Naval Convoy", true)',
			[3] = 'Action.Text("Greek naval forces are shipping reinforcement to Cyprus.")',
		},
		['active'] = false,
	},
	['North Cyprus Force 2 stop'] = {
		['condition'] = 'Return.TargetAlive("North Cyprus Force 2") < 40',
		['once'] = true,
		['action'] = {
			[1] = 'Action.Text("North Cyprus columns to the close south west of Nicosia took heavy losses and are stopped")',
		},
		['active'] = true,
	},
	['Greek Naval Convoy 2 activation'] = {
		['condition'] = 'Return.CampFlag(801) and (Return.Mission() >= Return.CampFlag(801) + 4)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("Greek Naval Convoy 2 T1.stm")',
			[2] = 'Action.TargetActive("Greek Naval Convoy 2", true)',
			[3] = 'Action.Text("Greek naval forces are shipping reinforcement to Cyprus.")',
		},
		['active'] = true,
	},
	['Greek Naval Convoy 2 activation after NCF victory'] = {
		['condition'] = 'Return.CampFlag(802) and (Return.Mission() >= Return.CampFlag(802) + 1)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("Greek Naval Convoy 2 T1.stm")',
			[2] = 'Action.TargetActive("Greek Naval Convoy 2", true)',
			[3] = 'Action.Text("Greek naval forces are shipping reinforcement to Cyprus.")',
		},
		['active'] = false,
	},
	['Larnaca Turkish Assault Force retreat'] = {
		['condition'] = '(Return.Mission() > 23) and Return.CampFlag(804) and Return.CampFlag(843) and (Return.TargetAlive("Greek Expeditionary Force 3") > Return.TargetAlive("Larnaca Turkish Assault Force 1"))',
		['once'] = true,
		['action'] = {
			[2] = 'Action.SideBase("blue", "Larnaca Airbase")',
			[3] = 'Action.TemplateActive("Larnaca Cyprus defenses T1.stm")',
			[1] = 'Action.TemplateActive("Larnaca Turkish Assault Force 1 T1.stm")',
			[4] = 'Action.TemplateActive("Larnaca Turkish AA T2.stm")',
			[5] = 'Action.SetCampFlag(855, 0)',
		},
		['active'] = true,
	},
	['Greek EWR activation'] = {
		['condition'] = 'Return.CampFlag(809) and (Return.Mission() >= Return.CampFlag(809) + 1)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("EWR-Moonbeam.stm")',
			[2] = 'Action.TargetActive("EWR-Moonbeam", true)',
			[4] = 'Action.Text("A new Greek EWR is active east of Limassol")',
			[3] = 'Action.AddImage("EWR-Moonbeam.png")',
		},
		['active'] = false,
	},
	['Cyprus Defense Force 3 move 2 after North Cyprus attack'] = {
		['condition'] = 'Return.CampFlag(802) and (Return.Mission() >= Return.CampFlag(802) + 3) and (Return.TargetAlive("Cyprus Defense Force 3") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("Cyprus Defense Force 3 T2.stm")',
			[2] = 'Action.AddImage("CDF3-2.png")',
			[3] = 'Action.Text("Cyprus Defense Force 3 is still moving")',
		},
		['active'] = false,
	},
	['Cyprus Defense Force 4 move 2 after North Cyprus attack'] = {
		['condition'] = 'Return.CampFlag(802) and (Return.Mission() >= Return.CampFlag(802) + 3) and (Return.TargetAlive("Cyprus Defense Force 4") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("Cyprus Defense Force 4 T2.stm")',
			[2] = 'Action.AddImage("CDF4-2.png")',
			[3] = 'Action.Text("Cyprus Defense Force 4 is still moving")',
		},
		['active'] = false,
	},
	['Greek Expeditionary Force 2 move 2'] = {
		['condition'] = 'Return.CampFlag(809) and (Return.Mission() >= Return.CampFlag(809) + 3) and (Return.TargetAlive("Greek Expeditionary Force 2") > 40)',
		['once'] = true,
		['action'] = {
			[2] = 'Action.AddImage("GEF2-2.png")',
			[3] = 'Action.TemplateActive("Greek Naval Convoy 2 T1.stm")',
			[1] = 'Action.TemplateActive("Greek Expeditionary Force 2 T2.stm")',
			[4] = 'Action.TargetActive("Greek Naval Convoy 2", false)',
			[5] = 'Action.Text("Greek Expeditionary column 2 is still moving ")',
		},
		['active'] = false,
	},
	['North Cyprus-Turkish Force 1 move 2 after Greece involvement'] = {
		['condition'] = 'Return.CampFlag(802) and (Return.Mission() >= Return.CampFlag(802) + 4) and (Return.TargetAlive("North Cyprus-Turkish Force 1") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.AirUnitBase("134.Filo", "Gecitkale Airbase")',
			[2] = 'Action.TemplateActive("North Cyprus-Turkish Force 1 T2.stm")',
			[4] = 'Action.AddImage("NCTF1-2.png")',
			[3] = 'Action.Text("Heavy Turkish column 1 is still moving in the suburbs north east of Nicosia")',
		},
		['active'] = false,
	},
	['North Cyprus Force 1 initial positions'] = {
		['condition'] = 'Return.Mission() > 0',
		['once'] = true,
		['action'] = {
			[6] = 'Action.AddImage("Newspaper_FirstNight_blue.jpg", "blue")',
			[2] = 'Action.TargetActive("North Cyprus Force 1", true)',
			[3] = 'Action.Text("North Cyprus columns crossed the No man s land and are coming from the far South west of Nicosia")',
			[1] = 'Action.TemplateActive("North Cyprus Force 1 T1.stm")',
			[4] = 'Action.TemplateActive("Cyprus Border Force 2 T1.stm")',
			[5] = 'Action.TargetActive("Cyprus Border Force 2", true)',
		},
		['active'] = false,
	},
	['Greek Expeditionary Force 2 move 3'] = {
		['condition'] = 'Return.CampFlag(809) and (Return.Mission() >= Return.CampFlag(809) + 5) and (Return.TargetAlive("Greek Expeditionary Force 2") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("Greek Expeditionary Force 2 T3.stm")',
			[2] = 'Action.AddImage("GEF2-3.png")',
			[3] = 'Action.Text("Greek Expeditionary column 2 is still moving ")',
		},
		['active'] = false,
	},
	['Helicopters Hind Squadron Move'] = {
		['condition'] = 'Return.CampFlag(801) and (Return.Mission() >= Return.CampFlag(801) + 1)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.AirUnitBase("450 M-E/P-1", "Paphos Airbase")',
			[2] = 'Action.Text("After our initial victory over North Cyprus invaders, Turkish sent massive reinforcement to help their allies. We must retreat our Hind frontline helicopters unit to Paphos airbase")',
			[3] = 'Action.SetCampFlag(803, Return.Mission())',
		},
		['active'] = true,
	},
	['North Cyprus-Turkish Force 3 stop'] = {
		['condition'] = 'Return.TargetAlive("North Cyprus-Turkish Force 3") < 40',
		['once'] = true,
		['action'] = {
			[1] = 'Action.Text("Heavy Turkish column 3 took heavy losses and is stopped")',
		},
		['active'] = true,
	},
	['Campaign 20 percents destructions'] = {
		['condition'] = 'GroundTarget["blue"].percent < 80',
		['once'] = true,
		['action'] = {
			[1] = 'Action.Text("Enemy targets have sustained fair damages. Keep up the good work")',
			[2] = 'Action.Text("Les cibles ennemies ont subi des dommages moyens. Continuez votre bon travail")',
		},
		['active'] = true,
	},
	['Greek Expeditionary Force 3 move 3'] = {
		['condition'] = 'Return.CampFlag(810) and (Return.Mission() >= Return.CampFlag(810) + 4) and (Return.TargetAlive("Greek Expeditionary Force 3") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("Greek Expeditionary Force 3 T3.stm")',
			[2] = 'Action.AddImage("GEF3-3.png")',
			[3] = 'Action.Text("Greek Expeditionary column 3 is still moving ")',
		},
		['active'] = false,
	},
	['North Cyprus-Turkish EWR activation'] = {
		['condition'] = 'Return.CampFlag(805) and (Return.Mission() >= Return.CampFlag(805) + 1)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("EWR-Jaguar T1.stm")',
			[2] = 'Action.TargetActive("EWR-Jaguar", true)',
			[4] = 'Action.Text("A new Turkish EWR seems to be active near Famagusta")',
			[3] = 'Action.AddImage("EWR-Jaguar.png")',
		},
		['active'] = false,
	},
	['North Cyprus-Turkish Force 2 retreat'] = {
		['condition'] = '(Return.Mission() > 23) and Return.CampFlag(832) and (Return.CampFlag(821) or Return.CampFlag(842)) and (Return.TargetAlive("Greek Expeditionary Force 2") > Return.TargetAlive("North Cyprus-Turkish Force 2") or Return.TargetAlive("Cyprus Defense Force 1") > Return.TargetAlive("North Cyprus-Turkish Force 2"))',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("North Cyprus-Turkish Force 4 T2.stm")',
			[2] = 'Action.SetCampFlag(852, 0)',
		},
		['active'] = false,
	},
	['North Cyprus Force 1 move 3'] = {
		['condition'] = 'Return.Mission() > 2 and (Return.TargetAlive("North Cyprus Force 1") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("North Cyprus Force 1 T3.stm")',
			[2] = 'Action.Text("North Cyprus columns are still moving in the south west suburbs of Nicosia")',
			[4] = 'Action.TemplateActive("Cyprus Border Force 2 T3.stm")',
			[3] = 'Action.TemplateActive("Cyprus Border Force 1 T3.stm")',
		},
		['active'] = false,
	},
	['North Cyprus-Turkish Force 1 move 3'] = {
		['condition'] = 'Return.CampFlag(801) and (Return.Mission() >= Return.CampFlag(801) + 5) and (Return.TargetAlive("North Cyprus-Turkish Force 1") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("North Cyprus-Turkish Force 1 T3.stm")',
			[2] = 'Action.Text("Heavy Turkish column 1 is still moving")',
			[3] = 'Action.AddImage("NCTF1-3.png")',
		},
		['active'] = true,
	},
	['North Cyprus-Turkish Force 1 move 2'] = {
		['condition'] = 'Return.CampFlag(801) and (Return.Mission() >= Return.CampFlag(801) + 3) and (Return.TargetAlive("North Cyprus-Turkish Force 1") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("North Cyprus-Turkish Force 1 T2.stm")',
			[2] = 'Action.Text("Heavy Turkish column 1 is still moving")',
			[3] = 'Action.AddImage("NCTF1-2.png")',
		},
		['active'] = true,
	},
	['North Cyprus-Turkish Force 4 move 2'] = {
		['condition'] = 'Return.CampFlag(807) and (Return.Mission() >= Return.CampFlag(807) + 3) and (Return.TargetAlive("North Cyprus-Turkish Force 4") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("North Cyprus-Turkish Force 4 T2.stm")',
			[2] = 'Action.AddImage("NCTF4-2.png")',
			[3] = 'Action.Text("Heavy Turkish column 4 is still moving few nm south west of Ercan Airbase")',
		},
		['active'] = true,
	},
	['Greek Expeditionary Force 4 move 3'] = {
		['condition'] = 'Return.CampFlag(811) and (Return.Mission() >= Return.CampFlag(811) + 4) and (Return.TargetAlive("Greek Expeditionary Force 4") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("Greek Expeditionary Force 4 T3.stm")',
			[2] = 'Action.AddImage("GEF4-3.png")',
			[3] = 'Action.Text("Greek Expeditionary column 4 is still moving ")',
		},
		['active'] = false,
	},
	['Nord Cyprus Stinger Reinforcement activation'] = {
		['condition'] = 'Return.CampFlag(801) and (Return.Mission() >= Return.CampFlag(801) + 1)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("Nord Cyprus Stinger Reinforcement.stm")',
			[2] = 'Action.Text("Intels advice all our forces that large number of Stinger manpads were spread all over the Pro-Turkish territory so fly very carefully to avoid cities where they should try to ambush you")',
		},
		['active'] = true,
	},
	['Turkish Naval Convoi 2 activation'] = {
		['condition'] = 'Return.CampFlag(801) and (Return.Mission() >= Return.CampFlag(801) + 3)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("Turkish Naval Convoy 2 T1.stm")',
			[2] = 'Action.TargetActive("Turkish Naval Convoy 2", true)',
			[3] = 'Action.Text("Turkish naval forces are shipping reinforcement to Cyprus. One convoy just lived Turkish coasts to rejoin south east port in Cyprus")',
		},
		['active'] = true,
	},
	['North Cyprus-Turkish Force 3 Victory'] = {
		['condition'] = '(Return.Mission() > 23) and Return.CampFlag(833) and (Return.CampFlag(825) or Return.CampFlag(841)) and (Return.TargetAlive("Greek Expeditionary Force 1") < Return.TargetAlive("North Cyprus-Turkish Force 3") or Return.TargetAlive("Cyprus Defense Force 5") < Return.TargetAlive("North Cyprus-Turkish Force 3"))',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("Cyprus Defense Force 5 T2.stm")',
			[2] = 'Action.TemplateActive("Greek Expeditionary Force 1 T2.stm")',
			[3] = 'Action.SetCampFlag(853, 1)',
		},
		['active'] = false,
	},
	['Greek Expeditionary Force 4 stop'] = {
		['condition'] = 'Return.TargetAlive("Greek Expeditionary Force 4") < 40',
		['once'] = true,
		['action'] = {
			[1] = 'Action.Text("Greek Expeditionary column 4 took heavy losses and is stopped")',
		},
		['active'] = true,
	},
	['North Cyprus-Turkish Force 1 retreat 2'] = {
		['condition'] = '(Return.Mission() > 23) and (Return.CampFlag(831) == nil) and (Return.CampFlag(824) or Return.CampFlag(823))',
		['once'] = true,
		['action'] = {
			[1] = 'Action.SetCampFlag(851, 0)',
		},
		['active'] = false,
	},
	['North Cyprus-Turkish Force 3 retreat 4'] = {
		['condition'] = '(Return.Mission() > 23) and Return.CampFlag(833) and (Return.CampFlag(825) or Return.CampFlag(841)) and (Return.TargetAlive("Greek Expeditionary Force 1") == Return.TargetAlive("North Cyprus-Turkish Force 3") or Return.TargetAlive("Cyprus Defense Force 5") == Return.TargetAlive("North Cyprus-Turkish Force 3"))',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("North Cyprus-Turkish Force 3 T2.stm")',
			[2] = 'Action.SetCampFlag(853, 0)',
		},
		['active'] = false,
	},
	['Turkish Naval Convoi 2 mouvement after Greece involvement'] = {
		['condition'] = 'Return.CampFlag(802) and (Return.Mission() >= Return.CampFlag(802) + 5) and (Return.TargetAlive("Turkish Naval Convoy 2") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("Turkish Naval Convoy 2 T2.stm")',
			[2] = 'Action.Text("Turkish naval forces are shipping reinforcement to Cyprus. One convoy is near Kyrenia port in North Cyprus")',
		},
		['active'] = false,
	},
	['North Cyprus-Turkish Force 4 retreat 2'] = {
		['condition'] = '(Return.Mission() > 23) and (Return.CampFlag(834) == nil) and (Return.CampFlag(822) or Return.CampFlag(842))',
		['once'] = true,
		['action'] = {
			[1] = 'Action.SetCampFlag(854, 0)',
		},
		['active'] = false,
	},
	['North Cyprus-Turkish Force 4 retreat 3'] = {
		['condition'] = '(Return.Mission() > 23) and (Return.CampFlag(834) == nil) and ((Return.CampFlag(822) == nil) or (Return.CampFlag(842) == nil))',
		['once'] = true,
		['action'] = {
			[1] = 'Action.SetCampFlag(854, 0)',
		},
		['active'] = true,
	},
	['Campaign Briefing'] = {
		['condition'] = 'true',
		['once'] = true,
		['action'] = {
			[1] = 'Action.Text("Since 1974 Cyprus is divided between Cyprus pro-Turkish population to the north and Cyprus pro-Greek population to the south. June 2004,Pro-Turkish forces are trying to circle Nicosia with surprised light columms attack. Their hope is to capture the city and win lot more territorial possessions. Your unit will try to resist and destroy those weak enemy columns in the suburbs of Nicosia. You are equiped with Mi-35P Hind and SA-342 Gazelle. Intel think that Turkey is ready to support massively this attack and our hope is that Greek army will help us if that occured.")',
			[2] = 'Action.Text("The Turkish Air Force is flying a mix of F-16C F-4E and F-5E-3 fighters. UH-1H Huey and AH-1 Cobra will support their ground forces directly.SAM systems like Rapier, Hawk and more mobile Avenger and Stinger Manpad will certainly be deployed if needed by Turkey")',
			[3] = 'Action.AddImage("Newspaper_FirstNight_blue.jpg", "blue")',
		},
		['active'] = false,
	},
	['Turkish involvement after Greece involvement'] = {
		['condition'] = 'Return.CampFlag(802) and (Return.Mission() >= Return.CampFlag(802) + 2)',
		['once'] = true,
		['action'] = {
			[6] = 'Action.TargetActive("Airlift Ercan Airbase 2", true)',
			[2] = 'Action.AirUnitActive("134.Filo", true)',
			[8] = 'Action.Text("After Greece involvement it seems that turkish forces will try to rescue their allies sending heavy reinforcements")',
			[3] = 'Action.AirUnitActive("2nd KHA", true)',
			[1] = 'Action.AirUnitActive("111.Filo", true)',
			[4] = 'Action.AirUnitActive("2nd-2 KHA", true)',
			[5] = 'Action.TargetActive("CAP-1-Turkish", true)',
			[7] = 'Action.TargetActive("Airlift Ercan Airbase 3", true)',
		},
		['active'] = false,
	},
	['Greek Naval Convoy 2 mouvement after NCF victory'] = {
		['condition'] = 'Return.CampFlag(802) and (Return.Mission() >= Return.CampFlag(802) + 3) and (Return.TargetAlive("Greek Naval Convoy 2") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("Greek Naval Convoy 2 T2.stm")',
			[2] = 'Action.Text("Greek naval forces are shipping reinforcement to Cyprus.")',
		},
		['active'] = false,
	},
	['North Cyprus-Turkish Force 4 Victory'] = {
		['condition'] = '(Return.Mission() > 23) and Return.CampFlag(834) and (Return.CampFlag(822) or Return.CampFlag(842)) and (Return.TargetAlive("Greek Expeditionary Force 2") < Return.TargetAlive("North Cyprus-Turkish Force 4") or Return.TargetAlive("Cyprus Defense Force 2") < Return.TargetAlive("North Cyprus-Turkish Force 4"))',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("Cyprus Defense Force 2 T2.stm")',
			[2] = 'Action.TemplateActive("Greek Expeditionary Force 2 T2.stm")',
			[3] = 'Action.SetCampFlag(854, 1)',
		},
		['active'] = true,
	},
	['Cyprus Defense Force 4 move 3'] = {
		['condition'] = 'Return.CampFlag(801) and (Return.Mission() >= Return.CampFlag(801) + 7) and (Return.TargetAlive("Cyprus Defense Force 4") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("Cyprus Defense Force 4 T3.stm")',
			[2] = 'Action.AddImage("CDF4-3.png")',
			[4] = 'Action.SetCampFlag(824, Return.Mission())',
			[3] = 'Action.Text("Cyprus Defense Force 4 reached defensives positions")',
		},
		['active'] = true,
	},
	['North Cyprus-Turkish Force 3 move 4'] = {
		['condition'] = 'Return.CampFlag(806) and (Return.Mission() >= Return.CampFlag(806) + 7) and (Return.TargetAlive("North Cyprus-Turkish Force 3") > 40)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("North Cyprus-Turkish Force 3 T4.stm")',
			[2] = 'Action.Text("Heavy Turkish column 3 stopped moving in Morphon City 20nm west of Nicosia")',
			[4] = 'Action.SetCampFlag(833, Return.Mission())',
			[3] = 'Action.AddImage("NCTF3-4.png")',
		},
		['active'] = false,
	},
	['Reinforce 450 M-E/P-2'] = {
		['condition'] = 'true',
		['action'] = 'Action.AirUnitReinforce("450 M-E/P-2")',
		['active'] = true,
	},
	['North Cyprus-Turkish Force 2 retreat 2'] = {
		['condition'] = '(Return.Mission() > 23) and (Return.CampFlag(832) == nil) and (Return.CampFlag(821) or Return.CampFlag(842))',
		['once'] = true,
		['action'] = {
			[1] = 'Action.SetCampFlag(852, 0)',
		},
		['active'] = true,
	},
	['CAP 2 only after EWR Destroyed'] = {
		['condition'] = 'Return.TargetAlive("EWR-Eyeball") == 0',
		['once'] = true,
		['action'] = {
			[2] = 'Action.TargetActive("Paphos Airbase Alert", false)',
			[3] = 'Action.TargetActive("Paphos Airbase Alert 2", false)',
			[1] = 'Action.TargetActive("CAP-2-Greek", true)',
			[4] = 'Action.TargetActive("Paphos Airbase Alert 3", false)',
			[5] = 'Action.Text("With the recent destruction of our Early Warning Radar site we are not able to maintain Interceptions alerts on Paphos Airbase anymore . We will depend on Combat Air Patrols to compensate, though without the support of ground controllers these will be of limited effectiveness.")',
		},
		['active'] = true,
	},
	['Greek Naval Convoy in port'] = {
		['condition'] = 'Return.CampFlag(801) and (Return.Mission() >= Return.CampFlag(801) + 7) and (Return.TargetAlive("Greek Naval Convoy") > 40)',
		['once'] = true,
		['action'] = {
			[6] = 'Action.Text("Greek naval forces are shipping reinforcement to Cyprus. One convoy is unloading troops and a Hawk battery in Paphos harbor")',
			[2] = 'Action.TemplateActive("Greek Expeditionary Force 1 T1.stm")',
			[8] = 'Action.SetCampFlag(808, Return.Mission())',
			[3] = 'Action.TargetActive("Greek Expeditionary Force 1", true)',
			[1] = 'Action.TemplateActive("Greek Naval Convoy T3.stm")',
			[4] = 'Action.TemplateActive("Greek Hawk Battery 1 T1.stm")',
			[5] = 'Action.TargetActive("Greek Hawk Battery 1", true)',
			[7] = 'Action.AddImage("GEF1-1.png")',
		},
		['active'] = true,
	},
	['Reinforce 347th Squadron'] = {
		['condition'] = 'true',
		['action'] = 'Action.AirUnitReinforce("347th Squadron")',
		['active'] = true,
	},
	['Reinforce 222.Filo'] = {
		['condition'] = 'true',
		['action'] = 'Action.AirUnitReinforce("222.Filo")',
		['active'] = true,
	},
	['Larnaca Airbase Attack'] = {
		['condition'] = 'Return.CampFlag(801) and (Return.Mission() >= Return.CampFlag(801) + 2)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("Larnaca Turkish Assault Force 1 T1.stm")',
			[2] = 'Action.TargetActive("Larnaca Turkish Assault Force 1", true)',
			[4] = 'Action.AddImage("LarnacaAttack.png")',
			[3] = 'Action.Text("Larnaca Airbase is under attack by a Marines Turkish force. We must try to defend it")',
		},
		['active'] = true,
	},
	['Larnaca Airbase Attack after Greece involvement'] = {
		['condition'] = 'Return.CampFlag(802) and (Return.Mission() >= Return.CampFlag(802) + 4)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("Larnaca Turkish Assault Force 1 T1.stm")',
			[2] = 'Action.TargetActive("Larnaca Turkish Assault Force 1", true)',
			[4] = 'Action.AddImage("LarnacaAttack.png")',
			[3] = 'Action.Text("Larnaca Airbase is under attack by a Marines Turkish force. We must try to defend it")',
		},
		['active'] = false,
	},
	['Gecitkale Airbase Alert activation after Greek involvment'] = {
		['condition'] = '(Return.CampFlag(802) and (Return.Mission() >= Return.CampFlag(802) + 8)) and (Return.TargetAlive("EWR-Jaguar") > 20)',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TargetActive("Gecitkale Airbase Alert", true)',
		},
		['active'] = false,
	},
	['North Cyprus-Turkish Force 4 retreat'] = {
		['condition'] = '(Return.Mission() > 23) and Return.CampFlag(834) and (Return.CampFlag(822) or Return.CampFlag(842)) and (Return.TargetAlive("Greek Expeditionary Force 2") > Return.TargetAlive("North Cyprus-Turkish Force 4") or Return.TargetAlive("Cyprus Defense Force 2") > Return.TargetAlive("North Cyprus-Turkish Force 4"))',
		['once'] = true,
		['action'] = {
			[1] = 'Action.TemplateActive("North Cyprus-Turkish Force 4 T2.stm")',
			[2] = 'Action.SetCampFlag(854, 0)',
		},
		['active'] = true,
	},
}
