camp = {
	['CVN_Vmax'] = 10,
	['date'] = {
		['day'] = 24,
		['month'] = 6,
		['minute'] = 29,
		['hour'] = 9,
		['year'] = 2004,
	},
	['MissionFilename'] = 'Cyprus Incident-Mirage_ongoing.miz',
	['idle_time_min'] = 10800,
	['dawn'] = 19800,
	['BaseAirStart'] = {
		['Kasteli Airbase'] = {
			['y'] = -575875,
			['x'] = -3194,
			['side'] = 'blue',
			['elevation'] = 0,
			['divert'] = false,
			['BaseAirStart'] = true,
			['ATC_frequency'] = '0',
		},
	},
	['day'] = 4,
	['waitingNextGen'] = true,
	['CVN_despawnAfterLanding'] = true,
	['code_loadout'] = 'Cyprus',
	['ShipMissions'] = {
	},
	['player'] = {
		['pack'] = {
			['Flare Illumination'] = {
			},
			['main'] = {
				[1] = {
					['number'] = 4,
					['tot_to'] = 5400,
					['eta_offset'] = 0,
					['divert'] = {
						['Akrotiri Airbase'] = 'Akrotiri Airbase',
						['Lakatamia Airbase'] = 'Lakatamia Airbase',
					},
					['firepower'] = 4,
					['livery'] = {
						[1] = 'Greek Air Force',
					},
					['base'] = 'Paphos Airbase',
					['task'] = 'Strike',
					['playable'] = true,
					['tot_from'] = 0,
					['type'] = 'M-2000C',
					['route'] = {
						[7] = {
							['eta'] = 1303.3821212237,
							['x'] = 28754.249708208,
							['id'] = 'Target',
							['alt'] = 200,
							['y'] = -222357.10925405,
						},
						[1] = {
							['eta'] = 0,
							['x'] = -18696.34668,
							['id'] = 'Taxi',
							['alt'] = 0,
							['y'] = -314208.375,
						},
						[2] = {
							['eta'] = 900,
							['x'] = -18696.34668,
							['id'] = 'Departure',
							['alt'] = 1536,
							['y'] = -314208.375,
						},
						[4] = {
							['eta'] = 1210.3527323041,
							['x'] = 13907.599330029,
							['id'] = 'Nav',
							['alt'] = 300.4,
							['y'] = -251096.12905828,
						},
						[8] = {
							['eta'] = 1423.9527346331,
							['x'] = 66300.110486104,
							['id'] = 'Egress',
							['alt'] = 200,
							['y'] = -241753.39597205,
						},
						[9] = {
							['eta'] = 1428.0506938168,
							['x'] = 65536.046820117,
							['id'] = 'Nav',
							['alt'] = 300.4,
							['y'] = -242404.71978884,
						},
						[5] = {
							['eta'] = 1212.8115078143,
							['x'] = 14184.0859159,
							['id'] = 'IP',
							['alt'] = 200,
							['y'] = -250560.92729461,
						},
						[10] = {
							['eta'] = 1818.5960314223,
							['x'] = -7281.0528654544,
							['id'] = 'Split',
							['alt'] = 300.4,
							['y'] = -304477.44148221,
						},
						[3] = {
							['eta'] = 981.63265306122,
							['x'] = -11811.720537785,
							['id'] = 'Join',
							['alt'] = 300.4,
							['y'] = -300881.63785688,
							['hCruiseREF'] = 300.4,
						},
						[6] = {
							['eta'] = 1272.8115078143,
							['x'] = 23836.331767286,
							['id'] = 'Attack',
							['alt'] = 200,
							['y'] = -231876.84181995,
						},
						[11] = {
							['eta'] = 1879.8205212182,
							['x'] = -18696.34668,
							['id'] = 'Land',
							['alt'] = 300.4,
							['y'] = -314208.375,
						},
					},
					['callsign'] = 'Ford91',
					['callsignId'] = 6,
					['name'] = 'EC 331',
					['loadout'] = {
						['hCruise'] = 300.4,
						['night'] = false,
						['loadout_name'] = '80s 90s 2000s SR AG Belouga*8,MagicII*2,FT*1',
						['capability'] = 1,
						['expend'] = 'All',
						['hAttack'] = 200,
						['support'] = {
							['Escort'] = true,
							['SEAD'] = true,
						},
						['attributes'] = {
							[1] = 'soft',
							[2] = 'SAM',
						},
						['minscore'] = 0.2,
						['vCruise'] = 245,
						['code_loadout'] = {
							[1] = 'Cyprus',
							[2] = 'Crisis',
							[4] = 'Caucasus',
							[3] = 'PG',
						},
						['stores'] = {
							['pylons'] = {
								[7] = {
									['CLSID'] = '{BLG66_BELOUGA_AC}',
									['num'] = 7,
								},
								[1] = {
									['CLSID'] = '{MMagicII}',
									['num'] = 1,
								},
								[2] = {
									['CLSID'] = '{M2KC_RAFAUT_BLG66}',
									['num'] = 2,
								},
								[4] = {
									['CLSID'] = '{BLG66_BELOUGA_AC}',
									['num'] = 4,
								},
								[8] = {
									['CLSID'] = '{M2KC_RAFAUT_BLG66}',
									['num'] = 8,
								},
								[9] = {
									['CLSID'] = '{MMagicII}',
									['num'] = 9,
								},
								[5] = {
									['CLSID'] = '{M2KC_RPL_522}',
									['num'] = 5,
								},
								[3] = {
									['CLSID'] = '{BLG66_BELOUGA_AC}',
									['num'] = 3,
								},
								[6] = {
									['CLSID'] = '{BLG66_BELOUGA_AC}',
									['num'] = 6,
								},
							},
							['fuel'] = 3165,
							['flare'] = 48,
							['chaff'] = 112,
							['gun'] = 100,
						},
						['LDSD'] = true,
						['firepower'] = 1,
						['hCruiseREF'] = 300.4,
						['hAttackREF'] = 200,
						['adverseWeather'] = false,
						['name'] = '80s 90s 2000s SR AG Belouga*8,MagicII*2,FT*1',
						['vAttack'] = 350.5,
						['range'] = 130000,
						['day'] = true,
						['weaponType'] = 'Bombs',
						['sortie_rate'] = 6,
					},
					['units'] = {
						[1] = {
							['alt'] = 621.6,
							['hardpoint_racks'] = true,
							['alt_type'] = 'RADIO',
							['livery_id'] = 'Greek Air Force',
							['skill'] = 'Player',
							['speed'] = 183.75,
							['heading'] = 0,
							['Radio'] = {
								[1] = {
									['channels'] = {
										[1] = 357.525,
									},
								},
								[2] = {
									['channels'] = {
										[6] = 357.525,
										[2] = 393.175,
										[3] = 251.8,
										[1] = 251.8,
										[4] = 251.9,
										[5] = 322.225,
									},
								},
							},
							['callsign'] = {
								[1] = 6,
								[2] = 9,
								['name'] = 'Ford91',
								[3] = 1,
							},
							['psi'] = 0,
							['y'] = -314208.375,
							['x'] = -18696.34668,
							['name'] = 'Pack 1 - EC 331 - Strike 1-1',
							['payload'] = {
								['pylons'] = {
									[7] = {
										['CLSID'] = '{BLG66_BELOUGA_AC}',
										['num'] = 7,
									},
									[1] = {
										['CLSID'] = '{MMagicII}',
										['num'] = 1,
									},
									[2] = {
										['CLSID'] = '{M2KC_RAFAUT_BLG66}',
										['num'] = 2,
									},
									[4] = {
										['CLSID'] = '{BLG66_BELOUGA_AC}',
										['num'] = 4,
									},
									[8] = {
										['CLSID'] = '{M2KC_RAFAUT_BLG66}',
										['num'] = 8,
									},
									[9] = {
										['CLSID'] = '{MMagicII}',
										['num'] = 9,
									},
									[5] = {
										['CLSID'] = '{M2KC_RPL_522}',
										['num'] = 5,
									},
									[3] = {
										['CLSID'] = '{BLG66_BELOUGA_AC}',
										['num'] = 3,
									},
									[6] = {
										['CLSID'] = '{BLG66_BELOUGA_AC}',
										['num'] = 6,
									},
								},
								['fuel'] = 3165,
								['flare'] = 48,
								['chaff'] = 112,
								['gun'] = 100,
							},
							['parking_id'] = '27',
							['unitId'] = 100022,
							['type'] = 'M-2000C',
							['onboard_num'] = '064',
						},
						[2] = {
							['alt'] = 621.6,
							['hardpoint_racks'] = true,
							['alt_type'] = 'RADIO',
							['livery_id'] = 'Greek Air Force',
							['skill'] = 'High',
							['speed'] = 183.75,
							['heading'] = 0,
							['Radio'] = {
								[1] = {
									['channels'] = {
									},
								},
								[2] = {
									['channels'] = {
									},
								},
							},
							['callsign'] = {
								[1] = 6,
								[2] = 9,
								['name'] = 'Ford92',
								[3] = 2,
							},
							['psi'] = 0,
							['y'] = -314108.375,
							['x'] = -18596.34668,
							['name'] = 'Pack 1 - EC 331 - Strike 1-2',
							['payload'] = {
								['pylons'] = {
									[7] = {
										['CLSID'] = '{BLG66_BELOUGA_AC}',
										['num'] = 7,
									},
									[1] = {
										['CLSID'] = '{MMagicII}',
										['num'] = 1,
									},
									[2] = {
										['CLSID'] = '{M2KC_RAFAUT_BLG66}',
										['num'] = 2,
									},
									[4] = {
										['CLSID'] = '{BLG66_BELOUGA_AC}',
										['num'] = 4,
									},
									[8] = {
										['CLSID'] = '{M2KC_RAFAUT_BLG66}',
										['num'] = 8,
									},
									[9] = {
										['CLSID'] = '{MMagicII}',
										['num'] = 9,
									},
									[5] = {
										['CLSID'] = '{M2KC_RPL_522}',
										['num'] = 5,
									},
									[3] = {
										['CLSID'] = '{BLG66_BELOUGA_AC}',
										['num'] = 3,
									},
									[6] = {
										['CLSID'] = '{BLG66_BELOUGA_AC}',
										['num'] = 6,
									},
								},
								['fuel'] = 3165,
								['flare'] = 48,
								['chaff'] = 112,
								['gun'] = 100,
							},
							['parking_id'] = '36',
							['unitId'] = 100023,
							['type'] = 'M-2000C',
							['onboard_num'] = '009',
						},
						[4] = {
							['alt'] = 621.6,
							['hardpoint_racks'] = true,
							['alt_type'] = 'RADIO',
							['livery_id'] = 'Greek Air Force',
							['skill'] = 'Average',
							['speed'] = 183.75,
							['heading'] = 0,
							['Radio'] = {
								[1] = {
									['channels'] = {
									},
								},
								[2] = {
									['channels'] = {
									},
								},
							},
							['callsign'] = {
								[1] = 6,
								[2] = 9,
								['name'] = 'Ford94',
								[3] = 4,
							},
							['psi'] = 0,
							['y'] = -313908.375,
							['x'] = -18396.34668,
							['name'] = 'Pack 1 - EC 331 - Strike 1-4',
							['payload'] = {
								['pylons'] = {
									[7] = {
										['CLSID'] = '{BLG66_BELOUGA_AC}',
										['num'] = 7,
									},
									[1] = {
										['CLSID'] = '{MMagicII}',
										['num'] = 1,
									},
									[2] = {
										['CLSID'] = '{M2KC_RAFAUT_BLG66}',
										['num'] = 2,
									},
									[4] = {
										['CLSID'] = '{BLG66_BELOUGA_AC}',
										['num'] = 4,
									},
									[8] = {
										['CLSID'] = '{M2KC_RAFAUT_BLG66}',
										['num'] = 8,
									},
									[9] = {
										['CLSID'] = '{MMagicII}',
										['num'] = 9,
									},
									[5] = {
										['CLSID'] = '{M2KC_RPL_522}',
										['num'] = 5,
									},
									[3] = {
										['CLSID'] = '{BLG66_BELOUGA_AC}',
										['num'] = 3,
									},
									[6] = {
										['CLSID'] = '{BLG66_BELOUGA_AC}',
										['num'] = 6,
									},
								},
								['fuel'] = 3165,
								['flare'] = 48,
								['chaff'] = 112,
								['gun'] = 100,
							},
							['parking_id'] = '30',
							['unitId'] = 100025,
							['type'] = 'M-2000C',
							['onboard_num'] = '062',
						},
						[3] = {
							['alt'] = 621.6,
							['hardpoint_racks'] = true,
							['alt_type'] = 'RADIO',
							['livery_id'] = 'Greek Air Force',
							['skill'] = 'Good',
							['speed'] = 183.75,
							['heading'] = 0,
							['Radio'] = {
								[1] = {
									['channels'] = {
									},
								},
								[2] = {
									['channels'] = {
									},
								},
							},
							['callsign'] = {
								[1] = 6,
								[2] = 9,
								['name'] = 'Ford93',
								[3] = 3,
							},
							['psi'] = 0,
							['y'] = -314008.375,
							['x'] = -18496.34668,
							['name'] = 'Pack 1 - EC 331 - Strike 1-3',
							['payload'] = {
								['pylons'] = {
									[7] = {
										['CLSID'] = '{BLG66_BELOUGA_AC}',
										['num'] = 7,
									},
									[1] = {
										['CLSID'] = '{MMagicII}',
										['num'] = 1,
									},
									[2] = {
										['CLSID'] = '{M2KC_RAFAUT_BLG66}',
										['num'] = 2,
									},
									[4] = {
										['CLSID'] = '{BLG66_BELOUGA_AC}',
										['num'] = 4,
									},
									[8] = {
										['CLSID'] = '{M2KC_RAFAUT_BLG66}',
										['num'] = 8,
									},
									[9] = {
										['CLSID'] = '{MMagicII}',
										['num'] = 9,
									},
									[5] = {
										['CLSID'] = '{M2KC_RPL_522}',
										['num'] = 5,
									},
									[3] = {
										['CLSID'] = '{BLG66_BELOUGA_AC}',
										['num'] = 3,
									},
									[6] = {
										['CLSID'] = '{BLG66_BELOUGA_AC}',
										['num'] = 6,
									},
								},
								['fuel'] = 3165,
								['flare'] = 48,
								['chaff'] = 112,
								['gun'] = 100,
							},
							['parking_id'] = '31',
							['unitId'] = 100024,
							['type'] = 'M-2000C',
							['onboard_num'] = '003',
						},
					},
					['parking_id'] = {
						[''] = {
							[13] = 35,
							[7] = 29,
							[1] = 23,
							[2] = 24,
							[4] = 26,
							[8] = 30,
							[15] = 37,
							[9] = 31,
							[5] = 27,
							[10] = 32,
							[14] = 36,
							[3] = 25,
							[6] = 28,
							[12] = 34,
							[11] = 33,
						},
					},
					['player'] = true,
					['target_name'] = 'North Cyprus-Turkish Force 1',
					['target'] = {
						['inactive'] = false,
						['elements'] = {
							[1] = {
								['y'] = -227527.00653597,
								['x'] = 28690.103240268,
								['name'] = 'NCTF 1-1',
								['dead_last'] = false,
								['foundOobGround'] = true,
								['groupId'] = 222,
							},
							[2] = {
								['y'] = -227476.53099799,
								['x'] = 28723.364136763,
								['name'] = 'NCTF 1-2',
								['dead_last'] = false,
								['foundOobGround'] = true,
								['groupId'] = 223,
							},
							[4] = {
								['y'] = -227372.95139661,
								['x'] = 28794.577216553,
								['name'] = 'NCTF 1-4',
								['dead_last'] = false,
								['foundOobGround'] = true,
								['groupId'] = 225,
							},
							[8] = {
								['name'] = 'NCTF 1-8',
								['groupId'] = 229,
								['dead_last'] = false,
								['foundOobGround'] = true,
								['dead'] = true,
							},
							[16] = {
								['y'] = -226808.75160384,
								['x'] = 29140.326924353,
								['name'] = 'NCTF 1-16',
								['dead_last'] = false,
								['foundOobGround'] = true,
								['groupId'] = 237,
							},
							[17] = {
								['y'] = -225540.33552455,
								['x'] = 29595.663381319,
								['name'] = 'NCTF 1-17',
								['dead_last'] = false,
								['foundOobGround'] = true,
								['groupId'] = 238,
							},
							[9] = {
								['name'] = 'NCTF 1-9',
								['groupId'] = 230,
								['dead_last'] = false,
								['foundOobGround'] = true,
								['dead'] = true,
							},
							[18] = {
								['y'] = -225470.84307322,
								['x'] = 29616.558286688,
								['name'] = 'NCTF 1-18',
								['dead_last'] = false,
								['foundOobGround'] = true,
								['groupId'] = 239,
							},
							[5] = {
								['y'] = -227320.29506404,
								['x'] = 28831.157161728,
								['name'] = 'NCTF 1-5',
								['dead_last'] = false,
								['foundOobGround'] = true,
								['groupId'] = 226,
							},
							[10] = {
								['name'] = 'NCTF 1-10',
								['groupId'] = 231,
								['dead_last'] = false,
								['foundOobGround'] = true,
								['dead'] = true,
							},
							[20] = {
								['y'] = -225704.34067694,
								['x'] = 29542.20022116,
								['name'] = 'NCTF 1-20',
								['dead_last'] = false,
								['foundOobGround'] = true,
								['groupId'] = 241,
							},
							[21] = {
								['y'] = -225828.98380572,
								['x'] = 29501.51000691,
								['name'] = 'NCTF 1-21',
								['dead_last'] = false,
								['foundOobGround'] = true,
								['groupId'] = 242,
							},
							[11] = {
								['y'] = -226703.1546814,
								['x'] = 29197.936793951,
								['name'] = 'NCTF 1-11',
								['dead_last'] = false,
								['foundOobGround'] = true,
								['groupId'] = 232,
							},
							[22] = {
								['y'] = -225991.66624171,
								['x'] = 29448.302802141,
								['name'] = 'NCTF 1-22',
								['dead_last'] = false,
								['foundOobGround'] = true,
								['groupId'] = 243,
							},
							[3] = {
								['y'] = -227422.96380421,
								['x'] = 28760.392054689,
								['name'] = 'NCTF 1-3',
								['dead_last'] = false,
								['foundOobGround'] = true,
								['groupId'] = 224,
							},
							[6] = {
								['y'] = -227125.06218315,
								['x'] = 28957.191352111,
								['name'] = 'NCTF 1-6',
								['dead_last'] = false,
								['foundOobGround'] = true,
								['groupId'] = 227,
							},
							[12] = {
								['y'] = -226752.9681482,
								['x'] = 29171.418053153,
								['name'] = 'NCTF 1-12',
								['dead_last'] = false,
								['foundOobGround'] = true,
								['groupId'] = 233,
							},
							[24] = {
								['y'] = -226107.00908993,
								['x'] = 29412.066776385,
								['name'] = 'NCTF 1-24',
								['dead_last'] = false,
								['foundOobGround'] = true,
								['groupId'] = 245,
							},
							[13] = {
								['y'] = -226387.25793196,
								['x'] = 29318.179577928,
								['name'] = 'NCTF 1-13',
								['dead_last'] = false,
								['foundOobGround'] = true,
								['groupId'] = 234,
							},
							[7] = {
								['name'] = 'NCTF 1-7',
								['groupId'] = 228,
								['dead_last'] = false,
								['foundOobGround'] = true,
								['dead'] = true,
							},
							[14] = {
								['y'] = -226482.94857757,
								['x'] = 29283.073840827,
								['name'] = 'NCTF 1-14',
								['dead_last'] = false,
								['foundOobGround'] = true,
								['groupId'] = 235,
							},
							[23] = {
								['y'] = -226212.53224902,
								['x'] = 29377.726051002,
								['name'] = 'NCTF 1-23',
								['dead_last'] = false,
								['foundOobGround'] = true,
								['groupId'] = 244,
							},
							[19] = {
								['y'] = -226302.19981244,
								['x'] = 29347.248850546,
								['name'] = 'NCTF 1-19',
								['dead_last'] = false,
								['foundOobGround'] = true,
								['groupId'] = 240,
							},
							[15] = {
								['y'] = -226594.38116934,
								['x'] = 29236.773354732,
								['name'] = 'NCTF 1-15',
								['dead_last'] = false,
								['foundOobGround'] = true,
								['groupId'] = 236,
							},
						},
						['picture'] = {
							[1] = 'NCTF-1.png',
						},
						['task'] = 'Strike',
						['class'] = 'static',
						['ATO'] = true,
						['attributes'] = {
							[1] = 'soft',
						},
						['y'] = -222357.10925405,
						['x'] = 28754.249708208,
						['firepower'] = {
							['min'] = 2,
							['max'] = 6,
						},
						['dead_last'] = 0,
						['alive'] = 83,
						['priority'] = 18,
						['foundOobGround'] = true,
						['TitleName'] = 'North Cyprus-Turkish Force 1',
					},
					['airdromeId'] = 46,
					['country'] = 'Greece',
					['skill'] = 'High',
					['frequency'] = 357.525,
				},
			},
			['Laser Illumination'] = {
			},
			['SEAD'] = {
			},
			['Escort Jammer'] = {
			},
			['Escort'] = {
			},
		},
		['side'] = 'blue',
		['group'] = {
			['frequency'] = 357.525,
			['taskSelected'] = true,
			['modulation'] = 0,
			['groupId'] = 100026,
			['tasks'] = {
			},
			['route'] = {
				['points'] = {
					[7] = {
						['alt'] = 300.4,
						['briefing_name'] = 'Nav',
						['action'] = 'Turning Point',
						['alt_type'] = 'RADIO',
						['properties'] = {
							['vnav'] = 1,
							['scale'] = 0,
							['angle'] = 0,
							['vangle'] = 0,
							['steer'] = 2,
						},
						['type'] = 'Turning Point',
						['ETA'] = 1428.0506938168,
						['y'] = -242404.71978884,
						['formation_template'] = '',
						['name'] = 'Nav    216  /    2 KM /   0 mn',
						['x'] = 65536.046820117,
						['speed'] = 245,
						['ETA_locked'] = false,
						['task'] = {
							['id'] = 'ComboTask',
							['params'] = {
								['tasks'] = {
								},
							},
						},
						['speed_locked'] = true,
					},
					[1] = {
						['speed_locked'] = true,
						['briefing_name'] = 'Departure',
						['action'] = 'From Parking Area',
						['alt_type'] = 'RADIO',
						['formation_template'] = '',
						['properties'] = {
							['vnav'] = 1,
							['scale'] = 0,
							['angle'] = 0,
							['vangle'] = 0,
							['steer'] = 2,
						},
						['airdromeId'] = 46,
						['alt'] = 621.6,
						['y'] = -314208.375,
						['x'] = -18696.34668,
						['name'] = 'Departure',
						['ETA_locked'] = true,
						['speed'] = 183.75,
						['ETA'] = 0,
						['task'] = {
							['id'] = 'ComboTask',
							['params'] = {
								['tasks'] = {
									[1] = {
										['number'] = 1,
										['auto'] = false,
										['id'] = 'WrappedAction',
										['enabled'] = true,
										['params'] = {
											['action'] = {
												['id'] = 'Option',
												['params'] = {
													['variantIndex'] = 1,
													['value'] = 458753,
													['name'] = 5,
													['formationIndex'] = 7,
												},
											},
										},
									},
									[2] = {
										['enabled'] = true,
										['auto'] = false,
										['id'] = 'WrappedAction',
										['number'] = 2,
										['params'] = {
											['action'] = {
												['id'] = 'Script',
												['params'] = {
													['command'] = 'OrbitPosition("Pack 1 - EC 331 - Strike 1", 621.6, 163.33333333333, 900)',
												},
											},
										},
									},
									[4] = {
										['enabled'] = true,
										['auto'] = false,
										['id'] = 'WrappedAction',
										['number'] = 4,
										['params'] = {
											['action'] = {
												['id'] = 'Option',
												['params'] = {
													['value'] = true,
													['name'] = 15,
												},
											},
										},
									},
									[3] = {
										['number'] = 3,
										['auto'] = false,
										['id'] = 'WrappedAction',
										['enabled'] = true,
										['params'] = {
											['action'] = {
												['id'] = 'Option',
												['params'] = {
													['value'] = 2,
													['name'] = 1,
												},
											},
										},
									},
								},
							},
						},
						['type'] = 'TakeOffParking',
					},
					[2] = {
						['speed_locked'] = true,
						['briefing_name'] = 'Join',
						['action'] = 'Turning Point',
						['alt_type'] = 'RADIO',
						['formation_template'] = '',
						['properties'] = {
							['vnav'] = 1,
							['scale'] = 0,
							['angle'] = 0,
							['vangle'] = 0,
							['steer'] = 2,
						},
						['alt'] = 300.4,
						['hCruiseREF'] = 300.4,
						['y'] = -300881.63785688,
						['x'] = -11811.720537785,
						['name'] = 'Join   058  /   15 KM /   1 mn',
						['ETA_locked'] = false,
						['speed'] = 183.75,
						['ETA'] = 981.63265306122,
						['task'] = {
							['id'] = 'ComboTask',
							['params'] = {
								['tasks'] = {
								},
							},
						},
						['type'] = 'Turning Point',
					},
					[4] = {
						['alt'] = 200,
						['briefing_name'] = 'IP',
						['action'] = 'Turning Point',
						['alt_type'] = 'RADIO',
						['properties'] = {
							['vnav'] = 1,
							['scale'] = 0,
							['angle'] = 0,
							['vangle'] = 0,
							['steer'] = 2,
						},
						['type'] = 'Turning Point',
						['ETA'] = 1212.8115078143,
						['y'] = -250560.92729461,
						['formation_template'] = '',
						['name'] = 'IP     058  /    1 KM /   0 mn',
						['x'] = 14184.0859159,
						['speed'] = 245,
						['ETA_locked'] = false,
						['task'] = {
							['id'] = 'ComboTask',
							['params'] = {
								['tasks'] = {
									[1] = {
										['enabled'] = true,
										['auto'] = false,
										['id'] = 'Bombing',
										['number'] = 1,
										['params'] = {
											['groupAttack'] = false,
											['attackQtyLimit'] = true,
											['attackQty'] = 1,
											['attackType'] = 'nil',
											['y'] = -227527.00653597,
											['x'] = 28690.103240268,
											['directionEnabled'] = false,
											['altitudeEdited'] = true,
											['altitudeEnabled'] = true,
											['altitude'] = 200,
											['weaponType'] = 2032,
											['direction'] = 0,
										},
									},
									[2] = {
										['enabled'] = true,
										['auto'] = false,
										['id'] = 'Bombing',
										['number'] = 2,
										['params'] = {
											['groupAttack'] = false,
											['attackQtyLimit'] = true,
											['attackQty'] = 1,
											['attackType'] = 'nil',
											['y'] = -227476.53099799,
											['x'] = 28723.364136763,
											['directionEnabled'] = false,
											['altitudeEdited'] = true,
											['altitudeEnabled'] = true,
											['altitude'] = 200,
											['weaponType'] = 2032,
											['direction'] = 0,
										},
									},
									[4] = {
										['enabled'] = true,
										['auto'] = false,
										['id'] = 'Bombing',
										['number'] = 4,
										['params'] = {
											['groupAttack'] = false,
											['attackQtyLimit'] = true,
											['attackQty'] = 1,
											['attackType'] = 'nil',
											['y'] = -227372.95139661,
											['x'] = 28794.577216553,
											['directionEnabled'] = false,
											['altitudeEdited'] = true,
											['altitudeEnabled'] = true,
											['altitude'] = 200,
											['weaponType'] = 2032,
											['direction'] = 0,
										},
									},
									[8] = {
										['enabled'] = true,
										['auto'] = false,
										['id'] = 'Bombing',
										['number'] = 8,
										['params'] = {
											['groupAttack'] = false,
											['attackQtyLimit'] = true,
											['attackQty'] = 1,
											['attackType'] = 'nil',
											['y'] = -226752.9681482,
											['x'] = 29171.418053153,
											['directionEnabled'] = false,
											['altitudeEdited'] = true,
											['altitudeEnabled'] = true,
											['altitude'] = 200,
											['weaponType'] = 2032,
											['direction'] = 0,
										},
									},
									[16] = {
										['enabled'] = true,
										['auto'] = false,
										['id'] = 'Bombing',
										['number'] = 16,
										['params'] = {
											['groupAttack'] = false,
											['attackQtyLimit'] = true,
											['attackQty'] = 1,
											['attackType'] = 'nil',
											['y'] = -225704.34067694,
											['x'] = 29542.20022116,
											['directionEnabled'] = false,
											['altitudeEdited'] = true,
											['altitudeEnabled'] = true,
											['altitude'] = 200,
											['weaponType'] = 2032,
											['direction'] = 0,
										},
									},
									[17] = {
										['enabled'] = true,
										['auto'] = false,
										['id'] = 'Bombing',
										['number'] = 17,
										['params'] = {
											['groupAttack'] = false,
											['attackQtyLimit'] = true,
											['attackQty'] = 1,
											['attackType'] = 'nil',
											['y'] = -225828.98380572,
											['x'] = 29501.51000691,
											['directionEnabled'] = false,
											['altitudeEdited'] = true,
											['altitudeEnabled'] = true,
											['altitude'] = 200,
											['weaponType'] = 2032,
											['direction'] = 0,
										},
									},
									[9] = {
										['enabled'] = true,
										['auto'] = false,
										['id'] = 'Bombing',
										['number'] = 9,
										['params'] = {
											['groupAttack'] = false,
											['attackQtyLimit'] = true,
											['attackQty'] = 1,
											['attackType'] = 'nil',
											['y'] = -226387.25793196,
											['x'] = 29318.179577928,
											['directionEnabled'] = false,
											['altitudeEdited'] = true,
											['altitudeEnabled'] = true,
											['altitude'] = 200,
											['weaponType'] = 2032,
											['direction'] = 0,
										},
									},
									[18] = {
										['enabled'] = true,
										['auto'] = false,
										['id'] = 'Bombing',
										['number'] = 18,
										['params'] = {
											['groupAttack'] = false,
											['attackQtyLimit'] = true,
											['attackQty'] = 1,
											['attackType'] = 'nil',
											['y'] = -225991.66624171,
											['x'] = 29448.302802141,
											['directionEnabled'] = false,
											['altitudeEdited'] = true,
											['altitudeEnabled'] = true,
											['altitude'] = 200,
											['weaponType'] = 2032,
											['direction'] = 0,
										},
									},
									[5] = {
										['enabled'] = true,
										['auto'] = false,
										['id'] = 'Bombing',
										['number'] = 5,
										['params'] = {
											['groupAttack'] = false,
											['attackQtyLimit'] = true,
											['attackQty'] = 1,
											['attackType'] = 'nil',
											['y'] = -227320.29506404,
											['x'] = 28831.157161728,
											['directionEnabled'] = false,
											['altitudeEdited'] = true,
											['altitudeEnabled'] = true,
											['altitude'] = 200,
											['weaponType'] = 2032,
											['direction'] = 0,
										},
									},
									[10] = {
										['enabled'] = true,
										['auto'] = false,
										['id'] = 'Bombing',
										['number'] = 10,
										['params'] = {
											['groupAttack'] = false,
											['attackQtyLimit'] = true,
											['attackQty'] = 1,
											['attackType'] = 'nil',
											['y'] = -226482.94857757,
											['x'] = 29283.073840827,
											['directionEnabled'] = false,
											['altitudeEdited'] = true,
											['altitudeEnabled'] = true,
											['altitude'] = 200,
											['weaponType'] = 2032,
											['direction'] = 0,
										},
									},
									[20] = {
										['enabled'] = true,
										['auto'] = false,
										['id'] = 'Bombing',
										['number'] = 20,
										['params'] = {
											['groupAttack'] = false,
											['attackQtyLimit'] = true,
											['attackQty'] = 1,
											['attackType'] = 'nil',
											['y'] = -226107.00908993,
											['x'] = 29412.066776385,
											['directionEnabled'] = false,
											['altitudeEdited'] = true,
											['altitudeEnabled'] = true,
											['altitude'] = 200,
											['weaponType'] = 2032,
											['direction'] = 0,
										},
									},
									[11] = {
										['enabled'] = true,
										['auto'] = false,
										['id'] = 'Bombing',
										['number'] = 11,
										['params'] = {
											['groupAttack'] = false,
											['attackQtyLimit'] = true,
											['attackQty'] = 1,
											['attackType'] = 'nil',
											['y'] = -226594.38116934,
											['x'] = 29236.773354732,
											['directionEnabled'] = false,
											['altitudeEdited'] = true,
											['altitudeEnabled'] = true,
											['altitude'] = 200,
											['weaponType'] = 2032,
											['direction'] = 0,
										},
									},
									[3] = {
										['enabled'] = true,
										['auto'] = false,
										['id'] = 'Bombing',
										['number'] = 3,
										['params'] = {
											['groupAttack'] = false,
											['attackQtyLimit'] = true,
											['attackQty'] = 1,
											['attackType'] = 'nil',
											['y'] = -227422.96380421,
											['x'] = 28760.392054689,
											['directionEnabled'] = false,
											['altitudeEdited'] = true,
											['altitudeEnabled'] = true,
											['altitude'] = 200,
											['weaponType'] = 2032,
											['direction'] = 0,
										},
									},
									[6] = {
										['enabled'] = true,
										['auto'] = false,
										['id'] = 'Bombing',
										['number'] = 6,
										['params'] = {
											['groupAttack'] = false,
											['attackQtyLimit'] = true,
											['attackQty'] = 1,
											['attackType'] = 'nil',
											['y'] = -227125.06218315,
											['x'] = 28957.191352111,
											['directionEnabled'] = false,
											['altitudeEdited'] = true,
											['altitudeEnabled'] = true,
											['altitude'] = 200,
											['weaponType'] = 2032,
											['direction'] = 0,
										},
									},
									[12] = {
										['enabled'] = true,
										['auto'] = false,
										['id'] = 'Bombing',
										['number'] = 12,
										['params'] = {
											['groupAttack'] = false,
											['attackQtyLimit'] = true,
											['attackQty'] = 1,
											['attackType'] = 'nil',
											['y'] = -226808.75160384,
											['x'] = 29140.326924353,
											['directionEnabled'] = false,
											['altitudeEdited'] = true,
											['altitudeEnabled'] = true,
											['altitude'] = 200,
											['weaponType'] = 2032,
											['direction'] = 0,
										},
									},
									[13] = {
										['enabled'] = true,
										['auto'] = false,
										['id'] = 'Bombing',
										['number'] = 13,
										['params'] = {
											['groupAttack'] = false,
											['attackQtyLimit'] = true,
											['attackQty'] = 1,
											['attackType'] = 'nil',
											['y'] = -225540.33552455,
											['x'] = 29595.663381319,
											['directionEnabled'] = false,
											['altitudeEdited'] = true,
											['altitudeEnabled'] = true,
											['altitude'] = 200,
											['weaponType'] = 2032,
											['direction'] = 0,
										},
									},
									[7] = {
										['enabled'] = true,
										['auto'] = false,
										['id'] = 'Bombing',
										['number'] = 7,
										['params'] = {
											['groupAttack'] = false,
											['attackQtyLimit'] = true,
											['attackQty'] = 1,
											['attackType'] = 'nil',
											['y'] = -226703.1546814,
											['x'] = 29197.936793951,
											['directionEnabled'] = false,
											['altitudeEdited'] = true,
											['altitudeEnabled'] = true,
											['altitude'] = 200,
											['weaponType'] = 2032,
											['direction'] = 0,
										},
									},
									[14] = {
										['enabled'] = true,
										['auto'] = false,
										['id'] = 'Bombing',
										['number'] = 14,
										['params'] = {
											['groupAttack'] = false,
											['attackQtyLimit'] = true,
											['attackQty'] = 1,
											['attackType'] = 'nil',
											['y'] = -225470.84307322,
											['x'] = 29616.558286688,
											['directionEnabled'] = false,
											['altitudeEdited'] = true,
											['altitudeEnabled'] = true,
											['altitude'] = 200,
											['weaponType'] = 2032,
											['direction'] = 0,
										},
									},
									[19] = {
										['enabled'] = true,
										['auto'] = false,
										['id'] = 'Bombing',
										['number'] = 19,
										['params'] = {
											['groupAttack'] = false,
											['attackQtyLimit'] = true,
											['attackQty'] = 1,
											['attackType'] = 'nil',
											['y'] = -226212.53224902,
											['x'] = 29377.726051002,
											['directionEnabled'] = false,
											['altitudeEdited'] = true,
											['altitudeEnabled'] = true,
											['altitude'] = 200,
											['weaponType'] = 2032,
											['direction'] = 0,
										},
									},
									[15] = {
										['enabled'] = true,
										['auto'] = false,
										['id'] = 'Bombing',
										['number'] = 15,
										['params'] = {
											['groupAttack'] = false,
											['attackQtyLimit'] = true,
											['attackQty'] = 1,
											['attackType'] = 'nil',
											['y'] = -226302.19981244,
											['x'] = 29347.248850546,
											['directionEnabled'] = false,
											['altitudeEdited'] = true,
											['altitudeEnabled'] = true,
											['altitude'] = 200,
											['weaponType'] = 2032,
											['direction'] = 0,
										},
									},
								},
							},
						},
						['speed_locked'] = true,
					},
					[8] = {
						['alt'] = 300.4,
						['briefing_name'] = 'Split',
						['action'] = 'Turning Point',
						['alt_type'] = 'RADIO',
						['properties'] = {
							['vnav'] = 1,
							['scale'] = 0,
							['angle'] = 0,
							['vangle'] = 0,
							['steer'] = 2,
						},
						['type'] = 'Turning Point',
						['ETA'] = 1818.5960314223,
						['y'] = -304477.44148221,
						['formation_template'] = '',
						['name'] = 'Split  216  /   96 KM /   7 mn',
						['x'] = -7281.0528654544,
						['speed'] = 245,
						['ETA_locked'] = false,
						['task'] = {
							['id'] = 'ComboTask',
							['params'] = {
								['tasks'] = {
								},
							},
						},
						['speed_locked'] = true,
					},
					[9] = {
						['speed_locked'] = true,
						['briefing_name'] = 'Land',
						['action'] = 'Landing',
						['alt_type'] = 'RADIO',
						['properties'] = {
							['vnav'] = 1,
							['scale'] = 0,
							['angle'] = 0,
							['vangle'] = 0,
							['steer'] = 2,
						},
						['speed'] = 245,
						['task'] = {
							['id'] = 'ComboTask',
							['params'] = {
								['tasks'] = {
								},
							},
						},
						['type'] = 'Land',
						['ETA'] = 1879.8205212182,
						['ETA_locked'] = false,
						['y'] = -314208.375,
						['x'] = -18696.34668,
						['name'] = 'Land   216  /   15 KM /   1 mn',
						['formation_template'] = '',
						['TotFlightTime'] = ' 00:16',
						['alt'] = 12,
						['TotFlightDist'] = '283 KM',
						['airdromeId'] = 46,
					},
					[5] = {
						['alt'] = 0,
						['briefing_name'] = 'Target',
						['action'] = 'Turning Point',
						['alt_type'] = 'RADIO',
						['properties'] = {
							['vnav'] = 1,
							['scale'] = 0,
							['angle'] = 0,
							['vangle'] = 0,
							['steer'] = 2,
						},
						['type'] = 'Turning Point',
						['ETA'] = 1303.3821212237,
						['y'] = -222357.10925405,
						['formation_template'] = '',
						['name'] = 'Target 058  /   32 KM /   1 mn',
						['x'] = 28754.249708208,
						['speed'] = 350.5,
						['ETA_locked'] = true,
						['task'] = {
							['id'] = 'ComboTask',
							['params'] = {
								['tasks'] = {
								},
							},
						},
						['speed_locked'] = false,
					},
					[3] = {
						['alt'] = 300.4,
						['briefing_name'] = 'Nav',
						['action'] = 'Turning Point',
						['alt_type'] = 'RADIO',
						['properties'] = {
							['vnav'] = 1,
							['scale'] = 0,
							['angle'] = 0,
							['vangle'] = 0,
							['steer'] = 2,
						},
						['type'] = 'Turning Point',
						['ETA'] = 1210.3527323041,
						['y'] = -251096.12905828,
						['formation_template'] = '',
						['name'] = 'Nav    058  /   57 KM /   4 mn',
						['x'] = 13907.599330029,
						['speed'] = 245,
						['ETA_locked'] = false,
						['task'] = {
							['id'] = 'ComboTask',
							['params'] = {
								['tasks'] = {
								},
							},
						},
						['speed_locked'] = true,
					},
					[6] = {
						['alt'] = 200,
						['briefing_name'] = 'Egress',
						['action'] = 'Turning Point',
						['alt_type'] = 'RADIO',
						['properties'] = {
							['vnav'] = 1,
							['scale'] = 0,
							['angle'] = 0,
							['vangle'] = 0,
							['steer'] = 2,
						},
						['type'] = 'Turning Point',
						['ETA'] = 1423.9527346331,
						['y'] = -241753.39597205,
						['formation_template'] = '',
						['name'] = 'Egress 328  /   43 KM /   2 mn',
						['x'] = 66300.110486104,
						['speed'] = 350.5,
						['ETA_locked'] = false,
						['task'] = {
							['id'] = 'ComboTask',
							['params'] = {
								['tasks'] = {
									[1] = {
										['enabled'] = true,
										['auto'] = false,
										['id'] = 'WrappedAction',
										['number'] = 1,
										['params'] = {
											['action'] = {
												['id'] = 'Script',
												['params'] = {
													['command'] = 'CustomRejoin("Pack 1 - EC 331 - Strike 1")',
												},
											},
										},
									},
								},
							},
						},
						['speed_locked'] = true,
					},
				},
			},
			['hidden'] = false,
			['units'] = {
				[1] = {
					['alt'] = 621.6,
					['hardpoint_racks'] = true,
					['alt_type'] = 'RADIO',
					['livery_id'] = 'Greek Air Force',
					['skill'] = 'Player',
					['speed'] = 183.75,
					['heading'] = 0,
					['Radio'] = {
						[1] = {
							['channels'] = {
								[1] = 357.525,
							},
						},
						[2] = {
							['channels'] = {
								[6] = 357.525,
								[2] = 393.175,
								[3] = 251.8,
								[1] = 251.8,
								[4] = 251.9,
								[5] = 322.225,
							},
						},
					},
					['callsign'] = {
						[1] = 6,
						[2] = 9,
						['name'] = 'Ford91',
						[3] = 1,
					},
					['psi'] = 0,
					['y'] = -314208.375,
					['x'] = -18696.34668,
					['name'] = 'Pack 1 - EC 331 - Strike 1-1',
					['payload'] = {
						['pylons'] = {
							[7] = {
								['CLSID'] = '{BLG66_BELOUGA_AC}',
								['num'] = 7,
							},
							[1] = {
								['CLSID'] = '{MMagicII}',
								['num'] = 1,
							},
							[2] = {
								['CLSID'] = '{M2KC_RAFAUT_BLG66}',
								['num'] = 2,
							},
							[4] = {
								['CLSID'] = '{BLG66_BELOUGA_AC}',
								['num'] = 4,
							},
							[8] = {
								['CLSID'] = '{M2KC_RAFAUT_BLG66}',
								['num'] = 8,
							},
							[9] = {
								['CLSID'] = '{MMagicII}',
								['num'] = 9,
							},
							[5] = {
								['CLSID'] = '{M2KC_RPL_522}',
								['num'] = 5,
							},
							[3] = {
								['CLSID'] = '{BLG66_BELOUGA_AC}',
								['num'] = 3,
							},
							[6] = {
								['CLSID'] = '{BLG66_BELOUGA_AC}',
								['num'] = 6,
							},
						},
						['fuel'] = 3165,
						['flare'] = 48,
						['chaff'] = 112,
						['gun'] = 100,
					},
					['parking_id'] = '27',
					['unitId'] = 100022,
					['type'] = 'M-2000C',
					['onboard_num'] = '064',
				},
				[2] = {
					['alt'] = 621.6,
					['hardpoint_racks'] = true,
					['alt_type'] = 'RADIO',
					['livery_id'] = 'Greek Air Force',
					['skill'] = 'High',
					['speed'] = 183.75,
					['heading'] = 0,
					['Radio'] = {
						[1] = {
							['channels'] = {
							},
						},
						[2] = {
							['channels'] = {
							},
						},
					},
					['callsign'] = {
						[1] = 6,
						[2] = 9,
						['name'] = 'Ford92',
						[3] = 2,
					},
					['psi'] = 0,
					['y'] = -314108.375,
					['x'] = -18596.34668,
					['name'] = 'Pack 1 - EC 331 - Strike 1-2',
					['payload'] = {
						['pylons'] = {
							[7] = {
								['CLSID'] = '{BLG66_BELOUGA_AC}',
								['num'] = 7,
							},
							[1] = {
								['CLSID'] = '{MMagicII}',
								['num'] = 1,
							},
							[2] = {
								['CLSID'] = '{M2KC_RAFAUT_BLG66}',
								['num'] = 2,
							},
							[4] = {
								['CLSID'] = '{BLG66_BELOUGA_AC}',
								['num'] = 4,
							},
							[8] = {
								['CLSID'] = '{M2KC_RAFAUT_BLG66}',
								['num'] = 8,
							},
							[9] = {
								['CLSID'] = '{MMagicII}',
								['num'] = 9,
							},
							[5] = {
								['CLSID'] = '{M2KC_RPL_522}',
								['num'] = 5,
							},
							[3] = {
								['CLSID'] = '{BLG66_BELOUGA_AC}',
								['num'] = 3,
							},
							[6] = {
								['CLSID'] = '{BLG66_BELOUGA_AC}',
								['num'] = 6,
							},
						},
						['fuel'] = 3165,
						['flare'] = 48,
						['chaff'] = 112,
						['gun'] = 100,
					},
					['parking_id'] = '36',
					['unitId'] = 100023,
					['type'] = 'M-2000C',
					['onboard_num'] = '009',
				},
				[4] = {
					['alt'] = 621.6,
					['hardpoint_racks'] = true,
					['alt_type'] = 'RADIO',
					['livery_id'] = 'Greek Air Force',
					['skill'] = 'Average',
					['speed'] = 183.75,
					['heading'] = 0,
					['Radio'] = {
						[1] = {
							['channels'] = {
							},
						},
						[2] = {
							['channels'] = {
							},
						},
					},
					['callsign'] = {
						[1] = 6,
						[2] = 9,
						['name'] = 'Ford94',
						[3] = 4,
					},
					['psi'] = 0,
					['y'] = -313908.375,
					['x'] = -18396.34668,
					['name'] = 'Pack 1 - EC 331 - Strike 1-4',
					['payload'] = {
						['pylons'] = {
							[7] = {
								['CLSID'] = '{BLG66_BELOUGA_AC}',
								['num'] = 7,
							},
							[1] = {
								['CLSID'] = '{MMagicII}',
								['num'] = 1,
							},
							[2] = {
								['CLSID'] = '{M2KC_RAFAUT_BLG66}',
								['num'] = 2,
							},
							[4] = {
								['CLSID'] = '{BLG66_BELOUGA_AC}',
								['num'] = 4,
							},
							[8] = {
								['CLSID'] = '{M2KC_RAFAUT_BLG66}',
								['num'] = 8,
							},
							[9] = {
								['CLSID'] = '{MMagicII}',
								['num'] = 9,
							},
							[5] = {
								['CLSID'] = '{M2KC_RPL_522}',
								['num'] = 5,
							},
							[3] = {
								['CLSID'] = '{BLG66_BELOUGA_AC}',
								['num'] = 3,
							},
							[6] = {
								['CLSID'] = '{BLG66_BELOUGA_AC}',
								['num'] = 6,
							},
						},
						['fuel'] = 3165,
						['flare'] = 48,
						['chaff'] = 112,
						['gun'] = 100,
					},
					['parking_id'] = '30',
					['unitId'] = 100025,
					['type'] = 'M-2000C',
					['onboard_num'] = '062',
				},
				[3] = {
					['alt'] = 621.6,
					['hardpoint_racks'] = true,
					['alt_type'] = 'RADIO',
					['livery_id'] = 'Greek Air Force',
					['skill'] = 'Good',
					['speed'] = 183.75,
					['heading'] = 0,
					['Radio'] = {
						[1] = {
							['channels'] = {
							},
						},
						[2] = {
							['channels'] = {
							},
						},
					},
					['callsign'] = {
						[1] = 6,
						[2] = 9,
						['name'] = 'Ford93',
						[3] = 3,
					},
					['psi'] = 0,
					['y'] = -314008.375,
					['x'] = -18496.34668,
					['name'] = 'Pack 1 - EC 331 - Strike 1-3',
					['payload'] = {
						['pylons'] = {
							[7] = {
								['CLSID'] = '{BLG66_BELOUGA_AC}',
								['num'] = 7,
							},
							[1] = {
								['CLSID'] = '{MMagicII}',
								['num'] = 1,
							},
							[2] = {
								['CLSID'] = '{M2KC_RAFAUT_BLG66}',
								['num'] = 2,
							},
							[4] = {
								['CLSID'] = '{BLG66_BELOUGA_AC}',
								['num'] = 4,
							},
							[8] = {
								['CLSID'] = '{M2KC_RAFAUT_BLG66}',
								['num'] = 8,
							},
							[9] = {
								['CLSID'] = '{MMagicII}',
								['num'] = 9,
							},
							[5] = {
								['CLSID'] = '{M2KC_RPL_522}',
								['num'] = 5,
							},
							[3] = {
								['CLSID'] = '{BLG66_BELOUGA_AC}',
								['num'] = 3,
							},
							[6] = {
								['CLSID'] = '{BLG66_BELOUGA_AC}',
								['num'] = 6,
							},
						},
						['fuel'] = 3165,
						['flare'] = 48,
						['chaff'] = 112,
						['gun'] = 100,
					},
					['parking_id'] = '31',
					['unitId'] = 100024,
					['type'] = 'M-2000C',
					['onboard_num'] = '003',
				},
			},
			['y'] = -314208.375,
			['radioSet'] = true,
			['name'] = 'Pack 1 - EC 331 - Strike 1',
			['communication'] = true,
			['x'] = -18696.34668,
			['start_time'] = 1,
			['task'] = 'CAS',
			['uncontrolled'] = false,
		},
		['flight'] = 1,
		['role'] = 'main',
		['target'] = {
			['x'] = 28754.249708208,
			['elements'] = {
				[1] = {
					['y'] = -227527.00653597,
					['x'] = 28690.103240268,
					['name'] = 'NCTF 1-1',
					['dead_last'] = false,
					['foundOobGround'] = true,
					['groupId'] = 222,
				},
				[2] = {
					['y'] = -227476.53099799,
					['x'] = 28723.364136763,
					['name'] = 'NCTF 1-2',
					['dead_last'] = false,
					['foundOobGround'] = true,
					['groupId'] = 223,
				},
				[4] = {
					['y'] = -227372.95139661,
					['x'] = 28794.577216553,
					['name'] = 'NCTF 1-4',
					['dead_last'] = false,
					['foundOobGround'] = true,
					['groupId'] = 225,
				},
				[8] = {
					['name'] = 'NCTF 1-8',
					['groupId'] = 229,
					['dead_last'] = false,
					['foundOobGround'] = true,
					['dead'] = true,
				},
				[16] = {
					['y'] = -226808.75160384,
					['x'] = 29140.326924353,
					['name'] = 'NCTF 1-16',
					['dead_last'] = false,
					['foundOobGround'] = true,
					['groupId'] = 237,
				},
				[17] = {
					['y'] = -225540.33552455,
					['x'] = 29595.663381319,
					['name'] = 'NCTF 1-17',
					['dead_last'] = false,
					['foundOobGround'] = true,
					['groupId'] = 238,
				},
				[9] = {
					['name'] = 'NCTF 1-9',
					['groupId'] = 230,
					['dead_last'] = false,
					['foundOobGround'] = true,
					['dead'] = true,
				},
				[18] = {
					['y'] = -225470.84307322,
					['x'] = 29616.558286688,
					['name'] = 'NCTF 1-18',
					['dead_last'] = false,
					['foundOobGround'] = true,
					['groupId'] = 239,
				},
				[5] = {
					['y'] = -227320.29506404,
					['x'] = 28831.157161728,
					['name'] = 'NCTF 1-5',
					['dead_last'] = false,
					['foundOobGround'] = true,
					['groupId'] = 226,
				},
				[10] = {
					['name'] = 'NCTF 1-10',
					['groupId'] = 231,
					['dead_last'] = false,
					['foundOobGround'] = true,
					['dead'] = true,
				},
				[20] = {
					['y'] = -225704.34067694,
					['x'] = 29542.20022116,
					['name'] = 'NCTF 1-20',
					['dead_last'] = false,
					['foundOobGround'] = true,
					['groupId'] = 241,
				},
				[21] = {
					['y'] = -225828.98380572,
					['x'] = 29501.51000691,
					['name'] = 'NCTF 1-21',
					['dead_last'] = false,
					['foundOobGround'] = true,
					['groupId'] = 242,
				},
				[11] = {
					['y'] = -226703.1546814,
					['x'] = 29197.936793951,
					['name'] = 'NCTF 1-11',
					['dead_last'] = false,
					['foundOobGround'] = true,
					['groupId'] = 232,
				},
				[22] = {
					['y'] = -225991.66624171,
					['x'] = 29448.302802141,
					['name'] = 'NCTF 1-22',
					['dead_last'] = false,
					['foundOobGround'] = true,
					['groupId'] = 243,
				},
				[3] = {
					['y'] = -227422.96380421,
					['x'] = 28760.392054689,
					['name'] = 'NCTF 1-3',
					['dead_last'] = false,
					['foundOobGround'] = true,
					['groupId'] = 224,
				},
				[6] = {
					['y'] = -227125.06218315,
					['x'] = 28957.191352111,
					['name'] = 'NCTF 1-6',
					['dead_last'] = false,
					['foundOobGround'] = true,
					['groupId'] = 227,
				},
				[12] = {
					['y'] = -226752.9681482,
					['x'] = 29171.418053153,
					['name'] = 'NCTF 1-12',
					['dead_last'] = false,
					['foundOobGround'] = true,
					['groupId'] = 233,
				},
				[24] = {
					['y'] = -226107.00908993,
					['x'] = 29412.066776385,
					['name'] = 'NCTF 1-24',
					['dead_last'] = false,
					['foundOobGround'] = true,
					['groupId'] = 245,
				},
				[13] = {
					['y'] = -226387.25793196,
					['x'] = 29318.179577928,
					['name'] = 'NCTF 1-13',
					['dead_last'] = false,
					['foundOobGround'] = true,
					['groupId'] = 234,
				},
				[7] = {
					['name'] = 'NCTF 1-7',
					['groupId'] = 228,
					['dead_last'] = false,
					['foundOobGround'] = true,
					['dead'] = true,
				},
				[14] = {
					['y'] = -226482.94857757,
					['x'] = 29283.073840827,
					['name'] = 'NCTF 1-14',
					['dead_last'] = false,
					['foundOobGround'] = true,
					['groupId'] = 235,
				},
				[23] = {
					['y'] = -226212.53224902,
					['x'] = 29377.726051002,
					['name'] = 'NCTF 1-23',
					['dead_last'] = false,
					['foundOobGround'] = true,
					['groupId'] = 244,
				},
				[19] = {
					['y'] = -226302.19981244,
					['x'] = 29347.248850546,
					['name'] = 'NCTF 1-19',
					['dead_last'] = false,
					['foundOobGround'] = true,
					['groupId'] = 240,
				},
				[15] = {
					['y'] = -226594.38116934,
					['x'] = 29236.773354732,
					['name'] = 'NCTF 1-15',
					['dead_last'] = false,
					['foundOobGround'] = true,
					['groupId'] = 236,
				},
			},
			['picture'] = {
				[1] = 'NCTF-1.png',
			},
			['foundOobGround'] = true,
			['class'] = 'static',
			['ATO'] = true,
			['firepower'] = {
				['min'] = 2,
				['max'] = 6,
			},
			['y'] = -222357.10925405,
			['inactive'] = false,
			['attributes'] = {
				[1] = 'soft',
			},
			['dead_last'] = 0,
			['alive'] = 83,
			['priority'] = 18,
			['task'] = 'Strike',
			['TitleName'] = 'North Cyprus-Turkish Force 1',
		},
		['waypoints'] = {
			[7] = {
				['speed_locked'] = true,
				['briefing_name'] = 'Egress',
				['ETA'] = 1423.9527346331,
				['alt_type'] = 'RADIO',
				['properties'] = {
					['vnav'] = 1,
					['scale'] = 0,
					['vangle'] = 0,
					['angle'] = 0,
					['steer'] = 2,
				},
				['action'] = 'Turning Point',
				['alt'] = 200,
				['y'] = -241753.39597205,
				['formation_template'] = '',
				['name'] = 'Egress 328  /   43 KM /   2 mn',
				['ETA_locked'] = false,
				['speed'] = 350.5,
				['x'] = 66300.110486104,
				['task'] = {
					['id'] = 'ComboTask',
					['params'] = {
						['tasks'] = {
							[1] = {
								['number'] = 1,
								['auto'] = false,
								['id'] = 'WrappedAction',
								['enabled'] = true,
								['params'] = {
									['action'] = {
										['id'] = 'Script',
										['params'] = {
											['command'] = 'CustomRejoin("Pack 1 - EC 331 - Strike 1")',
										},
									},
								},
							},
						},
					},
				},
				['type'] = 'Turning Point',
			},
			[1] = {
				['speed_locked'] = true,
				['airdromeId'] = 46,
				['ETA'] = 0,
				['alt_type'] = 'RADIO',
				['action'] = 'From Parking Area',
				['properties'] = {
					['vnav'] = 1,
					['scale'] = 0,
					['vangle'] = 0,
					['angle'] = 0,
					['steer'] = 2,
				},
				['briefing_name'] = 'Taxi',
				['alt'] = 0,
				['y'] = -314208.375,
				['x'] = -18696.34668,
				['name'] = 'Taxi',
				['ETA_locked'] = true,
				['speed'] = 245,
				['formation_template'] = '',
				['task'] = {
					['id'] = 'ComboTask',
					['params'] = {
						['tasks'] = {
						},
					},
				},
				['type'] = 'TakeOffParking',
			},
			[2] = {
				['speed_locked'] = true,
				['briefing_name'] = 'Departure',
				['ETA'] = 900,
				['alt_type'] = 'RADIO',
				['properties'] = {
					['vnav'] = 1,
					['scale'] = 0,
					['vangle'] = 0,
					['angle'] = 0,
					['steer'] = 2,
				},
				['action'] = 'Turning Point',
				['alt'] = 0,
				['y'] = -314208.375,
				['formation_template'] = '',
				['name'] = 'Departure',
				['ETA_locked'] = false,
				['speed'] = 0,
				['x'] = -18696.34668,
				['task'] = {
					['id'] = 'ComboTask',
					['params'] = {
						['tasks'] = {
							[1] = {
								['enabled'] = true,
								['auto'] = false,
								['id'] = 'WrappedAction',
								['number'] = 1,
								['params'] = {
									['action'] = {
										['id'] = 'Option',
										['params'] = {
											['value'] = 458753,
											['variantIndex'] = 1,
											['name'] = 5,
											['formationIndex'] = 7,
										},
									},
								},
							},
							[2] = {
								['number'] = 2,
								['auto'] = false,
								['id'] = 'WrappedAction',
								['enabled'] = true,
								['params'] = {
									['action'] = {
										['id'] = 'Script',
										['params'] = {
											['command'] = 'OrbitPosition("Pack 1 - EC 331 - Strike 1", 621.6, 163.33333333333, 900)',
										},
									},
								},
							},
						},
					},
				},
				['type'] = 'Turning Point',
			},
			[4] = {
				['speed_locked'] = true,
				['briefing_name'] = 'Nav',
				['ETA'] = 1210.3527323041,
				['alt_type'] = 'RADIO',
				['properties'] = {
					['vnav'] = 1,
					['scale'] = 0,
					['vangle'] = 0,
					['angle'] = 0,
					['steer'] = 2,
				},
				['action'] = 'Turning Point',
				['alt'] = 300.4,
				['y'] = -251096.12905828,
				['formation_template'] = '',
				['name'] = 'Nav    058  /   57 KM /   4 mn',
				['ETA_locked'] = false,
				['speed'] = 245,
				['x'] = 13907.599330029,
				['task'] = {
					['id'] = 'ComboTask',
					['params'] = {
						['tasks'] = {
						},
					},
				},
				['type'] = 'Turning Point',
			},
			[8] = {
				['speed_locked'] = true,
				['briefing_name'] = 'Nav',
				['ETA'] = 1428.0506938168,
				['alt_type'] = 'RADIO',
				['properties'] = {
					['vnav'] = 1,
					['scale'] = 0,
					['vangle'] = 0,
					['angle'] = 0,
					['steer'] = 2,
				},
				['action'] = 'Turning Point',
				['alt'] = 300.4,
				['y'] = -242404.71978884,
				['formation_template'] = '',
				['name'] = 'Nav    216  /    2 KM /   0 mn',
				['ETA_locked'] = false,
				['speed'] = 245,
				['x'] = 65536.046820117,
				['task'] = {
					['id'] = 'ComboTask',
					['params'] = {
						['tasks'] = {
						},
					},
				},
				['type'] = 'Turning Point',
			},
			[9] = {
				['speed_locked'] = true,
				['briefing_name'] = 'Split',
				['ETA'] = 1818.5960314223,
				['alt_type'] = 'RADIO',
				['properties'] = {
					['vnav'] = 1,
					['scale'] = 0,
					['vangle'] = 0,
					['angle'] = 0,
					['steer'] = 2,
				},
				['action'] = 'Turning Point',
				['alt'] = 300.4,
				['y'] = -304477.44148221,
				['formation_template'] = '',
				['name'] = 'Split  216  /   96 KM /   7 mn',
				['ETA_locked'] = false,
				['speed'] = 245,
				['x'] = -7281.0528654544,
				['task'] = {
					['id'] = 'ComboTask',
					['params'] = {
						['tasks'] = {
						},
					},
				},
				['type'] = 'Turning Point',
			},
			[5] = {
				['speed_locked'] = true,
				['briefing_name'] = 'IP',
				['ETA'] = 1212.8115078143,
				['alt_type'] = 'RADIO',
				['properties'] = {
					['vnav'] = 1,
					['scale'] = 0,
					['vangle'] = 0,
					['angle'] = 0,
					['steer'] = 2,
				},
				['action'] = 'Turning Point',
				['alt'] = 200,
				['y'] = -250560.92729461,
				['formation_template'] = '',
				['name'] = 'IP     058  /    1 KM /   0 mn',
				['ETA_locked'] = false,
				['speed'] = 245,
				['x'] = 14184.0859159,
				['task'] = {
					['id'] = 'ComboTask',
					['params'] = {
						['tasks'] = {
							[1] = {
								['number'] = 1,
								['auto'] = false,
								['id'] = 'Bombing',
								['enabled'] = true,
								['params'] = {
									['groupAttack'] = false,
									['attackQtyLimit'] = true,
									['attackQty'] = 1,
									['directionEnabled'] = false,
									['altitude'] = 200,
									['x'] = 28690.103240268,
									['direction'] = 0,
									['y'] = -227527.00653597,
									['altitudeEnabled'] = true,
									['altitudeEdited'] = true,
									['weaponType'] = 2032,
									['attackType'] = 'nil',
								},
							},
							[2] = {
								['number'] = 2,
								['auto'] = false,
								['id'] = 'Bombing',
								['enabled'] = true,
								['params'] = {
									['groupAttack'] = false,
									['attackQtyLimit'] = true,
									['attackQty'] = 1,
									['directionEnabled'] = false,
									['altitude'] = 200,
									['x'] = 28723.364136763,
									['direction'] = 0,
									['y'] = -227476.53099799,
									['altitudeEnabled'] = true,
									['altitudeEdited'] = true,
									['weaponType'] = 2032,
									['attackType'] = 'nil',
								},
							},
							[4] = {
								['number'] = 4,
								['auto'] = false,
								['id'] = 'Bombing',
								['enabled'] = true,
								['params'] = {
									['groupAttack'] = false,
									['attackQtyLimit'] = true,
									['attackQty'] = 1,
									['directionEnabled'] = false,
									['altitude'] = 200,
									['x'] = 28794.577216553,
									['direction'] = 0,
									['y'] = -227372.95139661,
									['altitudeEnabled'] = true,
									['altitudeEdited'] = true,
									['weaponType'] = 2032,
									['attackType'] = 'nil',
								},
							},
							[8] = {
								['number'] = 8,
								['auto'] = false,
								['id'] = 'Bombing',
								['enabled'] = true,
								['params'] = {
									['groupAttack'] = false,
									['attackQtyLimit'] = true,
									['attackQty'] = 1,
									['directionEnabled'] = false,
									['altitude'] = 200,
									['x'] = 29171.418053153,
									['direction'] = 0,
									['y'] = -226752.9681482,
									['altitudeEnabled'] = true,
									['altitudeEdited'] = true,
									['weaponType'] = 2032,
									['attackType'] = 'nil',
								},
							},
							[16] = {
								['number'] = 16,
								['auto'] = false,
								['id'] = 'Bombing',
								['enabled'] = true,
								['params'] = {
									['groupAttack'] = false,
									['attackQtyLimit'] = true,
									['attackQty'] = 1,
									['directionEnabled'] = false,
									['altitude'] = 200,
									['x'] = 29542.20022116,
									['direction'] = 0,
									['y'] = -225704.34067694,
									['altitudeEnabled'] = true,
									['altitudeEdited'] = true,
									['weaponType'] = 2032,
									['attackType'] = 'nil',
								},
							},
							[17] = {
								['number'] = 17,
								['auto'] = false,
								['id'] = 'Bombing',
								['enabled'] = true,
								['params'] = {
									['groupAttack'] = false,
									['attackQtyLimit'] = true,
									['attackQty'] = 1,
									['directionEnabled'] = false,
									['altitude'] = 200,
									['x'] = 29501.51000691,
									['direction'] = 0,
									['y'] = -225828.98380572,
									['altitudeEnabled'] = true,
									['altitudeEdited'] = true,
									['weaponType'] = 2032,
									['attackType'] = 'nil',
								},
							},
							[9] = {
								['number'] = 9,
								['auto'] = false,
								['id'] = 'Bombing',
								['enabled'] = true,
								['params'] = {
									['groupAttack'] = false,
									['attackQtyLimit'] = true,
									['attackQty'] = 1,
									['directionEnabled'] = false,
									['altitude'] = 200,
									['x'] = 29318.179577928,
									['direction'] = 0,
									['y'] = -226387.25793196,
									['altitudeEnabled'] = true,
									['altitudeEdited'] = true,
									['weaponType'] = 2032,
									['attackType'] = 'nil',
								},
							},
							[18] = {
								['number'] = 18,
								['auto'] = false,
								['id'] = 'Bombing',
								['enabled'] = true,
								['params'] = {
									['groupAttack'] = false,
									['attackQtyLimit'] = true,
									['attackQty'] = 1,
									['directionEnabled'] = false,
									['altitude'] = 200,
									['x'] = 29448.302802141,
									['direction'] = 0,
									['y'] = -225991.66624171,
									['altitudeEnabled'] = true,
									['altitudeEdited'] = true,
									['weaponType'] = 2032,
									['attackType'] = 'nil',
								},
							},
							[5] = {
								['number'] = 5,
								['auto'] = false,
								['id'] = 'Bombing',
								['enabled'] = true,
								['params'] = {
									['groupAttack'] = false,
									['attackQtyLimit'] = true,
									['attackQty'] = 1,
									['directionEnabled'] = false,
									['altitude'] = 200,
									['x'] = 28831.157161728,
									['direction'] = 0,
									['y'] = -227320.29506404,
									['altitudeEnabled'] = true,
									['altitudeEdited'] = true,
									['weaponType'] = 2032,
									['attackType'] = 'nil',
								},
							},
							[10] = {
								['number'] = 10,
								['auto'] = false,
								['id'] = 'Bombing',
								['enabled'] = true,
								['params'] = {
									['groupAttack'] = false,
									['attackQtyLimit'] = true,
									['attackQty'] = 1,
									['directionEnabled'] = false,
									['altitude'] = 200,
									['x'] = 29283.073840827,
									['direction'] = 0,
									['y'] = -226482.94857757,
									['altitudeEnabled'] = true,
									['altitudeEdited'] = true,
									['weaponType'] = 2032,
									['attackType'] = 'nil',
								},
							},
							[20] = {
								['number'] = 20,
								['auto'] = false,
								['id'] = 'Bombing',
								['enabled'] = true,
								['params'] = {
									['groupAttack'] = false,
									['attackQtyLimit'] = true,
									['attackQty'] = 1,
									['directionEnabled'] = false,
									['altitude'] = 200,
									['x'] = 29412.066776385,
									['direction'] = 0,
									['y'] = -226107.00908993,
									['altitudeEnabled'] = true,
									['altitudeEdited'] = true,
									['weaponType'] = 2032,
									['attackType'] = 'nil',
								},
							},
							[11] = {
								['number'] = 11,
								['auto'] = false,
								['id'] = 'Bombing',
								['enabled'] = true,
								['params'] = {
									['groupAttack'] = false,
									['attackQtyLimit'] = true,
									['attackQty'] = 1,
									['directionEnabled'] = false,
									['altitude'] = 200,
									['x'] = 29236.773354732,
									['direction'] = 0,
									['y'] = -226594.38116934,
									['altitudeEnabled'] = true,
									['altitudeEdited'] = true,
									['weaponType'] = 2032,
									['attackType'] = 'nil',
								},
							},
							[3] = {
								['number'] = 3,
								['auto'] = false,
								['id'] = 'Bombing',
								['enabled'] = true,
								['params'] = {
									['groupAttack'] = false,
									['attackQtyLimit'] = true,
									['attackQty'] = 1,
									['directionEnabled'] = false,
									['altitude'] = 200,
									['x'] = 28760.392054689,
									['direction'] = 0,
									['y'] = -227422.96380421,
									['altitudeEnabled'] = true,
									['altitudeEdited'] = true,
									['weaponType'] = 2032,
									['attackType'] = 'nil',
								},
							},
							[6] = {
								['number'] = 6,
								['auto'] = false,
								['id'] = 'Bombing',
								['enabled'] = true,
								['params'] = {
									['groupAttack'] = false,
									['attackQtyLimit'] = true,
									['attackQty'] = 1,
									['directionEnabled'] = false,
									['altitude'] = 200,
									['x'] = 28957.191352111,
									['direction'] = 0,
									['y'] = -227125.06218315,
									['altitudeEnabled'] = true,
									['altitudeEdited'] = true,
									['weaponType'] = 2032,
									['attackType'] = 'nil',
								},
							},
							[12] = {
								['number'] = 12,
								['auto'] = false,
								['id'] = 'Bombing',
								['enabled'] = true,
								['params'] = {
									['groupAttack'] = false,
									['attackQtyLimit'] = true,
									['attackQty'] = 1,
									['directionEnabled'] = false,
									['altitude'] = 200,
									['x'] = 29140.326924353,
									['direction'] = 0,
									['y'] = -226808.75160384,
									['altitudeEnabled'] = true,
									['altitudeEdited'] = true,
									['weaponType'] = 2032,
									['attackType'] = 'nil',
								},
							},
							[13] = {
								['number'] = 13,
								['auto'] = false,
								['id'] = 'Bombing',
								['enabled'] = true,
								['params'] = {
									['groupAttack'] = false,
									['attackQtyLimit'] = true,
									['attackQty'] = 1,
									['directionEnabled'] = false,
									['altitude'] = 200,
									['x'] = 29595.663381319,
									['direction'] = 0,
									['y'] = -225540.33552455,
									['altitudeEnabled'] = true,
									['altitudeEdited'] = true,
									['weaponType'] = 2032,
									['attackType'] = 'nil',
								},
							},
							[7] = {
								['number'] = 7,
								['auto'] = false,
								['id'] = 'Bombing',
								['enabled'] = true,
								['params'] = {
									['groupAttack'] = false,
									['attackQtyLimit'] = true,
									['attackQty'] = 1,
									['directionEnabled'] = false,
									['altitude'] = 200,
									['x'] = 29197.936793951,
									['direction'] = 0,
									['y'] = -226703.1546814,
									['altitudeEnabled'] = true,
									['altitudeEdited'] = true,
									['weaponType'] = 2032,
									['attackType'] = 'nil',
								},
							},
							[14] = {
								['number'] = 14,
								['auto'] = false,
								['id'] = 'Bombing',
								['enabled'] = true,
								['params'] = {
									['groupAttack'] = false,
									['attackQtyLimit'] = true,
									['attackQty'] = 1,
									['directionEnabled'] = false,
									['altitude'] = 200,
									['x'] = 29616.558286688,
									['direction'] = 0,
									['y'] = -225470.84307322,
									['altitudeEnabled'] = true,
									['altitudeEdited'] = true,
									['weaponType'] = 2032,
									['attackType'] = 'nil',
								},
							},
							[19] = {
								['number'] = 19,
								['auto'] = false,
								['id'] = 'Bombing',
								['enabled'] = true,
								['params'] = {
									['groupAttack'] = false,
									['attackQtyLimit'] = true,
									['attackQty'] = 1,
									['directionEnabled'] = false,
									['altitude'] = 200,
									['x'] = 29377.726051002,
									['direction'] = 0,
									['y'] = -226212.53224902,
									['altitudeEnabled'] = true,
									['altitudeEdited'] = true,
									['weaponType'] = 2032,
									['attackType'] = 'nil',
								},
							},
							[15] = {
								['number'] = 15,
								['auto'] = false,
								['id'] = 'Bombing',
								['enabled'] = true,
								['params'] = {
									['groupAttack'] = false,
									['attackQtyLimit'] = true,
									['attackQty'] = 1,
									['directionEnabled'] = false,
									['altitude'] = 200,
									['x'] = 29347.248850546,
									['direction'] = 0,
									['y'] = -226302.19981244,
									['altitudeEnabled'] = true,
									['altitudeEdited'] = true,
									['weaponType'] = 2032,
									['attackType'] = 'nil',
								},
							},
						},
					},
				},
				['type'] = 'Turning Point',
			},
			[10] = {
				['alt'] = 12,
				['briefing_name'] = 'Land',
				['action'] = 'Landing',
				['alt_type'] = 'RADIO',
				['properties'] = {
					['vnav'] = 1,
					['scale'] = 0,
					['vangle'] = 0,
					['angle'] = 0,
					['steer'] = 2,
				},
				['speed'] = 245,
				['task'] = {
					['id'] = 'ComboTask',
					['params'] = {
						['tasks'] = {
						},
					},
				},
				['airdromeId'] = 46,
				['ETA'] = 1879.8205212182,
				['ETA_locked'] = false,
				['y'] = -314208.375,
				['x'] = -18696.34668,
				['name'] = 'Land   216  /   15 KM /   1 mn',
				['TotFlightTime'] = ' 00:16',
				['type'] = 'Land',
				['speed_locked'] = true,
				['TotFlightDist'] = '283 KM',
				['formation_template'] = '',
			},
			[3] = {
				['speed_locked'] = true,
				['type'] = 'Turning Point',
				['action'] = 'Turning Point',
				['alt_type'] = 'RADIO',
				['briefing_name'] = 'Join',
				['properties'] = {
					['vnav'] = 1,
					['scale'] = 0,
					['vangle'] = 0,
					['angle'] = 0,
					['steer'] = 2,
				},
				['x'] = -11811.720537785,
				['hCruiseREF'] = 300.4,
				['y'] = -300881.63785688,
				['formation_template'] = '',
				['name'] = 'Join   058  /   15 KM /   1 mn',
				['ETA'] = 981.63265306122,
				['speed'] = 183.75,
				['ETA_locked'] = false,
				['task'] = {
					['id'] = 'ComboTask',
					['params'] = {
						['tasks'] = {
						},
					},
				},
				['alt'] = 300.4,
			},
			[6] = {
				['speed_locked'] = false,
				['briefing_name'] = 'Target',
				['ETA'] = 1303.3821212237,
				['alt_type'] = 'RADIO',
				['properties'] = {
					['vnav'] = 1,
					['scale'] = 0,
					['vangle'] = 0,
					['angle'] = 0,
					['steer'] = 2,
				},
				['action'] = 'Turning Point',
				['alt'] = 0,
				['y'] = -222357.10925405,
				['formation_template'] = '',
				['name'] = 'Target 058  /   32 KM /   1 mn',
				['ETA_locked'] = true,
				['speed'] = 350.5,
				['x'] = 28754.249708208,
				['task'] = {
					['id'] = 'ComboTask',
					['params'] = {
						['tasks'] = {
						},
					},
				},
				['type'] = 'Turning Point',
			},
		},
		['pack_n'] = 1,
		['airbase'] = 'Paphos Airbase',
		['tgt_wp'] = 6,
		['unitname'] = 'M-2000C Pack 1 - EC 331 - Strike 1-1',
	},
	['title'] = 'Cyprus Incident-Mirage',
	['aircraft_availability'] = {
		['3rd KHA'] = {
			['assigned'] = 2,
			['available'] = 2,
			['unassigned'] = 0,
			['unavailable'] = {
				[6] = 305321,
				[2] = 307754,
				[3] = 305321,
				[1] = 307754,
				[4] = 305321,
				[5] = 305321,
			},
			['serviceable'] = 5,
			['ready'] = 6,
		},
		['222.Filo'] = {
			['assigned'] = 2,
			['available'] = 2,
			['unassigned'] = 0,
			['unavailable'] = {
				[6] = 305321,
				[2] = 307754,
				[3] = 305321,
				[1] = 307754,
				[4] = 305321,
				[5] = 305321,
			},
			['serviceable'] = 5,
			['ready'] = 6,
		},
		['450 M-E/P-1'] = {
			['assigned'] = 2,
			['available'] = 2,
			['unassigned'] = 0,
			['unavailable'] = {
				[6] = 301534,
				[2] = 305321,
				[3] = 305321,
				[1] = 305321,
				[4] = 305321,
				[5] = 301534,
			},
			['serviceable'] = 4,
			['ready'] = 6,
		},
		['EC 331'] = {
			['assigned'] = 4,
			['available'] = 4,
			['unassigned'] = 0,
			['unavailable'] = {
				[7] = 295829,
				[1] = 305321,
				[2] = 301534,
				[4] = 301534,
				[8] = 295829,
				[9] = 295829,
				[5] = 301534,
				[10] = 294029,
				[3] = 301534,
				[6] = 295829,
				[11] = 294029,
			},
			['serviceable'] = 9,
			['ready'] = 11,
		},
		['134.Filo'] = {
			['assigned'] = 0,
			['available'] = 1,
			['unassigned'] = 1,
			['unavailable'] = {
				[2] = 299101,
				[3] = 299101,
				[1] = 299101,
				[4] = 299101,
				[5] = 0,
			},
			['serviceable'] = 4,
			['ready'] = 5,
		},
		['2nd-2 KHA'] = {
			['assigned'] = 2,
			['available'] = 2,
			['unassigned'] = 0,
			['unavailable'] = {
				[6] = 301994,
				[2] = 305321,
				[3] = 305321,
				[1] = 305321,
				[4] = 305321,
				[5] = 301994,
			},
			['serviceable'] = 5,
			['ready'] = 6,
		},
		['111.Filo'] = {
			['assigned'] = 2,
			['available'] = 2,
			['unassigned'] = 0,
			['unavailable'] = {
				[7] = 299101,
				[1] = 305321,
				[2] = 305321,
				[4] = 301534,
				[8] = 299101,
				[9] = 299101,
				[5] = 301534,
				[3] = 305321,
				[6] = 299101,
			},
			['serviceable'] = 8,
			['ready'] = 9,
		},
		['450 M-E/P-2'] = {
			['assigned'] = 0,
			['available'] = 1,
			['unassigned'] = 1,
			['unavailable'] = {
				[1] = 305321,
				[2] = 305321,
				[4] = 0,
				[3] = 305321,
			},
			['serviceable'] = 4,
			['ready'] = 4,
		},
		['2nd KHA'] = {
			['assigned'] = 0,
			['available'] = 0,
			['unassigned'] = 0,
			['unavailable'] = {
				[6] = 299561,
				[2] = 299561,
				[3] = 299561,
				[1] = 299561,
				[4] = 299561,
				[5] = 299561,
			},
			['serviceable'] = 4,
			['ready'] = 6,
		},
		['356th Tactical Transport Squadron'] = {
			['assigned'] = 3,
			['available'] = 3,
			['unassigned'] = 0,
			['unavailable'] = {
				[6] = 305321,
				[2] = 307754,
				[3] = 307754,
				[1] = 307754,
				[4] = 305321,
				[5] = 305321,
			},
			['serviceable'] = 5,
			['ready'] = 6,
		},
	},
	['mission'] = 9,
	['path'] = 'P:/Saved Games/DCS.openbeta/',
	['startup'] = 600,
	['SC_CarrierIntoWind'] = 'man',
	['idle_time_max'] = 14400,
	['time'] = 34154,
	['ShipDamagedLast'] = {
	},
	['weather'] = {
		['zoneNextTemp'] = 30,
		['pHigh'] = 60,
		['pLow'] = 40,
		['zoneNext'] = 'high',
		['zoneTemp'] = 33,
		['refTemp'] = 28,
		['zoneEnd'] = 2083662,
		['zoneStart'] = 1930666,
		['zone'] = 'high',
	},
	['CVN_windDeck'] = 9,
	['dusk'] = 68880,
	['radio'] = {
		['blue'] = {
			[1] = {
				['UHF'] = {
					['min'] = 225,
					['max'] = 300,
				},
				['FM'] = {
					['min'] = 30,
					['max'] = 50,
				},
				['VHF'] = {
					['min'] = 118,
					['max'] = 136,
				},
			},
			[2] = {
				['UHF'] = {
					['min'] = 225,
					['max'] = 400,
				},
				['VHF'] = {
					['min'] = 118,
					['max'] = 140,
				},
			},
			[3] = {
				['UHF'] = {
					['min'] = 225,
					['max'] = 399.9,
				},
			},
		},
		['red'] = {
			[1] = {
				['UHF'] = {
					['min'] = 225,
					['max'] = 300,
				},
				['VHF'] = {
					['min'] = 118,
					['max'] = 136,
				},
			},
		},
	},
	['MultiPlayer'] = {
		['pack_n'] = {
		},
	},
	['versionPackageICM'] = 'NG',
	['units'] = 'metric',
	['debug'] = false,
	['version'] = 'V2.15',
	['mission_duration'] = 5400,
	['ScriptsMod'] = '20.58.205',
	['flag'] = {
		[803] = 6,
		[811] = 7,
		[801] = 5,
		[804] = 9,
	},
	['variation'] = 4,
	['ShipHealth'] = {
		['Turkish Naval Convoy 1-2'] = 100,
		['Turkish Naval Convoy 1-3'] = 100,
		['Greek Naval Convoy-1'] = 100,
		['Naval-1-3'] = 100,
		['Greek Naval Convoy-4'] = 100,
		['Larnaca Turkish Assault Force 1-Boat-1'] = 100,
		['Turkish Naval Convoy 2-3'] = 100,
		['Naval-1-4'] = 100,
		['Turkish Naval Convoy 2-1'] = 100,
		['Greek Naval Convoy-8'] = 100,
		['Greek Naval Convoy-5'] = 100,
		['Greek Naval Convoy-6'] = 100,
		['Turkish Naval Convoy 1-4'] = 100,
		['Greek Naval Convoy-3'] = 100,
		['Turkish Naval Convoy 2-4'] = 100,
		['Turkish Naval Convoy 1-5'] = 100,
		['Naval-1-6'] = 100,
		['Naval-1-2'] = 100,
		['Turkish Naval Convoy 2-5'] = 100,
		['Naval-1-9'] = 100,
		['Naval-1-7'] = 100,
		['Turkish Naval Convoy 1-1'] = 100,
		['Naval-1-1'] = 100,
		['Naval-1-8'] = 100,
		['Naval-1-5'] = 100,
		['Turkish Naval Convoy 1-6'] = 100,
		['Greek Naval Convoy-2'] = 100,
		['Greek Naval Convoy-9'] = 100,
		['Greek Naval Convoy-7'] = 100,
		['Turkish Naval Convoy 2-2'] = 100,
	},
	['ShipHealth0'] = {
		['Turkish Naval Convoy 1-2'] = 1000,
		['Turkish Naval Convoy 1-3'] = 1000,
		['Greek Naval Convoy-1'] = 2100,
		['Naval-1-3'] = 750,
		['Greek Naval Convoy-4'] = 1000,
		['Larnaca Turkish Assault Force 1-Boat-1'] = 1000,
		['Turkish Naval Convoy 2-3'] = 1000,
		['Naval-1-4'] = 200,
		['Turkish Naval Convoy 2-1'] = 2100,
		['Greek Naval Convoy-8'] = 1000,
		['Greek Naval Convoy-5'] = 1000,
		['Greek Naval Convoy-6'] = 1000,
		['Turkish Naval Convoy 1-4'] = 1000,
		['Greek Naval Convoy-3'] = 1000,
		['Turkish Naval Convoy 2-4'] = 1000,
		['Turkish Naval Convoy 1-5'] = 1000,
		['Naval-1-6'] = 400,
		['Naval-1-2'] = 750,
		['Turkish Naval Convoy 2-5'] = 1000,
		['Naval-1-9'] = 1000,
		['Naval-1-7'] = 200,
		['Turkish Naval Convoy 1-1'] = 2100,
		['Naval-1-1'] = 2100,
		['Naval-1-8'] = 200,
		['Naval-1-5'] = 1000,
		['Turkish Naval Convoy 1-6'] = 1000,
		['Greek Naval Convoy-2'] = 750,
		['Greek Naval Convoy-9'] = 750,
		['Greek Naval Convoy-7'] = 1000,
		['Turkish Naval Convoy 2-2'] = 1000,
	},
}
