camp = {
	['CVN_Vmax'] = 10,
	['date'] = {
		['day'] = 24,
		['month'] = 6,
		['year'] = 2004,
		['hour'] = 10,
		['minute'] = 5,
	},
	['MissionFilename'] = 'Cyprus Incident-Mirage_ongoing.miz',
	['idle_time_min'] = 10800,
	['dawn'] = 19800,
	['BaseAirStart'] = {
	},
	['day'] = 4,
	['waitingNextGen'] = true,
	['CVN_despawnAfterLanding'] = true,
	['code_loadout'] = 'Cyprus',
	['ShipMissions'] = {
	},
	['player'] = {
		['pack'] = {
			['Flare Illumination'] = {
			},
			['main'] = {
				[1] = {
					['number'] = 2,
					['tot_to'] = 5400,
					['eta_offset'] = 0,
					['divert'] = {
						['Akrotiri Airbase'] = 'Akrotiri Airbase',
						['FARP-London'] = 'FARP-London',
						['Lakatamia Airbase'] = 'Lakatamia Airbase',
					},
					['firepower'] = 2,
					['livery'] = {
						[1] = 'Greek Air Force',
					},
					['task'] = 'Strike',
					['base'] = 'Paphos Airbase',
					['playable'] = true,
					['skill'] = 'High',
					['type'] = 'M-2000C',
					['route'] = {
						[1] = {
							['eta'] = 0,
							['x'] = -18696.34668,
							['id'] = 'Taxi',
							['y'] = -314208.375,
							['alt'] = 0,
						},
						[2] = {
							['eta'] = 900,
							['x'] = -18696.34668,
							['id'] = 'Departure',
							['y'] = -314208.375,
							['alt'] = 1536,
						},
						[3] = {
							['eta'] = 981.63265306122,
							['x'] = -11566.526123237,
							['id'] = 'Join',
							['alt'] = 300.4,
							['y'] = -301011.1912539,
							['hCruiseREF'] = 300.4,
						},
						[4] = {
							['eta'] = 1163.3019174021,
							['x'] = 9589.5383821139,
							['id'] = 'Nav',
							['y'] = -261851.65443265,
							['alt'] = 300.4,
						},
						[5] = {
							['eta'] = 1165.7606929123,
							['x'] = 9875.8719756735,
							['id'] = 'IP',
							['y'] = -261321.6555334,
							['alt'] = 200,
						},
						[6] = {
							['eta'] = 1225.7606929123,
							['x'] = 19871.880396255,
							['id'] = 'Attack',
							['y'] = -242819.20392137,
							['alt'] = 200,
						},
						[7] = {
							['eta'] = 1256.3313063217,
							['x'] = 24964.948880636,
							['id'] = 'Target',
							['y'] = -233392.0156654,
							['alt'] = 200,
						},
						[8] = {
							['eta'] = 1376.9019197311,
							['x'] = 62145.814554652,
							['id'] = 'Egress',
							['y'] = -253479.09678066,
							['alt'] = 200,
						},
						[9] = {
							['eta'] = 1380.9998789148,
							['x'] = 61343.080251696,
							['id'] = 'Nav',
							['y'] = -254082.11721054,
							['alt'] = 300.4,
						},
						[10] = {
							['eta'] = 1728.376720148,
							['x'] = -6703.3043051537,
							['id'] = 'Split',
							['y'] = -305199.10562923,
							['alt'] = 300.4,
						},
						[11] = {
							['eta'] = 1789.6012099439,
							['x'] = -18696.34668,
							['id'] = 'Land',
							['y'] = -314208.375,
							['alt'] = 300.4,
						},
					},
					['callsign'] = 'Ford71',
					['country'] = 'Greece',
					['airdromeId'] = 46,
					['loadout'] = {
						['hCruise'] = 300.4,
						['night'] = false,
						['loadout_name'] = '80s 90s 2000s SR AG Belouga*8,MagicII*2,FT*1',
						['capability'] = 1,
						['expend'] = 'All',
						['hAttack'] = 200,
						['support'] = {
							['Escort'] = true,
							['SEAD'] = true,
						},
						['attributes'] = {
							[1] = 'soft',
							[2] = 'SAM',
						},
						['minscore'] = 0.2,
						['vCruise'] = 245,
						['code_loadout'] = {
							[1] = 'Cyprus',
							[2] = 'Crisis',
							[3] = 'PG',
							[4] = 'Caucasus',
						},
						['stores'] = {
							['pylons'] = {
								[1] = {
									['CLSID'] = '{MMagicII}',
									['num'] = 1,
								},
								[2] = {
									['CLSID'] = '{M2KC_RAFAUT_BLG66}',
									['num'] = 2,
								},
								[3] = {
									['CLSID'] = '{BLG66_BELOUGA_AC}',
									['num'] = 3,
								},
								[4] = {
									['CLSID'] = '{BLG66_BELOUGA_AC}',
									['num'] = 4,
								},
								[5] = {
									['CLSID'] = '{M2KC_RPL_522}',
									['num'] = 5,
								},
								[6] = {
									['CLSID'] = '{BLG66_BELOUGA_AC}',
									['num'] = 6,
								},
								[7] = {
									['CLSID'] = '{BLG66_BELOUGA_AC}',
									['num'] = 7,
								},
								[8] = {
									['CLSID'] = '{M2KC_RAFAUT_BLG66}',
									['num'] = 8,
								},
								[9] = {
									['CLSID'] = '{MMagicII}',
									['num'] = 9,
								},
							},
							['fuel'] = 3165,
							['flare'] = 48,
							['chaff'] = 112,
							['gun'] = 100,
						},
						['LDSD'] = true,
						['firepower'] = 1,
						['hCruiseREF'] = 300.4,
						['hAttackREF'] = 200,
						['day'] = true,
						['name'] = '80s 90s 2000s SR AG Belouga*8,MagicII*2,FT*1',
						['vAttack'] = 350.5,
						['range'] = 130000,
						['adverseWeather'] = false,
						['weaponType'] = 'Bombs',
						['sortie_rate'] = 6,
					},
					['units'] = {
						[1] = {
							['alt'] = 621.6,
							['hardpoint_racks'] = true,
							['alt_type'] = 'RADIO',
							['livery_id'] = 'Greek Air Force',
							['skill'] = 'Player',
							['speed'] = 183.75,
							['heading'] = 0,
							['Radio'] = {
								[1] = {
									['channels'] = {
										[1] = 322.9,
									},
								},
								[2] = {
									['channels'] = {
										[1] = 251.8,
										[2] = 295.05,
										[3] = 251.8,
										[4] = 129.5,
										[5] = 251.9,
										[6] = 322.9,
									},
								},
							},
							['callsign'] = {
								[1] = 6,
								[2] = 7,
								['name'] = 'Ford71',
								[3] = 1,
							},
							['psi'] = 0,
							['y'] = -314208.375,
							['x'] = -18696.34668,
							['name'] = 'Pack 1 - EC 331 - Strike 1-1',
							['payload'] = {
								['pylons'] = {
									[7] = {
										['CLSID'] = '{BLG66_BELOUGA_AC}',
										['num'] = 7,
									},
									[1] = {
										['CLSID'] = '{MMagicII}',
										['num'] = 1,
									},
									[2] = {
										['CLSID'] = '{M2KC_RAFAUT_BLG66}',
										['num'] = 2,
									},
									[4] = {
										['CLSID'] = '{BLG66_BELOUGA_AC}',
										['num'] = 4,
									},
									[8] = {
										['CLSID'] = '{M2KC_RAFAUT_BLG66}',
										['num'] = 8,
									},
									[9] = {
										['CLSID'] = '{MMagicII}',
										['num'] = 9,
									},
									[5] = {
										['CLSID'] = '{M2KC_RPL_522}',
										['num'] = 5,
									},
									[3] = {
										['CLSID'] = '{BLG66_BELOUGA_AC}',
										['num'] = 3,
									},
									[6] = {
										['CLSID'] = '{BLG66_BELOUGA_AC}',
										['num'] = 6,
									},
								},
								['fuel'] = 3165,
								['flare'] = 48,
								['chaff'] = 112,
								['gun'] = 100,
							},
							['onboard_num'] = '099',
							['type'] = 'M-2000C',
							['unitId'] = 100022,
							['parking_id'] = '24',
						},
						[2] = {
							['alt'] = 621.6,
							['hardpoint_racks'] = true,
							['alt_type'] = 'RADIO',
							['livery_id'] = 'Greek Air Force',
							['skill'] = 'Excellent',
							['speed'] = 183.75,
							['heading'] = 0,
							['Radio'] = {
								[1] = {
									['channels'] = {
									},
								},
								[2] = {
									['channels'] = {
									},
								},
							},
							['callsign'] = {
								[1] = 6,
								[2] = 7,
								['name'] = 'Ford72',
								[3] = 2,
							},
							['psi'] = 0,
							['y'] = -314108.375,
							['x'] = -18596.34668,
							['name'] = 'Pack 1 - EC 331 - Strike 1-2',
							['payload'] = {
								['pylons'] = {
									[7] = {
										['CLSID'] = '{BLG66_BELOUGA_AC}',
										['num'] = 7,
									},
									[1] = {
										['CLSID'] = '{MMagicII}',
										['num'] = 1,
									},
									[2] = {
										['CLSID'] = '{M2KC_RAFAUT_BLG66}',
										['num'] = 2,
									},
									[4] = {
										['CLSID'] = '{BLG66_BELOUGA_AC}',
										['num'] = 4,
									},
									[8] = {
										['CLSID'] = '{M2KC_RAFAUT_BLG66}',
										['num'] = 8,
									},
									[9] = {
										['CLSID'] = '{MMagicII}',
										['num'] = 9,
									},
									[5] = {
										['CLSID'] = '{M2KC_RPL_522}',
										['num'] = 5,
									},
									[3] = {
										['CLSID'] = '{BLG66_BELOUGA_AC}',
										['num'] = 3,
									},
									[6] = {
										['CLSID'] = '{BLG66_BELOUGA_AC}',
										['num'] = 6,
									},
								},
								['fuel'] = 3165,
								['flare'] = 48,
								['chaff'] = 112,
								['gun'] = 100,
							},
							['onboard_num'] = '049',
							['type'] = 'M-2000C',
							['unitId'] = 100023,
							['parking_id'] = '37',
						},
					},
					['parking_id'] = {
						[''] = {
							[1] = 23,
							[2] = 24,
							[3] = 25,
							[4] = 26,
							[5] = 27,
							[6] = 28,
							[7] = 29,
							[8] = 30,
							[9] = 31,
							[10] = 32,
							[11] = 33,
							[12] = 34,
							[13] = 35,
							[14] = 36,
							[15] = 37,
						},
					},
					['player'] = true,
					['target_name'] = 'North Cyprus-Turkish Force 1',
					['target'] = {
						['x'] = 24964.948880636,
						['elements'] = {
							[1] = {
								['y'] = -241772.17653267,
								['x'] = 24832.020004365,
								['name'] = 'NCTF 1-1',
								['dead_last'] = false,
								['foundOobGround'] = true,
								['groupId'] = 222,
							},
							[2] = {
								['y'] = -241667.1524011,
								['x'] = 24764.675291289,
								['name'] = 'NCTF 1-2',
								['dead_last'] = false,
								['foundOobGround'] = true,
								['groupId'] = 223,
							},
							[3] = {
								['y'] = -241601.45468383,
								['x'] = 24721.500846477,
								['name'] = 'NCTF 1-3',
								['dead_last'] = false,
								['foundOobGround'] = true,
								['groupId'] = 224,
							},
							[4] = {
								['y'] = -241528.14145356,
								['x'] = 24676.125588337,
								['name'] = 'NCTF 1-4',
								['dead_last'] = false,
								['foundOobGround'] = true,
								['groupId'] = 225,
							},
							[5] = {
								['y'] = -241439.63699835,
								['x'] = 24626.014552287,
								['name'] = 'NCTF 1-5',
								['dead_last'] = false,
								['foundOobGround'] = true,
								['groupId'] = 226,
							},
							[6] = {
								['y'] = -241274.56409406,
								['x'] = 24549.347563773,
								['name'] = 'NCTF 1-6',
								['dead_last'] = false,
								['foundOobGround'] = true,
								['groupId'] = 227,
							},
							[7] = {
								['name'] = 'NCTF 1-7',
								['groupId'] = 228,
								['dead_last'] = false,
								['foundOobGround'] = true,
								['dead'] = true,
							},
							[8] = {
								['name'] = 'NCTF 1-8',
								['groupId'] = 229,
								['dead_last'] = false,
								['foundOobGround'] = true,
								['dead'] = true,
							},
							[9] = {
								['name'] = 'NCTF 1-9',
								['groupId'] = 230,
								['dead_last'] = false,
								['foundOobGround'] = true,
								['dead'] = true,
							},
							[10] = {
								['name'] = 'NCTF 1-10',
								['groupId'] = 231,
								['dead_last'] = false,
								['foundOobGround'] = true,
								['dead'] = true,
							},
							[11] = {
								['name'] = 'NCTF 1-11',
								['groupId'] = 232,
								['dead_last'] = true,
								['foundOobGround'] = true,
								['dead'] = true,
							},
							[12] = {
								['y'] = -240549.69737728,
								['x'] = 24409.897452375,
								['name'] = 'NCTF 1-12',
								['dead_last'] = false,
								['foundOobGround'] = true,
								['groupId'] = 233,
							},
							[13] = {
								['y'] = -240432.66415202,
								['x'] = 24393.080478573,
								['name'] = 'NCTF 1-13',
								['dead_last'] = false,
								['foundOobGround'] = true,
								['groupId'] = 234,
							},
							[14] = {
								['y'] = -240268.08823817,
								['x'] = 24371.175216749,
								['name'] = 'NCTF 1-14',
								['dead_last'] = false,
								['foundOobGround'] = true,
								['groupId'] = 235,
							},
							[15] = {
								['y'] = -240177.81900988,
								['x'] = 24357.53205647,
								['name'] = 'NCTF 1-15',
								['dead_last'] = false,
								['foundOobGround'] = true,
								['groupId'] = 236,
							},
							[16] = {
								['y'] = -240351.46731523,
								['x'] = 24382.136191168,
								['name'] = 'NCTF 1-16',
								['dead_last'] = false,
								['foundOobGround'] = true,
								['groupId'] = 237,
							},
							[17] = {
								['y'] = -239538.25583204,
								['x'] = 24093.218722443,
								['name'] = 'NCTF 1-17',
								['dead_last'] = false,
								['foundOobGround'] = true,
								['groupId'] = 238,
							},
							[18] = {
								['y'] = -239458.24195701,
								['x'] = 24036.474847986,
								['name'] = 'NCTF 1-18',
								['dead_last'] = false,
								['foundOobGround'] = true,
								['groupId'] = 239,
							},
							[19] = {
								['y'] = -240077.30057745,
								['x'] = 24338.178489128,
								['name'] = 'NCTF 1-19',
								['dead_last'] = false,
								['foundOobGround'] = true,
								['groupId'] = 240,
							},
							[20] = {
								['y'] = -239628.54452516,
								['x'] = 24156.107667655,
								['name'] = 'NCTF 1-20',
								['dead_last'] = false,
								['foundOobGround'] = true,
								['groupId'] = 241,
							},
							[21] = {
								['y'] = -239742.60724745,
								['x'] = 24220.65736973,
								['name'] = 'NCTF 1-21',
								['dead_last'] = false,
								['foundOobGround'] = true,
								['groupId'] = 242,
							},
							[22] = {
								['y'] = -239826.99698506,
								['x'] = 24259.965759747,
								['name'] = 'NCTF 1-22',
								['dead_last'] = false,
								['foundOobGround'] = true,
								['groupId'] = 243,
							},
							[23] = {
								['y'] = -240007.51057601,
								['x'] = 24320.919896945,
								['name'] = 'NCTF 1-23',
								['dead_last'] = false,
								['foundOobGround'] = true,
								['groupId'] = 244,
							},
							[24] = {
								['y'] = -239924.46180264,
								['x'] = 24295.585432035,
								['name'] = 'NCTF 1-24',
								['dead_last'] = false,
								['foundOobGround'] = true,
								['groupId'] = 245,
							},
						},
						['picture'] = {
							[1] = 'NCTF-1.png',
						},
						['task'] = 'Strike',
						['class'] = 'static',
						['ATO'] = true,
						['firepower'] = {
							['min'] = 2,
							['max'] = 6,
						},
						['y'] = -233392.0156654,
						['inactive'] = false,
						['attributes'] = {
							[1] = 'soft',
						},
						['dead_last'] = 4,
						['alive'] = 79,
						['priority'] = 18,
						['foundOobGround'] = true,
						['TitleName'] = 'North Cyprus-Turkish Force 1',
					},
					['name'] = 'EC 331',
					['callsignId'] = 6,
					['tot_from'] = 0,
					['frequency'] = 322.9,
				},
			},
			['Laser Illumination'] = {
			},
			['SEAD'] = {
			},
			['Escort'] = {
			},
			['Escort Jammer'] = {
			},
		},
		['side'] = 'blue',
		['group'] = {
			['uncontrolled'] = false,
			['taskSelected'] = true,
			['modulation'] = 0,
			['groupId'] = 100024,
			['tasks'] = {
			},
			['route'] = {
				['points'] = {
					[1] = {
						['speed_locked'] = true,
						['briefing_name'] = 'Departure',
						['action'] = 'From Parking Area',
						['alt_type'] = 'RADIO',
						['properties'] = {
							['vnav'] = 1,
							['scale'] = 0,
							['angle'] = 0,
							['vangle'] = 0,
							['steer'] = 2,
						},
						['speed'] = 183.75,
						['task'] = {
							['id'] = 'ComboTask',
							['params'] = {
								['tasks'] = {
									[1] = {
										['number'] = 1,
										['auto'] = false,
										['id'] = 'WrappedAction',
										['enabled'] = true,
										['params'] = {
											['action'] = {
												['id'] = 'Option',
												['params'] = {
													['variantIndex'] = 1,
													['value'] = 458753,
													['name'] = 5,
													['formationIndex'] = 7,
												},
											},
										},
									},
									[2] = {
										['enabled'] = true,
										['auto'] = false,
										['id'] = 'WrappedAction',
										['number'] = 2,
										['params'] = {
											['action'] = {
												['id'] = 'Script',
												['params'] = {
													['command'] = 'OrbitPosition("Pack 1 - EC 331 - Strike 1", 621.6, 163.33333333333, 900)',
												},
											},
										},
									},
									[3] = {
										['number'] = 3,
										['auto'] = false,
										['id'] = 'WrappedAction',
										['enabled'] = true,
										['params'] = {
											['action'] = {
												['id'] = 'Option',
												['params'] = {
													['value'] = 2,
													['name'] = 1,
												},
											},
										},
									},
									[4] = {
										['enabled'] = true,
										['auto'] = false,
										['id'] = 'WrappedAction',
										['number'] = 4,
										['params'] = {
											['action'] = {
												['id'] = 'Option',
												['params'] = {
													['value'] = true,
													['name'] = 15,
												},
											},
										},
									},
								},
							},
						},
						['type'] = 'TakeOffParking',
						['ETA'] = 0,
						['ETA_locked'] = true,
						['y'] = -314208.375,
						['x'] = -18696.34668,
						['name'] = 'Departure',
						['alt'] = 621.6,
						['airdromeId'] = 46,
						['formation_template'] = '',
					},
					[2] = {
						['speed_locked'] = true,
						['briefing_name'] = 'Join',
						['action'] = 'Turning Point',
						['alt_type'] = 'RADIO',
						['properties'] = {
							['vnav'] = 1,
							['scale'] = 0,
							['angle'] = 0,
							['vangle'] = 0,
							['steer'] = 2,
						},
						['speed'] = 183.75,
						['task'] = {
							['id'] = 'ComboTask',
							['params'] = {
								['tasks'] = {
								},
							},
						},
						['type'] = 'Turning Point',
						['ETA'] = 981.63265306122,
						['ETA_locked'] = false,
						['hCruiseREF'] = 300.4,
						['y'] = -301011.1912539,
						['x'] = -11566.526123237,
						['name'] = 'Join   057  /   16 KM /   1 mn',
						['alt'] = 300.4,
						['formation_template'] = '',
					},
					[3] = {
						['alt'] = 300.4,
						['briefing_name'] = 'Nav',
						['action'] = 'Turning Point',
						['alt_type'] = 'RADIO',
						['properties'] = {
							['vnav'] = 1,
							['scale'] = 0,
							['angle'] = 0,
							['vangle'] = 0,
							['steer'] = 2,
						},
						['speed_locked'] = true,
						['ETA'] = 1163.3019174021,
						['y'] = -261851.65443265,
						['formation_template'] = '',
						['name'] = 'Nav    057  /   45 KM /   3 mn',
						['ETA_locked'] = false,
						['speed'] = 245,
						['x'] = 9589.5383821139,
						['task'] = {
							['id'] = 'ComboTask',
							['params'] = {
								['tasks'] = {
								},
							},
						},
						['type'] = 'Turning Point',
					},
					[4] = {
						['alt'] = 200,
						['briefing_name'] = 'IP',
						['action'] = 'Turning Point',
						['alt_type'] = 'RADIO',
						['properties'] = {
							['vnav'] = 1,
							['scale'] = 0,
							['angle'] = 0,
							['vangle'] = 0,
							['steer'] = 2,
						},
						['speed_locked'] = true,
						['ETA'] = 1165.7606929123,
						['y'] = -261321.6555334,
						['formation_template'] = '',
						['name'] = 'IP     057  /    1 KM /   0 mn',
						['ETA_locked'] = false,
						['speed'] = 245,
						['x'] = 9875.8719756735,
						['task'] = {
							['id'] = 'ComboTask',
							['params'] = {
								['tasks'] = {
									[1] = {
										['enabled'] = true,
										['auto'] = false,
										['id'] = 'Bombing',
										['number'] = 1,
										['params'] = {
											['groupAttack'] = false,
											['attackQtyLimit'] = true,
											['attackQty'] = 1,
											['direction'] = 0,
											['y'] = -241772.17653267,
											['x'] = 24832.020004365,
											['directionEnabled'] = false,
											['altitude'] = 200,
											['altitudeEnabled'] = true,
											['altitudeEdited'] = true,
											['weaponType'] = 2032,
											['attackType'] = 'nil',
										},
									},
									[2] = {
										['enabled'] = true,
										['auto'] = false,
										['id'] = 'Bombing',
										['number'] = 2,
										['params'] = {
											['groupAttack'] = false,
											['attackQtyLimit'] = true,
											['attackQty'] = 1,
											['direction'] = 0,
											['y'] = -241667.1524011,
											['x'] = 24764.675291289,
											['directionEnabled'] = false,
											['altitude'] = 200,
											['altitudeEnabled'] = true,
											['altitudeEdited'] = true,
											['weaponType'] = 2032,
											['attackType'] = 'nil',
										},
									},
									[3] = {
										['enabled'] = true,
										['auto'] = false,
										['id'] = 'Bombing',
										['number'] = 3,
										['params'] = {
											['groupAttack'] = false,
											['attackQtyLimit'] = true,
											['attackQty'] = 1,
											['direction'] = 0,
											['y'] = -241601.45468383,
											['x'] = 24721.500846477,
											['directionEnabled'] = false,
											['altitude'] = 200,
											['altitudeEnabled'] = true,
											['altitudeEdited'] = true,
											['weaponType'] = 2032,
											['attackType'] = 'nil',
										},
									},
									[4] = {
										['enabled'] = true,
										['auto'] = false,
										['id'] = 'Bombing',
										['number'] = 4,
										['params'] = {
											['groupAttack'] = false,
											['attackQtyLimit'] = true,
											['attackQty'] = 1,
											['direction'] = 0,
											['y'] = -241528.14145356,
											['x'] = 24676.125588337,
											['directionEnabled'] = false,
											['altitude'] = 200,
											['altitudeEnabled'] = true,
											['altitudeEdited'] = true,
											['weaponType'] = 2032,
											['attackType'] = 'nil',
										},
									},
									[5] = {
										['enabled'] = true,
										['auto'] = false,
										['id'] = 'Bombing',
										['number'] = 5,
										['params'] = {
											['groupAttack'] = false,
											['attackQtyLimit'] = true,
											['attackQty'] = 1,
											['direction'] = 0,
											['y'] = -241439.63699835,
											['x'] = 24626.014552287,
											['directionEnabled'] = false,
											['altitude'] = 200,
											['altitudeEnabled'] = true,
											['altitudeEdited'] = true,
											['weaponType'] = 2032,
											['attackType'] = 'nil',
										},
									},
									[6] = {
										['enabled'] = true,
										['auto'] = false,
										['id'] = 'Bombing',
										['number'] = 6,
										['params'] = {
											['groupAttack'] = false,
											['attackQtyLimit'] = true,
											['attackQty'] = 1,
											['direction'] = 0,
											['y'] = -241274.56409406,
											['x'] = 24549.347563773,
											['directionEnabled'] = false,
											['altitude'] = 200,
											['altitudeEnabled'] = true,
											['altitudeEdited'] = true,
											['weaponType'] = 2032,
											['attackType'] = 'nil',
										},
									},
									[7] = {
										['enabled'] = true,
										['auto'] = false,
										['id'] = 'Bombing',
										['number'] = 7,
										['params'] = {
											['groupAttack'] = false,
											['attackQtyLimit'] = true,
											['attackQty'] = 1,
											['direction'] = 0,
											['y'] = -240549.69737728,
											['x'] = 24409.897452375,
											['directionEnabled'] = false,
											['altitude'] = 200,
											['altitudeEnabled'] = true,
											['altitudeEdited'] = true,
											['weaponType'] = 2032,
											['attackType'] = 'nil',
										},
									},
									[8] = {
										['enabled'] = true,
										['auto'] = false,
										['id'] = 'Bombing',
										['number'] = 8,
										['params'] = {
											['groupAttack'] = false,
											['attackQtyLimit'] = true,
											['attackQty'] = 1,
											['direction'] = 0,
											['y'] = -240432.66415202,
											['x'] = 24393.080478573,
											['directionEnabled'] = false,
											['altitude'] = 200,
											['altitudeEnabled'] = true,
											['altitudeEdited'] = true,
											['weaponType'] = 2032,
											['attackType'] = 'nil',
										},
									},
									[9] = {
										['enabled'] = true,
										['auto'] = false,
										['id'] = 'Bombing',
										['number'] = 9,
										['params'] = {
											['groupAttack'] = false,
											['attackQtyLimit'] = true,
											['attackQty'] = 1,
											['direction'] = 0,
											['y'] = -240268.08823817,
											['x'] = 24371.175216749,
											['directionEnabled'] = false,
											['altitude'] = 200,
											['altitudeEnabled'] = true,
											['altitudeEdited'] = true,
											['weaponType'] = 2032,
											['attackType'] = 'nil',
										},
									},
									[10] = {
										['enabled'] = true,
										['auto'] = false,
										['id'] = 'Bombing',
										['number'] = 10,
										['params'] = {
											['groupAttack'] = false,
											['attackQtyLimit'] = true,
											['attackQty'] = 1,
											['direction'] = 0,
											['y'] = -240177.81900988,
											['x'] = 24357.53205647,
											['directionEnabled'] = false,
											['altitude'] = 200,
											['altitudeEnabled'] = true,
											['altitudeEdited'] = true,
											['weaponType'] = 2032,
											['attackType'] = 'nil',
										},
									},
									[11] = {
										['enabled'] = true,
										['auto'] = false,
										['id'] = 'Bombing',
										['number'] = 11,
										['params'] = {
											['groupAttack'] = false,
											['attackQtyLimit'] = true,
											['attackQty'] = 1,
											['direction'] = 0,
											['y'] = -240351.46731523,
											['x'] = 24382.136191168,
											['directionEnabled'] = false,
											['altitude'] = 200,
											['altitudeEnabled'] = true,
											['altitudeEdited'] = true,
											['weaponType'] = 2032,
											['attackType'] = 'nil',
										},
									},
									[12] = {
										['enabled'] = true,
										['auto'] = false,
										['id'] = 'Bombing',
										['number'] = 12,
										['params'] = {
											['groupAttack'] = false,
											['attackQtyLimit'] = true,
											['attackQty'] = 1,
											['direction'] = 0,
											['y'] = -239538.25583204,
											['x'] = 24093.218722443,
											['directionEnabled'] = false,
											['altitude'] = 200,
											['altitudeEnabled'] = true,
											['altitudeEdited'] = true,
											['weaponType'] = 2032,
											['attackType'] = 'nil',
										},
									},
									[13] = {
										['enabled'] = true,
										['auto'] = false,
										['id'] = 'Bombing',
										['number'] = 13,
										['params'] = {
											['groupAttack'] = false,
											['attackQtyLimit'] = true,
											['attackQty'] = 1,
											['direction'] = 0,
											['y'] = -239458.24195701,
											['x'] = 24036.474847986,
											['directionEnabled'] = false,
											['altitude'] = 200,
											['altitudeEnabled'] = true,
											['altitudeEdited'] = true,
											['weaponType'] = 2032,
											['attackType'] = 'nil',
										},
									},
									[14] = {
										['enabled'] = true,
										['auto'] = false,
										['id'] = 'Bombing',
										['number'] = 14,
										['params'] = {
											['groupAttack'] = false,
											['attackQtyLimit'] = true,
											['attackQty'] = 1,
											['direction'] = 0,
											['y'] = -240077.30057745,
											['x'] = 24338.178489128,
											['directionEnabled'] = false,
											['altitude'] = 200,
											['altitudeEnabled'] = true,
											['altitudeEdited'] = true,
											['weaponType'] = 2032,
											['attackType'] = 'nil',
										},
									},
									[15] = {
										['enabled'] = true,
										['auto'] = false,
										['id'] = 'Bombing',
										['number'] = 15,
										['params'] = {
											['groupAttack'] = false,
											['attackQtyLimit'] = true,
											['attackQty'] = 1,
											['direction'] = 0,
											['y'] = -239628.54452516,
											['x'] = 24156.107667655,
											['directionEnabled'] = false,
											['altitude'] = 200,
											['altitudeEnabled'] = true,
											['altitudeEdited'] = true,
											['weaponType'] = 2032,
											['attackType'] = 'nil',
										},
									},
									[16] = {
										['enabled'] = true,
										['auto'] = false,
										['id'] = 'Bombing',
										['number'] = 16,
										['params'] = {
											['groupAttack'] = false,
											['attackQtyLimit'] = true,
											['attackQty'] = 1,
											['direction'] = 0,
											['y'] = -239742.60724745,
											['x'] = 24220.65736973,
											['directionEnabled'] = false,
											['altitude'] = 200,
											['altitudeEnabled'] = true,
											['altitudeEdited'] = true,
											['weaponType'] = 2032,
											['attackType'] = 'nil',
										},
									},
									[17] = {
										['enabled'] = true,
										['auto'] = false,
										['id'] = 'Bombing',
										['number'] = 17,
										['params'] = {
											['groupAttack'] = false,
											['attackQtyLimit'] = true,
											['attackQty'] = 1,
											['direction'] = 0,
											['y'] = -239826.99698506,
											['x'] = 24259.965759747,
											['directionEnabled'] = false,
											['altitude'] = 200,
											['altitudeEnabled'] = true,
											['altitudeEdited'] = true,
											['weaponType'] = 2032,
											['attackType'] = 'nil',
										},
									},
									[18] = {
										['enabled'] = true,
										['auto'] = false,
										['id'] = 'Bombing',
										['number'] = 18,
										['params'] = {
											['groupAttack'] = false,
											['attackQtyLimit'] = true,
											['attackQty'] = 1,
											['direction'] = 0,
											['y'] = -240007.51057601,
											['x'] = 24320.919896945,
											['directionEnabled'] = false,
											['altitude'] = 200,
											['altitudeEnabled'] = true,
											['altitudeEdited'] = true,
											['weaponType'] = 2032,
											['attackType'] = 'nil',
										},
									},
									[19] = {
										['enabled'] = true,
										['auto'] = false,
										['id'] = 'Bombing',
										['number'] = 19,
										['params'] = {
											['groupAttack'] = false,
											['attackQtyLimit'] = true,
											['attackQty'] = 1,
											['direction'] = 0,
											['y'] = -239924.46180264,
											['x'] = 24295.585432035,
											['directionEnabled'] = false,
											['altitude'] = 200,
											['altitudeEnabled'] = true,
											['altitudeEdited'] = true,
											['weaponType'] = 2032,
											['attackType'] = 'nil',
										},
									},
								},
							},
						},
						['type'] = 'Turning Point',
					},
					[5] = {
						['alt'] = 0,
						['briefing_name'] = 'Target',
						['action'] = 'Turning Point',
						['alt_type'] = 'RADIO',
						['properties'] = {
							['vnav'] = 1,
							['scale'] = 0,
							['angle'] = 0,
							['vangle'] = 0,
							['steer'] = 2,
						},
						['speed_locked'] = false,
						['ETA'] = 1256.3313063217,
						['y'] = -233392.0156654,
						['formation_template'] = '',
						['name'] = 'Target 057  /   32 KM /   1 mn',
						['ETA_locked'] = true,
						['speed'] = 350.5,
						['x'] = 24964.948880636,
						['task'] = {
							['id'] = 'ComboTask',
							['params'] = {
								['tasks'] = {
								},
							},
						},
						['type'] = 'Turning Point',
					},
					[6] = {
						['alt'] = 200,
						['briefing_name'] = 'Egress',
						['action'] = 'Turning Point',
						['alt_type'] = 'RADIO',
						['properties'] = {
							['vnav'] = 1,
							['scale'] = 0,
							['angle'] = 0,
							['vangle'] = 0,
							['steer'] = 2,
						},
						['speed_locked'] = true,
						['ETA'] = 1376.9019197311,
						['y'] = -253479.09678066,
						['formation_template'] = '',
						['name'] = 'Egress 327  /   43 KM /   2 mn',
						['ETA_locked'] = false,
						['speed'] = 350.5,
						['x'] = 62145.814554652,
						['task'] = {
							['id'] = 'ComboTask',
							['params'] = {
								['tasks'] = {
									[1] = {
										['enabled'] = true,
										['auto'] = false,
										['id'] = 'WrappedAction',
										['number'] = 1,
										['params'] = {
											['action'] = {
												['id'] = 'Script',
												['params'] = {
													['command'] = 'CustomRejoin("Pack 1 - EC 331 - Strike 1")',
												},
											},
										},
									},
								},
							},
						},
						['type'] = 'Turning Point',
					},
					[7] = {
						['alt'] = 300.4,
						['briefing_name'] = 'Nav',
						['action'] = 'Turning Point',
						['alt_type'] = 'RADIO',
						['properties'] = {
							['vnav'] = 1,
							['scale'] = 0,
							['angle'] = 0,
							['vangle'] = 0,
							['steer'] = 2,
						},
						['speed_locked'] = true,
						['ETA'] = 1380.9998789148,
						['y'] = -254082.11721054,
						['formation_template'] = '',
						['name'] = 'Nav    212  /    2 KM /   0 mn',
						['ETA_locked'] = false,
						['speed'] = 245,
						['x'] = 61343.080251696,
						['task'] = {
							['id'] = 'ComboTask',
							['params'] = {
								['tasks'] = {
								},
							},
						},
						['type'] = 'Turning Point',
					},
					[8] = {
						['alt'] = 300.4,
						['briefing_name'] = 'Split',
						['action'] = 'Turning Point',
						['alt_type'] = 'RADIO',
						['properties'] = {
							['vnav'] = 1,
							['scale'] = 0,
							['angle'] = 0,
							['vangle'] = 0,
							['steer'] = 2,
						},
						['speed_locked'] = true,
						['ETA'] = 1728.376720148,
						['y'] = -305199.10562923,
						['formation_template'] = '',
						['name'] = 'Split  212  /   86 KM /   6 mn',
						['ETA_locked'] = false,
						['speed'] = 245,
						['x'] = -6703.3043051537,
						['task'] = {
							['id'] = 'ComboTask',
							['params'] = {
								['tasks'] = {
								},
							},
						},
						['type'] = 'Turning Point',
					},
					[9] = {
						['speed_locked'] = true,
						['briefing_name'] = 'Land',
						['action'] = 'Landing',
						['alt_type'] = 'RADIO',
						['properties'] = {
							['vnav'] = 1,
							['scale'] = 0,
							['angle'] = 0,
							['vangle'] = 0,
							['steer'] = 2,
						},
						['speed'] = 245,
						['task'] = {
							['id'] = 'ComboTask',
							['params'] = {
								['tasks'] = {
								},
							},
						},
						['type'] = 'Land',
						['ETA'] = 1789.6012099439,
						['ETA_locked'] = false,
						['y'] = -314208.375,
						['x'] = -18696.34668,
						['name'] = 'Land   212  /   16 KM /   1 mn',
						['airdromeId'] = 46,
						['TotFlightTime'] = ' 00:14',
						['alt'] = 12,
						['TotFlightDist'] = '263 KM',
						['formation_template'] = '',
					},
				},
			},
			['hidden'] = false,
			['units'] = {
				[1] = {
					['alt'] = 621.6,
					['hardpoint_racks'] = true,
					['alt_type'] = 'RADIO',
					['livery_id'] = 'Greek Air Force',
					['skill'] = 'Player',
					['speed'] = 183.75,
					['heading'] = 0,
					['Radio'] = {
						[1] = {
							['channels'] = {
								[1] = 322.9,
							},
						},
						[2] = {
							['channels'] = {
								[1] = 251.8,
								[2] = 295.05,
								[3] = 251.8,
								[4] = 129.5,
								[5] = 251.9,
								[6] = 322.9,
							},
						},
					},
					['callsign'] = {
						[1] = 6,
						[2] = 7,
						['name'] = 'Ford71',
						[3] = 1,
					},
					['psi'] = 0,
					['y'] = -314208.375,
					['x'] = -18696.34668,
					['name'] = 'Pack 1 - EC 331 - Strike 1-1',
					['payload'] = {
						['pylons'] = {
							[7] = {
								['CLSID'] = '{BLG66_BELOUGA_AC}',
								['num'] = 7,
							},
							[1] = {
								['CLSID'] = '{MMagicII}',
								['num'] = 1,
							},
							[2] = {
								['CLSID'] = '{M2KC_RAFAUT_BLG66}',
								['num'] = 2,
							},
							[4] = {
								['CLSID'] = '{BLG66_BELOUGA_AC}',
								['num'] = 4,
							},
							[8] = {
								['CLSID'] = '{M2KC_RAFAUT_BLG66}',
								['num'] = 8,
							},
							[9] = {
								['CLSID'] = '{MMagicII}',
								['num'] = 9,
							},
							[5] = {
								['CLSID'] = '{M2KC_RPL_522}',
								['num'] = 5,
							},
							[3] = {
								['CLSID'] = '{BLG66_BELOUGA_AC}',
								['num'] = 3,
							},
							[6] = {
								['CLSID'] = '{BLG66_BELOUGA_AC}',
								['num'] = 6,
							},
						},
						['fuel'] = 3165,
						['flare'] = 48,
						['chaff'] = 112,
						['gun'] = 100,
					},
					['onboard_num'] = '099',
					['type'] = 'M-2000C',
					['unitId'] = 100022,
					['parking_id'] = '24',
				},
				[2] = {
					['alt'] = 621.6,
					['hardpoint_racks'] = true,
					['alt_type'] = 'RADIO',
					['livery_id'] = 'Greek Air Force',
					['skill'] = 'Excellent',
					['speed'] = 183.75,
					['heading'] = 0,
					['Radio'] = {
						[1] = {
							['channels'] = {
							},
						},
						[2] = {
							['channels'] = {
							},
						},
					},
					['callsign'] = {
						[1] = 6,
						[2] = 7,
						['name'] = 'Ford72',
						[3] = 2,
					},
					['psi'] = 0,
					['y'] = -314108.375,
					['x'] = -18596.34668,
					['name'] = 'Pack 1 - EC 331 - Strike 1-2',
					['payload'] = {
						['pylons'] = {
							[7] = {
								['CLSID'] = '{BLG66_BELOUGA_AC}',
								['num'] = 7,
							},
							[1] = {
								['CLSID'] = '{MMagicII}',
								['num'] = 1,
							},
							[2] = {
								['CLSID'] = '{M2KC_RAFAUT_BLG66}',
								['num'] = 2,
							},
							[4] = {
								['CLSID'] = '{BLG66_BELOUGA_AC}',
								['num'] = 4,
							},
							[8] = {
								['CLSID'] = '{M2KC_RAFAUT_BLG66}',
								['num'] = 8,
							},
							[9] = {
								['CLSID'] = '{MMagicII}',
								['num'] = 9,
							},
							[5] = {
								['CLSID'] = '{M2KC_RPL_522}',
								['num'] = 5,
							},
							[3] = {
								['CLSID'] = '{BLG66_BELOUGA_AC}',
								['num'] = 3,
							},
							[6] = {
								['CLSID'] = '{BLG66_BELOUGA_AC}',
								['num'] = 6,
							},
						},
						['fuel'] = 3165,
						['flare'] = 48,
						['chaff'] = 112,
						['gun'] = 100,
					},
					['onboard_num'] = '049',
					['type'] = 'M-2000C',
					['unitId'] = 100023,
					['parking_id'] = '37',
				},
			},
			['y'] = -314208.375,
			['radioSet'] = true,
			['name'] = 'Pack 1 - EC 331 - Strike 1',
			['communication'] = true,
			['x'] = -18696.34668,
			['start_time'] = 1,
			['task'] = 'CAS',
			['frequency'] = 322.9,
		},
		['flight'] = 1,
		['role'] = 'main',
		['waypoints'] = {
			[1] = {
				['speed_locked'] = true,
				['airdromeId'] = 46,
				['ETA'] = 0,
				['alt_type'] = 'RADIO',
				['type'] = 'TakeOffParking',
				['properties'] = {
					['vnav'] = 1,
					['scale'] = 0,
					['vangle'] = 0,
					['angle'] = 0,
					['steer'] = 2,
				},
				['briefing_name'] = 'Taxi',
				['x'] = -18696.34668,
				['y'] = -314208.375,
				['formation_template'] = '',
				['name'] = 'Taxi',
				['ETA_locked'] = true,
				['speed'] = 245,
				['alt'] = 0,
				['task'] = {
					['id'] = 'ComboTask',
					['params'] = {
						['tasks'] = {
						},
					},
				},
				['action'] = 'From Parking Area',
			},
			[2] = {
				['speed_locked'] = true,
				['briefing_name'] = 'Departure',
				['ETA'] = 900,
				['alt_type'] = 'RADIO',
				['properties'] = {
					['vnav'] = 1,
					['scale'] = 0,
					['vangle'] = 0,
					['angle'] = 0,
					['steer'] = 2,
				},
				['type'] = 'Turning Point',
				['alt'] = 0,
				['y'] = -314208.375,
				['formation_template'] = '',
				['name'] = 'Departure',
				['x'] = -18696.34668,
				['speed'] = 0,
				['ETA_locked'] = false,
				['task'] = {
					['id'] = 'ComboTask',
					['params'] = {
						['tasks'] = {
							[1] = {
								['enabled'] = true,
								['auto'] = false,
								['id'] = 'WrappedAction',
								['number'] = 1,
								['params'] = {
									['action'] = {
										['id'] = 'Option',
										['params'] = {
											['value'] = 458753,
											['variantIndex'] = 1,
											['name'] = 5,
											['formationIndex'] = 7,
										},
									},
								},
							},
							[2] = {
								['number'] = 2,
								['auto'] = false,
								['id'] = 'WrappedAction',
								['enabled'] = true,
								['params'] = {
									['action'] = {
										['id'] = 'Script',
										['params'] = {
											['command'] = 'OrbitPosition("Pack 1 - EC 331 - Strike 1", 621.6, 163.33333333333, 900)',
										},
									},
								},
							},
						},
					},
				},
				['action'] = 'Turning Point',
			},
			[3] = {
				['speed_locked'] = true,
				['type'] = 'Turning Point',
				['action'] = 'Turning Point',
				['alt_type'] = 'RADIO',
				['formation_template'] = '',
				['properties'] = {
					['vnav'] = 1,
					['scale'] = 0,
					['vangle'] = 0,
					['angle'] = 0,
					['steer'] = 2,
				},
				['alt'] = 300.4,
				['hCruiseREF'] = 300.4,
				['y'] = -301011.1912539,
				['x'] = -11566.526123237,
				['name'] = 'Join   057  /   16 KM /   1 mn',
				['ETA_locked'] = false,
				['speed'] = 183.75,
				['ETA'] = 981.63265306122,
				['task'] = {
					['id'] = 'ComboTask',
					['params'] = {
						['tasks'] = {
						},
					},
				},
				['briefing_name'] = 'Join',
			},
			[4] = {
				['speed_locked'] = true,
				['briefing_name'] = 'Nav',
				['ETA'] = 1163.3019174021,
				['alt_type'] = 'RADIO',
				['properties'] = {
					['vnav'] = 1,
					['scale'] = 0,
					['vangle'] = 0,
					['angle'] = 0,
					['steer'] = 2,
				},
				['type'] = 'Turning Point',
				['alt'] = 300.4,
				['y'] = -261851.65443265,
				['formation_template'] = '',
				['name'] = 'Nav    057  /   45 KM /   3 mn',
				['x'] = 9589.5383821139,
				['speed'] = 245,
				['ETA_locked'] = false,
				['task'] = {
					['id'] = 'ComboTask',
					['params'] = {
						['tasks'] = {
						},
					},
				},
				['action'] = 'Turning Point',
			},
			[5] = {
				['speed_locked'] = true,
				['briefing_name'] = 'IP',
				['ETA'] = 1165.7606929123,
				['alt_type'] = 'RADIO',
				['properties'] = {
					['vnav'] = 1,
					['scale'] = 0,
					['vangle'] = 0,
					['angle'] = 0,
					['steer'] = 2,
				},
				['type'] = 'Turning Point',
				['alt'] = 200,
				['y'] = -261321.6555334,
				['formation_template'] = '',
				['name'] = 'IP     057  /    1 KM /   0 mn',
				['x'] = 9875.8719756735,
				['speed'] = 245,
				['ETA_locked'] = false,
				['task'] = {
					['id'] = 'ComboTask',
					['params'] = {
						['tasks'] = {
							[1] = {
								['number'] = 1,
								['auto'] = false,
								['id'] = 'Bombing',
								['enabled'] = true,
								['params'] = {
									['groupAttack'] = false,
									['attackQtyLimit'] = true,
									['attackQty'] = 1,
									['attackType'] = 'nil',
									['altitude'] = 200,
									['x'] = 24832.020004365,
									['direction'] = 0,
									['altitudeEdited'] = true,
									['altitudeEnabled'] = true,
									['y'] = -241772.17653267,
									['weaponType'] = 2032,
									['directionEnabled'] = false,
								},
							},
							[2] = {
								['number'] = 2,
								['auto'] = false,
								['id'] = 'Bombing',
								['enabled'] = true,
								['params'] = {
									['groupAttack'] = false,
									['attackQtyLimit'] = true,
									['attackQty'] = 1,
									['attackType'] = 'nil',
									['altitude'] = 200,
									['x'] = 24764.675291289,
									['direction'] = 0,
									['altitudeEdited'] = true,
									['altitudeEnabled'] = true,
									['y'] = -241667.1524011,
									['weaponType'] = 2032,
									['directionEnabled'] = false,
								},
							},
							[3] = {
								['number'] = 3,
								['auto'] = false,
								['id'] = 'Bombing',
								['enabled'] = true,
								['params'] = {
									['groupAttack'] = false,
									['attackQtyLimit'] = true,
									['attackQty'] = 1,
									['attackType'] = 'nil',
									['altitude'] = 200,
									['x'] = 24721.500846477,
									['direction'] = 0,
									['altitudeEdited'] = true,
									['altitudeEnabled'] = true,
									['y'] = -241601.45468383,
									['weaponType'] = 2032,
									['directionEnabled'] = false,
								},
							},
							[4] = {
								['number'] = 4,
								['auto'] = false,
								['id'] = 'Bombing',
								['enabled'] = true,
								['params'] = {
									['groupAttack'] = false,
									['attackQtyLimit'] = true,
									['attackQty'] = 1,
									['attackType'] = 'nil',
									['altitude'] = 200,
									['x'] = 24676.125588337,
									['direction'] = 0,
									['altitudeEdited'] = true,
									['altitudeEnabled'] = true,
									['y'] = -241528.14145356,
									['weaponType'] = 2032,
									['directionEnabled'] = false,
								},
							},
							[5] = {
								['number'] = 5,
								['auto'] = false,
								['id'] = 'Bombing',
								['enabled'] = true,
								['params'] = {
									['groupAttack'] = false,
									['attackQtyLimit'] = true,
									['attackQty'] = 1,
									['attackType'] = 'nil',
									['altitude'] = 200,
									['x'] = 24626.014552287,
									['direction'] = 0,
									['altitudeEdited'] = true,
									['altitudeEnabled'] = true,
									['y'] = -241439.63699835,
									['weaponType'] = 2032,
									['directionEnabled'] = false,
								},
							},
							[6] = {
								['number'] = 6,
								['auto'] = false,
								['id'] = 'Bombing',
								['enabled'] = true,
								['params'] = {
									['groupAttack'] = false,
									['attackQtyLimit'] = true,
									['attackQty'] = 1,
									['attackType'] = 'nil',
									['altitude'] = 200,
									['x'] = 24549.347563773,
									['direction'] = 0,
									['altitudeEdited'] = true,
									['altitudeEnabled'] = true,
									['y'] = -241274.56409406,
									['weaponType'] = 2032,
									['directionEnabled'] = false,
								},
							},
							[7] = {
								['number'] = 7,
								['auto'] = false,
								['id'] = 'Bombing',
								['enabled'] = true,
								['params'] = {
									['groupAttack'] = false,
									['attackQtyLimit'] = true,
									['attackQty'] = 1,
									['attackType'] = 'nil',
									['altitude'] = 200,
									['x'] = 24409.897452375,
									['direction'] = 0,
									['altitudeEdited'] = true,
									['altitudeEnabled'] = true,
									['y'] = -240549.69737728,
									['weaponType'] = 2032,
									['directionEnabled'] = false,
								},
							},
							[8] = {
								['number'] = 8,
								['auto'] = false,
								['id'] = 'Bombing',
								['enabled'] = true,
								['params'] = {
									['groupAttack'] = false,
									['attackQtyLimit'] = true,
									['attackQty'] = 1,
									['attackType'] = 'nil',
									['altitude'] = 200,
									['x'] = 24393.080478573,
									['direction'] = 0,
									['altitudeEdited'] = true,
									['altitudeEnabled'] = true,
									['y'] = -240432.66415202,
									['weaponType'] = 2032,
									['directionEnabled'] = false,
								},
							},
							[9] = {
								['number'] = 9,
								['auto'] = false,
								['id'] = 'Bombing',
								['enabled'] = true,
								['params'] = {
									['groupAttack'] = false,
									['attackQtyLimit'] = true,
									['attackQty'] = 1,
									['attackType'] = 'nil',
									['altitude'] = 200,
									['x'] = 24371.175216749,
									['direction'] = 0,
									['altitudeEdited'] = true,
									['altitudeEnabled'] = true,
									['y'] = -240268.08823817,
									['weaponType'] = 2032,
									['directionEnabled'] = false,
								},
							},
							[10] = {
								['number'] = 10,
								['auto'] = false,
								['id'] = 'Bombing',
								['enabled'] = true,
								['params'] = {
									['groupAttack'] = false,
									['attackQtyLimit'] = true,
									['attackQty'] = 1,
									['attackType'] = 'nil',
									['altitude'] = 200,
									['x'] = 24357.53205647,
									['direction'] = 0,
									['altitudeEdited'] = true,
									['altitudeEnabled'] = true,
									['y'] = -240177.81900988,
									['weaponType'] = 2032,
									['directionEnabled'] = false,
								},
							},
							[11] = {
								['number'] = 11,
								['auto'] = false,
								['id'] = 'Bombing',
								['enabled'] = true,
								['params'] = {
									['groupAttack'] = false,
									['attackQtyLimit'] = true,
									['attackQty'] = 1,
									['attackType'] = 'nil',
									['altitude'] = 200,
									['x'] = 24382.136191168,
									['direction'] = 0,
									['altitudeEdited'] = true,
									['altitudeEnabled'] = true,
									['y'] = -240351.46731523,
									['weaponType'] = 2032,
									['directionEnabled'] = false,
								},
							},
							[12] = {
								['number'] = 12,
								['auto'] = false,
								['id'] = 'Bombing',
								['enabled'] = true,
								['params'] = {
									['groupAttack'] = false,
									['attackQtyLimit'] = true,
									['attackQty'] = 1,
									['attackType'] = 'nil',
									['altitude'] = 200,
									['x'] = 24093.218722443,
									['direction'] = 0,
									['altitudeEdited'] = true,
									['altitudeEnabled'] = true,
									['y'] = -239538.25583204,
									['weaponType'] = 2032,
									['directionEnabled'] = false,
								},
							},
							[13] = {
								['number'] = 13,
								['auto'] = false,
								['id'] = 'Bombing',
								['enabled'] = true,
								['params'] = {
									['groupAttack'] = false,
									['attackQtyLimit'] = true,
									['attackQty'] = 1,
									['attackType'] = 'nil',
									['altitude'] = 200,
									['x'] = 24036.474847986,
									['direction'] = 0,
									['altitudeEdited'] = true,
									['altitudeEnabled'] = true,
									['y'] = -239458.24195701,
									['weaponType'] = 2032,
									['directionEnabled'] = false,
								},
							},
							[14] = {
								['number'] = 14,
								['auto'] = false,
								['id'] = 'Bombing',
								['enabled'] = true,
								['params'] = {
									['groupAttack'] = false,
									['attackQtyLimit'] = true,
									['attackQty'] = 1,
									['attackType'] = 'nil',
									['altitude'] = 200,
									['x'] = 24338.178489128,
									['direction'] = 0,
									['altitudeEdited'] = true,
									['altitudeEnabled'] = true,
									['y'] = -240077.30057745,
									['weaponType'] = 2032,
									['directionEnabled'] = false,
								},
							},
							[15] = {
								['number'] = 15,
								['auto'] = false,
								['id'] = 'Bombing',
								['enabled'] = true,
								['params'] = {
									['groupAttack'] = false,
									['attackQtyLimit'] = true,
									['attackQty'] = 1,
									['attackType'] = 'nil',
									['altitude'] = 200,
									['x'] = 24156.107667655,
									['direction'] = 0,
									['altitudeEdited'] = true,
									['altitudeEnabled'] = true,
									['y'] = -239628.54452516,
									['weaponType'] = 2032,
									['directionEnabled'] = false,
								},
							},
							[16] = {
								['number'] = 16,
								['auto'] = false,
								['id'] = 'Bombing',
								['enabled'] = true,
								['params'] = {
									['groupAttack'] = false,
									['attackQtyLimit'] = true,
									['attackQty'] = 1,
									['attackType'] = 'nil',
									['altitude'] = 200,
									['x'] = 24220.65736973,
									['direction'] = 0,
									['altitudeEdited'] = true,
									['altitudeEnabled'] = true,
									['y'] = -239742.60724745,
									['weaponType'] = 2032,
									['directionEnabled'] = false,
								},
							},
							[17] = {
								['number'] = 17,
								['auto'] = false,
								['id'] = 'Bombing',
								['enabled'] = true,
								['params'] = {
									['groupAttack'] = false,
									['attackQtyLimit'] = true,
									['attackQty'] = 1,
									['attackType'] = 'nil',
									['altitude'] = 200,
									['x'] = 24259.965759747,
									['direction'] = 0,
									['altitudeEdited'] = true,
									['altitudeEnabled'] = true,
									['y'] = -239826.99698506,
									['weaponType'] = 2032,
									['directionEnabled'] = false,
								},
							},
							[18] = {
								['number'] = 18,
								['auto'] = false,
								['id'] = 'Bombing',
								['enabled'] = true,
								['params'] = {
									['groupAttack'] = false,
									['attackQtyLimit'] = true,
									['attackQty'] = 1,
									['attackType'] = 'nil',
									['altitude'] = 200,
									['x'] = 24320.919896945,
									['direction'] = 0,
									['altitudeEdited'] = true,
									['altitudeEnabled'] = true,
									['y'] = -240007.51057601,
									['weaponType'] = 2032,
									['directionEnabled'] = false,
								},
							},
							[19] = {
								['number'] = 19,
								['auto'] = false,
								['id'] = 'Bombing',
								['enabled'] = true,
								['params'] = {
									['groupAttack'] = false,
									['attackQtyLimit'] = true,
									['attackQty'] = 1,
									['attackType'] = 'nil',
									['altitude'] = 200,
									['x'] = 24295.585432035,
									['direction'] = 0,
									['altitudeEdited'] = true,
									['altitudeEnabled'] = true,
									['y'] = -239924.46180264,
									['weaponType'] = 2032,
									['directionEnabled'] = false,
								},
							},
						},
					},
				},
				['action'] = 'Turning Point',
			},
			[6] = {
				['speed_locked'] = false,
				['briefing_name'] = 'Target',
				['ETA'] = 1256.3313063217,
				['alt_type'] = 'RADIO',
				['properties'] = {
					['vnav'] = 1,
					['scale'] = 0,
					['vangle'] = 0,
					['angle'] = 0,
					['steer'] = 2,
				},
				['type'] = 'Turning Point',
				['alt'] = 0,
				['y'] = -233392.0156654,
				['formation_template'] = '',
				['name'] = 'Target 057  /   32 KM /   1 mn',
				['x'] = 24964.948880636,
				['speed'] = 350.5,
				['ETA_locked'] = true,
				['task'] = {
					['id'] = 'ComboTask',
					['params'] = {
						['tasks'] = {
						},
					},
				},
				['action'] = 'Turning Point',
			},
			[7] = {
				['speed_locked'] = true,
				['briefing_name'] = 'Egress',
				['ETA'] = 1376.9019197311,
				['alt_type'] = 'RADIO',
				['properties'] = {
					['vnav'] = 1,
					['scale'] = 0,
					['vangle'] = 0,
					['angle'] = 0,
					['steer'] = 2,
				},
				['type'] = 'Turning Point',
				['alt'] = 200,
				['y'] = -253479.09678066,
				['formation_template'] = '',
				['name'] = 'Egress 327  /   43 KM /   2 mn',
				['x'] = 62145.814554652,
				['speed'] = 350.5,
				['ETA_locked'] = false,
				['task'] = {
					['id'] = 'ComboTask',
					['params'] = {
						['tasks'] = {
							[1] = {
								['number'] = 1,
								['auto'] = false,
								['id'] = 'WrappedAction',
								['enabled'] = true,
								['params'] = {
									['action'] = {
										['id'] = 'Script',
										['params'] = {
											['command'] = 'CustomRejoin("Pack 1 - EC 331 - Strike 1")',
										},
									},
								},
							},
						},
					},
				},
				['action'] = 'Turning Point',
			},
			[8] = {
				['speed_locked'] = true,
				['briefing_name'] = 'Nav',
				['ETA'] = 1380.9998789148,
				['alt_type'] = 'RADIO',
				['properties'] = {
					['vnav'] = 1,
					['scale'] = 0,
					['vangle'] = 0,
					['angle'] = 0,
					['steer'] = 2,
				},
				['type'] = 'Turning Point',
				['alt'] = 300.4,
				['y'] = -254082.11721054,
				['formation_template'] = '',
				['name'] = 'Nav    212  /    2 KM /   0 mn',
				['x'] = 61343.080251696,
				['speed'] = 245,
				['ETA_locked'] = false,
				['task'] = {
					['id'] = 'ComboTask',
					['params'] = {
						['tasks'] = {
						},
					},
				},
				['action'] = 'Turning Point',
			},
			[9] = {
				['speed_locked'] = true,
				['briefing_name'] = 'Split',
				['ETA'] = 1728.376720148,
				['alt_type'] = 'RADIO',
				['properties'] = {
					['vnav'] = 1,
					['scale'] = 0,
					['vangle'] = 0,
					['angle'] = 0,
					['steer'] = 2,
				},
				['type'] = 'Turning Point',
				['alt'] = 300.4,
				['y'] = -305199.10562923,
				['formation_template'] = '',
				['name'] = 'Split  212  /   86 KM /   6 mn',
				['x'] = -6703.3043051537,
				['speed'] = 245,
				['ETA_locked'] = false,
				['task'] = {
					['id'] = 'ComboTask',
					['params'] = {
						['tasks'] = {
						},
					},
				},
				['action'] = 'Turning Point',
			},
			[10] = {
				['alt'] = 12,
				['briefing_name'] = 'Land',
				['action'] = 'Landing',
				['alt_type'] = 'RADIO',
				['properties'] = {
					['vnav'] = 1,
					['scale'] = 0,
					['vangle'] = 0,
					['angle'] = 0,
					['steer'] = 2,
				},
				['speed'] = 245,
				['task'] = {
					['id'] = 'ComboTask',
					['params'] = {
						['tasks'] = {
						},
					},
				},
				['airdromeId'] = 46,
				['ETA'] = 1789.6012099439,
				['ETA_locked'] = false,
				['y'] = -314208.375,
				['x'] = -18696.34668,
				['name'] = 'Land   212  /   16 KM /   1 mn',
				['formation_template'] = '',
				['type'] = 'Land',
				['speed_locked'] = true,
				['TotFlightDist'] = '263 KM',
				['TotFlightTime'] = ' 00:14',
			},
		},
		['unitname'] = 'M-2000C Pack 1 - EC 331 - Strike 1-1',
		['pack_n'] = 1,
		['airbase'] = 'Paphos Airbase',
		['tgt_wp'] = 6,
		['target'] = {
			['inactive'] = false,
			['elements'] = {
				[1] = {
					['y'] = -241772.17653267,
					['x'] = 24832.020004365,
					['name'] = 'NCTF 1-1',
					['dead_last'] = false,
					['foundOobGround'] = true,
					['groupId'] = 222,
				},
				[2] = {
					['y'] = -241667.1524011,
					['x'] = 24764.675291289,
					['name'] = 'NCTF 1-2',
					['dead_last'] = false,
					['foundOobGround'] = true,
					['groupId'] = 223,
				},
				[3] = {
					['y'] = -241601.45468383,
					['x'] = 24721.500846477,
					['name'] = 'NCTF 1-3',
					['dead_last'] = false,
					['foundOobGround'] = true,
					['groupId'] = 224,
				},
				[4] = {
					['y'] = -241528.14145356,
					['x'] = 24676.125588337,
					['name'] = 'NCTF 1-4',
					['dead_last'] = false,
					['foundOobGround'] = true,
					['groupId'] = 225,
				},
				[5] = {
					['y'] = -241439.63699835,
					['x'] = 24626.014552287,
					['name'] = 'NCTF 1-5',
					['dead_last'] = false,
					['foundOobGround'] = true,
					['groupId'] = 226,
				},
				[6] = {
					['y'] = -241274.56409406,
					['x'] = 24549.347563773,
					['name'] = 'NCTF 1-6',
					['dead_last'] = false,
					['foundOobGround'] = true,
					['groupId'] = 227,
				},
				[7] = {
					['name'] = 'NCTF 1-7',
					['groupId'] = 228,
					['dead_last'] = false,
					['foundOobGround'] = true,
					['dead'] = true,
				},
				[8] = {
					['name'] = 'NCTF 1-8',
					['groupId'] = 229,
					['dead_last'] = false,
					['foundOobGround'] = true,
					['dead'] = true,
				},
				[9] = {
					['name'] = 'NCTF 1-9',
					['groupId'] = 230,
					['dead_last'] = false,
					['foundOobGround'] = true,
					['dead'] = true,
				},
				[10] = {
					['name'] = 'NCTF 1-10',
					['groupId'] = 231,
					['dead_last'] = false,
					['foundOobGround'] = true,
					['dead'] = true,
				},
				[11] = {
					['name'] = 'NCTF 1-11',
					['groupId'] = 232,
					['dead_last'] = true,
					['foundOobGround'] = true,
					['dead'] = true,
				},
				[12] = {
					['y'] = -240549.69737728,
					['x'] = 24409.897452375,
					['name'] = 'NCTF 1-12',
					['dead_last'] = false,
					['foundOobGround'] = true,
					['groupId'] = 233,
				},
				[13] = {
					['y'] = -240432.66415202,
					['x'] = 24393.080478573,
					['name'] = 'NCTF 1-13',
					['dead_last'] = false,
					['foundOobGround'] = true,
					['groupId'] = 234,
				},
				[14] = {
					['y'] = -240268.08823817,
					['x'] = 24371.175216749,
					['name'] = 'NCTF 1-14',
					['dead_last'] = false,
					['foundOobGround'] = true,
					['groupId'] = 235,
				},
				[15] = {
					['y'] = -240177.81900988,
					['x'] = 24357.53205647,
					['name'] = 'NCTF 1-15',
					['dead_last'] = false,
					['foundOobGround'] = true,
					['groupId'] = 236,
				},
				[16] = {
					['y'] = -240351.46731523,
					['x'] = 24382.136191168,
					['name'] = 'NCTF 1-16',
					['dead_last'] = false,
					['foundOobGround'] = true,
					['groupId'] = 237,
				},
				[17] = {
					['y'] = -239538.25583204,
					['x'] = 24093.218722443,
					['name'] = 'NCTF 1-17',
					['dead_last'] = false,
					['foundOobGround'] = true,
					['groupId'] = 238,
				},
				[18] = {
					['y'] = -239458.24195701,
					['x'] = 24036.474847986,
					['name'] = 'NCTF 1-18',
					['dead_last'] = false,
					['foundOobGround'] = true,
					['groupId'] = 239,
				},
				[19] = {
					['y'] = -240077.30057745,
					['x'] = 24338.178489128,
					['name'] = 'NCTF 1-19',
					['dead_last'] = false,
					['foundOobGround'] = true,
					['groupId'] = 240,
				},
				[20] = {
					['y'] = -239628.54452516,
					['x'] = 24156.107667655,
					['name'] = 'NCTF 1-20',
					['dead_last'] = false,
					['foundOobGround'] = true,
					['groupId'] = 241,
				},
				[21] = {
					['y'] = -239742.60724745,
					['x'] = 24220.65736973,
					['name'] = 'NCTF 1-21',
					['dead_last'] = false,
					['foundOobGround'] = true,
					['groupId'] = 242,
				},
				[22] = {
					['y'] = -239826.99698506,
					['x'] = 24259.965759747,
					['name'] = 'NCTF 1-22',
					['dead_last'] = false,
					['foundOobGround'] = true,
					['groupId'] = 243,
				},
				[23] = {
					['y'] = -240007.51057601,
					['x'] = 24320.919896945,
					['name'] = 'NCTF 1-23',
					['dead_last'] = false,
					['foundOobGround'] = true,
					['groupId'] = 244,
				},
				[24] = {
					['y'] = -239924.46180264,
					['x'] = 24295.585432035,
					['name'] = 'NCTF 1-24',
					['dead_last'] = false,
					['foundOobGround'] = true,
					['groupId'] = 245,
				},
			},
			['picture'] = {
				[1] = 'NCTF-1.png',
			},
			['foundOobGround'] = true,
			['class'] = 'static',
			['ATO'] = true,
			['attributes'] = {
				[1] = 'soft',
			},
			['y'] = -233392.0156654,
			['x'] = 24964.948880636,
			['firepower'] = {
				['min'] = 2,
				['max'] = 6,
			},
			['dead_last'] = 4,
			['alive'] = 79,
			['priority'] = 18,
			['task'] = 'Strike',
			['TitleName'] = 'North Cyprus-Turkish Force 1',
		},
	},
	['title'] = 'Cyprus Incident-Mirage',
	['aircraft_availability'] = {
		['3rd KHA'] = {
			['assigned'] = 0,
			['available'] = 0,
			['unassigned'] = 0,
			['unavailable'] = {
				[6] = 305321,
				[2] = 307754,
				[3] = 305321,
				[1] = 307754,
				[4] = 305321,
				[5] = 305321,
			},
			['ready'] = 6,
			['serviceable'] = 6,
		},
		['222.Filo'] = {
			['assigned'] = 0,
			['available'] = 0,
			['unassigned'] = 0,
			['unavailable'] = {
				[6] = 305321,
				[2] = 307754,
				[3] = 305321,
				[1] = 307754,
				[4] = 305321,
				[5] = 305321,
			},
			['ready'] = 6,
			['serviceable'] = 5,
		},
		['450 M-E/P-1'] = {
			['assigned'] = 0,
			['available'] = 0,
			['unassigned'] = 0,
			['unavailable'] = {
				[6] = 301534,
				[2] = 305321,
				[3] = 305321,
				[1] = 305321,
				[4] = 305321,
				[5] = 301534,
			},
			['ready'] = 6,
			['serviceable'] = 6,
		},
		['EC 331'] = {
			['assigned'] = 2,
			['available'] = 2,
			['unassigned'] = 0,
			['unavailable'] = {
				[7] = 295829,
				[1] = 303691,
				[2] = 303691,
				[4] = 295829,
				[5] = 295829,
				[3] = 301534,
				[6] = 295829,
			},
			['ready'] = 7,
			['serviceable'] = 7,
		},
		['134.Filo'] = {
			['assigned'] = 0,
			['available'] = 1,
			['unassigned'] = 1,
			['unavailable'] = {
				[2] = 299101,
				[3] = 299101,
				[1] = 299101,
				[4] = 299101,
				[5] = 0,
			},
			['ready'] = 5,
			['serviceable'] = 4,
		},
		['2nd-2 KHA'] = {
			['assigned'] = 0,
			['available'] = 0,
			['unassigned'] = 0,
			['unavailable'] = {
				[6] = 301994,
				[2] = 305321,
				[3] = 305321,
				[1] = 305321,
				[4] = 305321,
				[5] = 301994,
			},
			['ready'] = 6,
			['serviceable'] = 5,
		},
		['111.Filo'] = {
			['assigned'] = 0,
			['available'] = 0,
			['unassigned'] = 0,
			['unavailable'] = {
				[7] = 299101,
				[1] = 305321,
				[2] = 305321,
				[4] = 301534,
				[8] = 299101,
				[9] = 299101,
				[5] = 301534,
				[3] = 305321,
				[6] = 299101,
			},
			['ready'] = 9,
			['serviceable'] = 7,
		},
		['450 M-E/P-2'] = {
			['assigned'] = 0,
			['available'] = 1,
			['unassigned'] = 1,
			['unavailable'] = {
				[1] = 305321,
				[2] = 305321,
				[4] = 0,
				[3] = 305321,
			},
			['ready'] = 4,
			['serviceable'] = 4,
		},
		['356th Tactical Transport Squadron'] = {
			['assigned'] = 0,
			['available'] = 0,
			['unassigned'] = 0,
			['unavailable'] = {
				[6] = 305321,
				[2] = 307754,
				[3] = 307754,
				[1] = 307754,
				[4] = 305321,
				[5] = 305321,
			},
			['ready'] = 6,
			['serviceable'] = 4,
		},
		['2nd KHA'] = {
			['assigned'] = 0,
			['available'] = 0,
			['unassigned'] = 0,
			['unavailable'] = {
				[6] = 299561,
				[2] = 299561,
				[3] = 299561,
				[1] = 299561,
				[4] = 299561,
				[5] = 299561,
			},
			['ready'] = 6,
			['serviceable'] = 5,
		},
	},
	['mission'] = 10,
	['path'] = 'P:/Saved Games/DCS.openbeta/',
	['startup'] = 600,
	['SC_CarrierIntoWind'] = 'man',
	['idle_time_max'] = 14400,
	['time'] = 36311,
	['ShipDamagedLast'] = {
	},
	['weather'] = {
		['zoneNextTemp'] = 30,
		['pHigh'] = 60,
		['pLow'] = 40,
		['zoneNext'] = 'high',
		['zoneTemp'] = 33,
		['refTemp'] = 28,
		['zoneEnd'] = 2083662,
		['zone'] = 'high',
		['zoneStart'] = 1930666,
	},
	['CVN_windDeck'] = 9,
	['dusk'] = 68880,
	['ShipHealth'] = {
		['Turkish Naval Convoy 1-2'] = 100,
		['Turkish Naval Convoy 1-3'] = 100,
		['Greek Naval Convoy-1'] = 100,
		['Naval-1-3'] = 100,
		['Greek Naval Convoy-4'] = 100,
		['Larnaca Turkish Assault Force 1-Boat-1'] = 100,
		['Turkish Naval Convoy 2-3'] = 100,
		['Naval-1-4'] = 100,
		['Turkish Naval Convoy 2-2'] = 100,
		['Greek Naval Convoy-8'] = 100,
		['Greek Naval Convoy-5'] = 100,
		['Greek Naval Convoy-6'] = 100,
		['Turkish Naval Convoy 1-4'] = 100,
		['Greek Naval Convoy-3'] = 100,
		['Turkish Naval Convoy 2-4'] = 100,
		['Turkish Naval Convoy 1-5'] = 100,
		['Greek Naval Convoy-7'] = 100,
		['Naval-1-2'] = 100,
		['Greek Naval Convoy-9'] = 100,
		['Turkish Naval Convoy 2-5'] = 100,
		['Naval-1-7'] = 100,
		['Turkish Naval Convoy 1-1'] = 100,
		['Naval-1-1'] = 100,
		['Naval-1-8'] = 100,
		['Naval-1-5'] = 100,
		['Turkish Naval Convoy 1-6'] = 100,
		['Naval-1-9'] = 100,
		['Greek Naval Convoy-2'] = 100,
		['Naval-1-6'] = 100,
		['Turkish Naval Convoy 2-1'] = 100,
	},
	['radio'] = {
		['blue'] = {
			[1] = {
				['FM'] = {
					['min'] = 30,
					['max'] = 50,
				},
				['UHF'] = {
					['max'] = 399,
					['player'] = true,
					['min'] = 226,
				},
				['VHF'] = {
					['max'] = 225,
					['player'] = true,
					['min'] = 100,
				},
			},
			[2] = {
				['UHF'] = {
					['min'] = 225,
					['max'] = 400,
				},
				['VHF'] = {
					['min'] = 118,
					['max'] = 140,
				},
			},
			[3] = {
				['UHF'] = {
					['min'] = 225,
					['max'] = 399.9,
				},
			},
		},
		['red'] = {
			[1] = {
				['UHF'] = {
					['min'] = 225,
					['max'] = 399,
				},
			},
		},
	},
	['ShipHealth0'] = {
		['Turkish Naval Convoy 1-2'] = 1000,
		['Turkish Naval Convoy 1-3'] = 1000,
		['Greek Naval Convoy-1'] = 2100,
		['Naval-1-3'] = 750,
		['Greek Naval Convoy-4'] = 1000,
		['Larnaca Turkish Assault Force 1-Boat-1'] = 1000,
		['Turkish Naval Convoy 2-3'] = 1000,
		['Naval-1-4'] = 200,
		['Turkish Naval Convoy 2-2'] = 1000,
		['Greek Naval Convoy-8'] = 1000,
		['Greek Naval Convoy-5'] = 1000,
		['Greek Naval Convoy-6'] = 1000,
		['Turkish Naval Convoy 1-4'] = 1000,
		['Greek Naval Convoy-3'] = 1000,
		['Turkish Naval Convoy 2-4'] = 1000,
		['Turkish Naval Convoy 1-5'] = 1000,
		['Greek Naval Convoy-7'] = 1000,
		['Naval-1-2'] = 750,
		['Greek Naval Convoy-9'] = 750,
		['Turkish Naval Convoy 2-5'] = 1000,
		['Naval-1-7'] = 200,
		['Turkish Naval Convoy 1-1'] = 2100,
		['Naval-1-1'] = 2100,
		['Naval-1-8'] = 200,
		['Naval-1-5'] = 1000,
		['Turkish Naval Convoy 1-6'] = 1000,
		['Naval-1-9'] = 1000,
		['Greek Naval Convoy-2'] = 750,
		['Naval-1-6'] = 400,
		['Turkish Naval Convoy 2-1'] = 2100,
	},
	['units'] = 'metric',
	['variation'] = 4,
	['flag'] = {
		[803] = 6,
		[811] = 7,
		[801] = 5,
		[804] = 9,
	},
	['mission_duration'] = 5400,
	['ScriptsMod'] = '20.58.205',
	['version'] = 'V2.15',
	['debug'] = false,
	['versionPackageICM'] = 'NG',
	['MultiPlayer'] = {
		['pack_n'] = {
		},
	},
}
