oob_air = {
	['blue'] = {
		[1] = {
			['number'] = 8,
			['type'] = 'F-16C_50',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Greece',
			['tasks'] = {
				['Strike'] = true,
				['Fighter Sweep'] = true,
				['Escort'] = true,
				['CAP'] = true,
				['Intercept'] = true,
			},
			['skill'] = 'High',
			['InitReserve'] = 30,
			['reserve'] = 30,
			['tasksCoef'] = {
				['Strike'] = 0.5,
				['Fighter Sweep'] = 1,
				['Escort'] = 1,
				['Laser Illumination'] = 1,
				['SEAD'] = 1,
				['Anti-ship Strike'] = 1,
				['CAP'] = 1.5,
				['Intercept'] = 2,
			},
			['player'] = false,
			['name'] = '347th Squadron',
			['roster'] = {
				['trans'] = 0,
				['lost'] = 0,
				['ready'] = 8,
				['damaged'] = 0,
				['reserve'] = 30,
			},
			['livery'] = {
				[1] = 'HAF F-16C 347 SQ PERSEAS',
			},
			['inactive'] = true,
			['base'] = 'Kasteli Airbase',
			['score_last'] = {
				['kills_ground'] = 0,
				['kills_air'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['damaged'] = 0,
				['ready'] = 0,
			},
		},
		[2] = {
			['number'] = 6,
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
				['Fighter Sweep'] = false,
				['Escort'] = false,
				['CAP'] = false,
				['Intercept'] = false,
				['Transport'] = true,
			},
			['skill'] = 'High',
			['roster'] = {
				['trans'] = 0,
				['lost'] = 0,
				['ready'] = 6,
				['damaged'] = 0,
				['reserve'] = 18,
			},
			['livery'] = 'HAF SEA Camo',
			['base'] = 'Kasteli Airbase',
			['callsignId'] = 3,
			['callsign'] = 'Uzi',
			['reserve'] = 18,
			['tasksCoef'] = {
				['Strike'] = 1,
				['Fighter Sweep'] = 1,
				['Escort'] = 1,
				['Laser Illumination'] = 1,
				['SEAD'] = 1,
				['Anti-ship Strike'] = 1,
				['CAP'] = 2,
				['Intercept'] = 2,
			},
			['player'] = false,
			['name'] = '356th Tactical Transport Squadron',
			['InitReserve'] = 18,
			['country'] = 'Greece',
			['type'] = 'C-130',
			['score_last'] = {
				['kills_ground'] = 0,
				['kills_air'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['damaged'] = 0,
				['ready'] = 0,
			},
		},
		[3] = {
			['number'] = 16,
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 43,
				['kills_ground'] = 34,
			},
			['tasks'] = {
				['Strike'] = true,
				['Fighter Sweep'] = true,
				['Escort'] = true,
				['CAP'] = true,
				['Intercept'] = true,
			},
			['skill'] = 'High',
			['roster'] = {
				['trans'] = 30,
				['lost'] = 39,
				['ready'] = 7,
				['damaged'] = 0,
				['reserve'] = 0,
			},
			['livery'] = {
				[1] = 'Greek Air Force',
			},
			['base'] = 'Paphos Airbase',
			['type'] = 'M-2000C',
			['country'] = 'Greece',
			['callsignId'] = 6,
			['reserve'] = 30,
			['tasksCoef'] = {
				['Strike'] = 1,
				['Fighter Sweep'] = 1,
				['Escort'] = 1,
				['Laser Illumination'] = 1,
				['SEAD'] = 1,
				['Anti-ship Strike'] = 1,
				['CAP'] = 1.5,
				['Intercept'] = 2,
			},
			['inactive'] = false,
			['name'] = 'EC 331',
			['callsign'] = 'Ford',
			['player'] = true,
			['parking_id'] = {
				[''] = {
					[13] = 35,
					[7] = 29,
					[1] = 23,
					[2] = 24,
					[4] = 26,
					[8] = 30,
					[15] = 37,
					[9] = 31,
					[5] = 27,
					[10] = 32,
					[3] = 25,
					[11] = 33,
					[6] = 28,
					[12] = 34,
					[14] = 36,
				},
			},
			['InitReserve'] = 30,
			['score_last'] = {
				['kills_ground'] = 1,
				['kills_air'] = 0,
				['lost'] = 4,
				['kills_ship'] = 0,
				['damaged'] = 0,
				['ready'] = 4,
			},
		},
		[4] = {
			['number'] = 6,
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 5,
			},
			['tasks'] = {
				['Strike'] = true,
				['Fighter Sweep'] = false,
				['Escort'] = true,
				['CAP'] = false,
				['Anti-ship Strike'] = false,
			},
			['skill'] = 'High',
			['roster'] = {
				['trans'] = 5,
				['lost'] = 5,
				['ready'] = 6,
				['damaged'] = 0,
				['reserve'] = 13,
			},
			['livery'] = {
				[1] = 'Cypriot Air Force 450th AHS Black Panther',
				[2] = 'Cypriot National Guard - 819',
			},
			['base'] = 'FARP-London',
			['type'] = 'Mi-24P',
			['callsign'] = 'Enfield',
			['InitReserve'] = 18,
			['reserve'] = 18,
			['tasksCoef'] = {
				['Strike'] = 2,
				['Fighter Sweep'] = 1,
				['Escort'] = 1,
				['Laser Illumination'] = 1,
				['SEAD'] = 1,
				['Anti-ship Strike'] = 3,
				['CAP'] = 1,
				['Intercept'] = 1,
			},
			['inactive'] = false,
			['name'] = '450 M-E/P-1',
			['callsignId'] = 1,
			['country'] = 'Cyprus',
			['helicopter'] = true,
			['player'] = false,
			['score_last'] = {
				['kills_ground'] = 0,
				['kills_air'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['damaged'] = 0,
				['ready'] = 0,
			},
		},
		[5] = {
			['number'] = 4,
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 12,
			},
			['tasks'] = {
				['Strike'] = true,
			},
			['skill'] = 'high',
			['roster'] = {
				['trans'] = 3,
				['lost'] = 3,
				['ready'] = 4,
				['damaged'] = 0,
				['reserve'] = 9,
			},
			['livery'] = {
				[1] = '',
			},
			['base'] = 'FARP-Dallas',
			['callsignId'] = 2,
			['callsign'] = 'Springfield',
			['reserve'] = 12,
			['helicopter'] = true,
			['player'] = false,
			['name'] = '450 M-E/P-2',
			['InitReserve'] = 12,
			['country'] = 'Cyprus',
			['type'] = 'SA342M',
			['score_last'] = {
				['kills_ground'] = 0,
				['kills_air'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['damaged'] = 0,
				['ready'] = 0,
			},
		},
	},
	['red'] = {
		[1] = {
			['number'] = 6,
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
				['Transport'] = true,
			},
			['skill'] = 'High',
			['roster'] = {
				['trans'] = 5,
				['lost'] = 5,
				['ready'] = 6,
				['damaged'] = 0,
				['reserve'] = 7,
			},
			['livery'] = 'Turkish Air Force',
			['base'] = 'Incirlik Airbase',
			['callsignId'] = 5,
			['callsign'] = 'Dodge',
			['inactive'] = false,
			['reserve'] = 12,
			['tasksCoef'] = {
				['Transport'] = 1,
				['Anti-ship Strike'] = 1,
				['Escort'] = 1,
				['Laser Illumination'] = 1,
				['SEAD'] = 1,
				['Fighter Sweep'] = 1,
				['CAP'] = 2,
				['Intercept'] = 2,
			},
			['InitNumber'] = 6,
			['name'] = '222.Filo',
			['InitReserve'] = 12,
			['type'] = 'C-130',
			['country'] = 'Turkey',
			['player'] = false,
			['score_last'] = {
				['kills_ground'] = 0,
				['kills_air'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['damaged'] = 0,
				['ready'] = 0,
			},
		},
		[2] = {
			['number'] = 6,
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
				['Strike'] = true,
				['Escort'] = true,
			},
			['InitReserve'] = 16,
			['roster'] = {
				['trans'] = 0,
				['lost'] = 0,
				['ready'] = 6,
				['damaged'] = 0,
				['reserve'] = 16,
			},
			['livery'] = 'Turkey 2',
			['base'] = 'Ercan Airbase',
			['score_last'] = {
				['kills_ground'] = 0,
				['kills_air'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['damaged'] = 0,
				['ready'] = 0,
			},
			['country'] = 'Turkey',
			['reserve'] = 16,
			['helicopter'] = true,
			['InitNumber'] = 6,
			['name'] = '2nd KHA',
			['inactive'] = false,
			['skill'] = 'Random',
			['type'] = 'AH-1W',
			['callsign'] = 'Uzi',
			['callsignId'] = 3,
		},
		[3] = {
			['number'] = 6,
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
				['Strike'] = true,
				['Escort'] = true,
			},
			['InitReserve'] = 16,
			['roster'] = {
				['trans'] = 3,
				['lost'] = 2,
				['ready'] = 6,
				['damaged'] = 1,
				['reserve'] = 13,
			},
			['livery'] = 'Turkey 2',
			['base'] = 'FARP-Madrid',
			['score_last'] = {
				['kills_ground'] = 0,
				['kills_air'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['damaged'] = 0,
				['ready'] = 0,
			},
			['country'] = 'Turkey',
			['reserve'] = 16,
			['helicopter'] = true,
			['InitNumber'] = 6,
			['name'] = '2nd-2 KHA',
			['callsignId'] = 1,
			['callsign'] = 'Enfield',
			['type'] = 'AH-1W',
			['inactive'] = false,
			['skill'] = 'Random',
		},
		[4] = {
			['number'] = 12,
			['type'] = 'F-16C_50',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Turkey',
			['tasks'] = {
				['Strike'] = true,
				['Fighter Sweep'] = true,
				['Escort'] = true,
				['CAP'] = true,
				['SEAD'] = true,
				['Intercept'] = true,
			},
			['inactive'] = true,
			['skill'] = 'high',
			['reserve'] = 24,
			['tasksCoef'] = {
				['Strike'] = 1,
				['Fighter Sweep'] = 1,
				['Escort'] = 1.5,
				['Laser Illumination'] = 1,
				['SEAD'] = 1,
				['CAP'] = 1,
				['Intercept'] = 1,
			},
			['InitNumber'] = 12,
			['name'] = '152 Filo',
			['roster'] = {
				['trans'] = 0,
				['lost'] = 0,
				['ready'] = 12,
				['damaged'] = 0,
				['reserve'] = 24,
			},
			['livery'] = 'TUAF 152 Akincilar',
			['InitReserve'] = 24,
			['base'] = 'Incirlik Airbase',
			['score_last'] = {
				['kills_ground'] = 0,
				['kills_air'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['damaged'] = 0,
				['ready'] = 0,
			},
		},
		[5] = {
			['number'] = 12,
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 3,
				['kills_ground'] = 1,
			},
			['tasks'] = {
				['Strike'] = true,
				['Fighter Sweep'] = false,
				['Escort'] = false,
				['CAP'] = true,
				['Intercept'] = false,
			},
			['InitReserve'] = 16,
			['roster'] = {
				['trans'] = 16,
				['lost'] = 23,
				['ready'] = 5,
				['damaged'] = 0,
				['reserve'] = 0,
			},
			['livery'] = '3rd Main Jet Base Group Command, Turkey',
			['base'] = 'Gecitkale Airbase',
			['score_last'] = {
				['kills_ground'] = 0,
				['kills_air'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['damaged'] = 0,
				['ready'] = 0,
			},
			['country'] = 'Turkey',
			['reserve'] = 16,
			['tasksCoef'] = {
				['Strike'] = 3,
				['Fighter Sweep'] = 1,
				['Escort'] = 1,
				['Laser Illumination'] = 1,
				['SEAD'] = 1,
				['CAP'] = 1,
				['Intercept'] = 1,
			},
			['inactive'] = false,
			['name'] = '134.Filo',
			['callsignId'] = 8,
			['callsign'] = 'Pontiac',
			['type'] = 'F-5E-3',
			['InitNumber'] = 12,
			['skill'] = 'Random',
		},
		[6] = {
			['number'] = 6,
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
				['Strike'] = true,
				['Fighter Sweep'] = false,
				['Escort'] = false,
				['CAP'] = false,
				['Intercept'] = false,
				['Transport'] = false,
			},
			['skill'] = 'High',
			['roster'] = {
				['trans'] = 7,
				['lost'] = 7,
				['ready'] = 6,
				['damaged'] = 0,
				['reserve'] = 5,
			},
			['livery'] = {
				[1] = '',
			},
			['base'] = 'Pinarbashi Airbase',
			['callsignId'] = 4,
			['callsign'] = 'Colt',
			['reserve'] = 12,
			['tasksCoef'] = {
				['Strike'] = 1,
				['Fighter Sweep'] = 1,
				['Escort'] = 1,
				['Laser Illumination'] = 1,
				['SEAD'] = 1,
				['Intercept'] = 1.5,
				['CAP'] = 2,
				['Transport'] = 1,
			},
			['InitNumber'] = 6,
			['name'] = '3rd KHA',
			['type'] = 'UH-1H',
			['country'] = 'Turkey',
			['InitReserve'] = 12,
			['helicopter'] = true,
			['score_last'] = {
				['kills_ground'] = 0,
				['kills_air'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['damaged'] = 0,
				['ready'] = 0,
			},
		},
		[7] = {
			['number'] = 16,
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 10,
				['kills_ground'] = 6,
			},
			['tasks'] = {
				['Strike'] = true,
				['Fighter Sweep'] = true,
				['Escort'] = true,
				['SEAD'] = true,
				['Anti-ship Strike'] = true,
				['CAP'] = true,
				['Intercept'] = true,
			},
			['InitReserve'] = 24,
			['roster'] = {
				['trans'] = 24,
				['lost'] = 30,
				['ready'] = 9,
				['damaged'] = 1,
				['reserve'] = 0,
			},
			['livery'] = 'F4 Turkey',
			['base'] = 'Incirlik Airbase',
			['score_last'] = {
				['kills_ground'] = 0,
				['kills_air'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['damaged'] = 0,
				['ready'] = 0,
			},
			['country'] = 'Turkey',
			['reserve'] = 24,
			['tasksCoef'] = {
				['Strike'] = 1,
				['Fighter Sweep'] = 1,
				['Escort'] = 1,
				['Laser Illumination'] = 1,
				['SEAD'] = 1,
				['CAP'] = 1,
				['Intercept'] = 1,
			},
			['inactive'] = false,
			['name'] = '111.Filo',
			['callsignId'] = 7,
			['callsign'] = 'Chevy',
			['type'] = 'F-4E',
			['InitNumber'] = 16,
			['skill'] = 'Random',
		},
	},
}
TypeAlias = {
	['Mi-24P'] = 'Mi-35P',
}
