targetlist = {
	['blue'] = {
		['EWR-Deathstar'] = {
			['x'] = 170511.92939443,
			['elements'] = {
				[1] = {
					['name'] = 'EWR-Deathstar',
					['dead_last'] = false,
				},
				[2] = {
					['name'] = 'EWR-Deathstar-2',
					['dead_last'] = false,
				},
				[3] = {
					['name'] = 'EWR-Deathstar-3',
					['dead_last'] = false,
				},
				[4] = {
					['name'] = 'EWR-Deathstar-4',
					['dead_last'] = false,
				},
				[5] = {
					['name'] = 'EWR-Deathstar-5',
					['dead_last'] = false,
				},
			},
			['groupId'] = 74,
			['foundOobGround'] = true,
			['class'] = 'vehicle',
			['ATO'] = true,
			['alive'] = 100,
			['y'] = -44728.909653577,
			['inactive'] = false,
			['name'] = 'EWR-Deathstar',
			['dead_last'] = 0,
			['attributes'] = {
				[1] = 'soft',
			},
			['priority'] = 5,
			['task'] = 'Strike',
			['firepower'] = {
				['min'] = 2,
				['max'] = 6,
			},
		},
		['Ercan Airbase'] = {
			['elements'] = {
				[7] = {
					['y'] = -218408.890625,
					['x'] = 24826.49609375,
					['name'] = 'Ercan Airbase Fuel Center 1',
					['dead_last'] = false,
				},
				[1] = {
					['y'] = -217960.140625,
					['x'] = 24470.318359375,
					['name'] = 'Ercan Airbase Hangar 1',
					['dead_last'] = false,
				},
				[2] = {
					['y'] = -218068.3125,
					['x'] = 24506.625,
					['name'] = 'Ercan Airbase Hangar 2',
					['dead_last'] = false,
					['CheckDay'] = 4,
					['dead'] = true,
				},
				[4] = {
					['y'] = -218305,
					['x'] = 24607.576171875,
					['name'] = 'Ercan Airbase Hangar 4',
					['dead_last'] = false,
				},
				[8] = {
					['y'] = -218380.75,
					['x'] = 24785.984375,
					['name'] = 'Ercan Airbase Fuel Tank 1',
					['dead_last'] = false,
				},
				[9] = {
					['y'] = -218411.421875,
					['x'] = 24704,
					['name'] = 'Ercan Airbase Fuel Tank 2',
					['dead_last'] = false,
				},
				[5] = {
					['y'] = -218346.234375,
					['x'] = 24639.82421875,
					['name'] = 'Ercan Airbase Hangar 5',
					['dead_last'] = false,
				},
				[10] = {
					['y'] = -217444.734375,
					['x'] = 24328.296875,
					['name'] = 'Ercan Airbase Ammunition Center 1',
					['dead_last'] = false,
				},
				[3] = {
					['y'] = -218282.46875,
					['x'] = 24597.279296875,
					['name'] = 'Ercan Airbase Hangar 3',
					['dead_last'] = false,
				},
				[6] = {
					['y'] = -218257.8125,
					['x'] = 24578.287109375,
					['name'] = 'Ercan Airbase HQ',
					['dead_last'] = false,
				},
				[12] = {
					['y'] = -217416.015625,
					['x'] = 24308.134765625,
					['name'] = 'Ercan Airbase Ammunition Center 3',
					['dead_last'] = false,
				},
				[11] = {
					['y'] = -217394.484375,
					['x'] = 24296.4375,
					['name'] = 'Ercan Airbase Ammunition Center 2',
					['dead_last'] = false,
				},
			},
			['picture'] = {
				[1] = 'Ercan Airbase.png',
			},
			['ATO'] = true,
			['y'] = -218056.35546875,
			['x'] = 24554.104980469,
			['firepower'] = {
				['min'] = 2,
				['max'] = 6,
			},
			['dead_last'] = 0,
			['alive'] = 91,
			['priority'] = 6,
			['task'] = 'Strike',
			['attributes'] = {
				[1] = 'Structure',
			},
		},
		['Pinarbashi Airbase'] = {
			['elements'] = {
				[7] = {
					['y'] = -238698.6875,
					['x'] = 38937.63671875,
					['name'] = 'Pinarbashi Airbase Ammunition Center',
					['dead_last'] = false,
				},
				[1] = {
					['y'] = -238774.59960938,
					['x'] = 39061.626953125,
					['name'] = 'Pinarbashi Airbase Hangar 1',
					['dead_last'] = false,
				},
				[2] = {
					['y'] = -238818.35058594,
					['x'] = 39262.537109375,
					['name'] = 'Pinarbashi Airbase Hangar 2',
					['dead_last'] = false,
				},
				[4] = {
					['y'] = -238550.39746094,
					['x'] = 39019.198242188,
					['name'] = 'Pinarbashi Airbase HQ',
					['dead_last'] = false,
				},
				[8] = {
					['y'] = -238777.97802734,
					['x'] = 39039.168945313,
					['name'] = 'Pinarbashi Airbase Support Center',
					['dead_last'] = false,
				},
				[9] = {
					['y'] = -238590.78613281,
					['x'] = 39151.743164063,
					['name'] = 'Pinarbashi Airbase Logistic Center 1',
					['dead_last'] = false,
				},
				[5] = {
					['y'] = -238798.34033203,
					['x'] = 38995.913658142,
					['name'] = 'Pinarbashi Airbase Fuel Center 1',
					['dead_last'] = false,
				},
				[10] = {
					['y'] = -238571.97662354,
					['x'] = 39191.224609375,
					['name'] = 'Pinarbashi Airbase Logistic Center 2',
					['dead_last'] = false,
				},
				[3] = {
					['y'] = -238780.26904297,
					['x'] = 39107.831054688,
					['name'] = 'Pinarbashi Airbase Hangar 3',
					['dead_last'] = false,
				},
				[6] = {
					['y'] = -238765.234375,
					['x'] = 39028.4140625,
					['name'] = 'Pinarbashi Airbase Fuel Center 2',
					['dead_last'] = false,
				},
				[11] = {
					['y'] = -238539.84844971,
					['x'] = 39153.175048828,
					['name'] = 'Pinarbashi Airbase Logistic Center 3',
					['dead_last'] = false,
				},
			},
			['picture'] = {
				[1] = 'Pinarbashi Airbase.png',
			},
			['ATO'] = true,
			['y'] = -238696.95164906,
			['x'] = 39086.224506032,
			['firepower'] = {
				['min'] = 2,
				['max'] = 6,
			},
			['dead_last'] = 0,
			['alive'] = 100,
			['priority'] = 5,
			['task'] = 'Strike',
			['attributes'] = {
				[1] = 'Structure',
			},
		},
		['North Cyprus Force 1'] = {
			['elements'] = {
				[1] = {
					['name'] = 'NCF 1-1',
					['groupId'] = 192,
					['dead_last'] = false,
					['foundOobGround'] = true,
					['dead'] = true,
				},
				[13] = {
					['name'] = 'NCF 1-13',
					['groupId'] = 204,
					['dead_last'] = false,
					['foundOobGround'] = true,
					['dead'] = true,
				},
				[7] = {
					['name'] = 'NCF 1-7',
					['groupId'] = 198,
					['dead_last'] = false,
					['foundOobGround'] = true,
					['dead'] = true,
				},
				[14] = {
					['name'] = 'NCF 1-14',
					['groupId'] = 205,
					['dead_last'] = false,
					['foundOobGround'] = true,
					['dead'] = true,
				},
				[2] = {
					['name'] = 'NCF 1-2',
					['groupId'] = 193,
					['dead_last'] = false,
					['foundOobGround'] = true,
					['dead'] = true,
				},
				[15] = {
					['name'] = 'NCF 1-15',
					['groupId'] = 206,
					['dead_last'] = false,
					['foundOobGround'] = true,
					['dead'] = true,
				},
				[8] = {
					['name'] = 'NCF 1-8',
					['groupId'] = 199,
					['dead_last'] = false,
					['foundOobGround'] = true,
					['dead'] = true,
				},
				[16] = {
					['name'] = 'NCF 1-16',
					['groupId'] = 207,
					['dead_last'] = false,
					['foundOobGround'] = true,
					['dead'] = true,
				},
				[9] = {
					['name'] = 'NCF 1-9',
					['groupId'] = 200,
					['dead_last'] = false,
					['foundOobGround'] = true,
					['dead'] = true,
				},
				[5] = {
					['name'] = 'NCF 1-5',
					['groupId'] = 196,
					['dead_last'] = false,
					['foundOobGround'] = true,
					['dead'] = true,
				},
				[10] = {
					['name'] = 'NCF 1-10',
					['groupId'] = 201,
					['dead_last'] = false,
					['foundOobGround'] = true,
					['dead'] = true,
				},
				[11] = {
					['name'] = 'NCF 1-11',
					['groupId'] = 202,
					['dead_last'] = false,
					['foundOobGround'] = true,
					['dead'] = true,
				},
				[3] = {
					['name'] = 'NCF 1-3',
					['groupId'] = 194,
					['dead_last'] = false,
					['foundOobGround'] = true,
					['dead'] = true,
				},
				[6] = {
					['name'] = 'NCF 1-6',
					['groupId'] = 197,
					['dead_last'] = false,
					['foundOobGround'] = true,
					['dead'] = true,
				},
				[12] = {
					['name'] = 'NCF 1-12',
					['groupId'] = 203,
					['dead_last'] = false,
					['foundOobGround'] = true,
					['dead'] = true,
				},
				[4] = {
					['name'] = 'NCF 1-4',
					['groupId'] = 195,
					['dead_last'] = false,
					['foundOobGround'] = true,
					['dead'] = true,
				},
			},
			['picture'] = {
				[1] = 'North Cyprus Columns.png',
			},
			['x'] = 17515.260244118,
			['class'] = 'static',
			['ATO'] = false,
			['foundOobGround'] = true,
			['y'] = -236500.86752,
			['inactive'] = true,
			['attributes'] = {
				[1] = 'soft',
			},
			['dead_last'] = 0,
			['alive'] = 0,
			['priority'] = 8,
			['task'] = 'Strike',
			['firepower'] = {
				['min'] = 2,
				['max'] = 6,
			},
		},
		['Larnaca Turkish Assault Force 1'] = {
			['elements'] = {
				[7] = {
					['name'] = 'Larnaca Turkish Assault Force 1-7',
					['groupId'] = 329,
					['dead_last'] = false,
					['foundOobGround'] = true,
					['dead'] = true,
				},
				[1] = {
					['name'] = 'Larnaca Turkish Assault Force 1-1',
					['groupId'] = 323,
					['dead_last'] = false,
					['foundOobGround'] = true,
					['dead'] = true,
				},
				[2] = {
					['name'] = 'Larnaca Turkish Assault Force 1-2',
					['groupId'] = 324,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[4] = {
					['name'] = 'Larnaca Turkish Assault Force 1-4',
					['groupId'] = 326,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[8] = {
					['name'] = 'Larnaca Turkish Assault Force 1-8',
					['groupId'] = 330,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[9] = {
					['name'] = 'Larnaca Turkish Assault Force 1-9',
					['groupId'] = 331,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[5] = {
					['name'] = 'Larnaca Turkish Assault Force 1-5',
					['groupId'] = 327,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[10] = {
					['name'] = 'Larnaca Turkish Assault Force 1-10',
					['groupId'] = 332,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[3] = {
					['name'] = 'Larnaca Turkish Assault Force 1-3',
					['groupId'] = 325,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[6] = {
					['name'] = 'Larnaca Turkish Assault Force 1-6',
					['groupId'] = 328,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[12] = {
					['name'] = 'Larnaca Turkish Assault Force 1-12',
					['groupId'] = 334,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[11] = {
					['name'] = 'Larnaca Turkish Assault Force 1-11',
					['groupId'] = 333,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
			},
			['picture'] = {
				[1] = '',
			},
			['x'] = -8220.233564766,
			['class'] = 'static',
			['ATO'] = true,
			['task'] = 'Strike',
			['y'] = -210806.09369903,
			['inactive'] = false,
			['attributes'] = {
				[1] = 'soft',
			},
			['dead_last'] = 0,
			['alive'] = 83,
			['priority'] = 8,
			['foundOobGround'] = true,
			['firepower'] = {
				['min'] = 2,
				['max'] = 6,
			},
		},
		['Airlift Paphos Airbase'] = {
			['ATO'] = true,
			['y'] = -314208.375,
			['x'] = -18696.34668,
			['attributes'] = {
			},
			['firepower'] = {
				['min'] = 1,
				['max'] = 1,
			},
			['task'] = 'Transport',
			['destination'] = 'Paphos Airbase',
			['base'] = 'Kasteli Airbase',
			['priority'] = 1,
		},
		['Turkish Naval Convoy 1'] = {
			['name'] = 'Turkish Naval Convoy 1',
			['elements'] = {
				[1] = {
					['name'] = 'Turkish Naval Convoy 1-1',
					['dead_last'] = false,
				},
				[2] = {
					['name'] = 'Turkish Naval Convoy 1-2',
					['dead_last'] = false,
				},
				[3] = {
					['name'] = 'Turkish Naval Convoy 1-3',
					['dead_last'] = false,
				},
				[4] = {
					['name'] = 'Turkish Naval Convoy 1-4',
					['dead_last'] = false,
				},
				[5] = {
					['name'] = 'Turkish Naval Convoy 1-5',
					['dead_last'] = false,
				},
			},
			['groupId'] = 249,
			['task'] = 'Anti-ship Strike',
			['class'] = 'ship',
			['ATO'] = true,
			['firepower'] = {
				['min'] = 2,
				['max'] = 4,
			},
			['y'] = -2844.6015859381,
			['inactive'] = false,
			['alive'] = 100,
			['dead_last'] = 0,
			['attributes'] = {
				[1] = 'ship',
			},
			['priority'] = 7,
			['foundOobGround'] = true,
			['x'] = 170621.27665262,
		},
		['Turkish Air Defense Hawk battery'] = {
			['elements'] = {
				[1] = {
					['name'] = 'Turkish Air Defence Hawk battery',
					['dead_last'] = false,
				},
				[2] = {
					['name'] = 'Turkish Air Defence Hawk battery-1',
					['dead_last'] = false,
				},
				[3] = {
					['name'] = 'Turkish Air Defence Hawk battery-3',
					['dead_last'] = false,
				},
				[4] = {
					['name'] = 'Turkish Air Defence Hawk battery-4',
					['dead_last'] = false,
				},
				[5] = {
					['name'] = 'Turkish Air Defence Hawk battery-5',
					['dead_last'] = false,
				},
				[6] = {
					['name'] = 'Turkish Air Defence Hawk battery-6',
					['dead_last'] = false,
				},
				[7] = {
					['name'] = 'Turkish Air Defence Hawk battery-7',
					['dead_last'] = false,
				},
				[8] = {
					['name'] = 'Turkish Air Defence Hawk battery-8',
					['dead_last'] = false,
				},
				[9] = {
					['name'] = 'Turkish Air Defence Hawk battery-9',
					['dead_last'] = false,
				},
				[10] = {
					['name'] = 'Turkish Air Defence Hawk battery-10',
					['dead_last'] = false,
				},
				[11] = {
					['name'] = 'Turkish Air Defence Hawk battery-11',
					['dead_last'] = false,
				},
			},
			['groupId'] = 60,
			['alive'] = 100,
			['class'] = 'vehicle',
			['ATO'] = true,
			['foundOobGround'] = true,
			['y'] = -46852.425066318,
			['x'] = 173285.76235831,
			['firepower'] = {
				['min'] = 2,
				['max'] = 4,
			},
			['dead_last'] = 0,
			['name'] = 'Turkish Air Defence Hawk battery',
			['priority'] = 4,
			['task'] = 'Strike',
			['attributes'] = {
				[1] = 'SAM',
			},
		},
		['Ercan Airbase Strategics'] = {
			['elements'] = {
				[6] = {
					['name'] = 'Ercan Airbase Ammo Shelter 1',
					['groupId'] = 53,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[2] = {
					['name'] = 'Ercan Airbase Fuel Tank 4',
					['groupId'] = 49,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[8] = {
					['name'] = 'Ercan Airbase Comm Center',
					['groupId'] = 55,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[3] = {
					['name'] = 'Ercan Airbase Fuel Tank 5',
					['groupId'] = 48,
					['dead_last'] = false,
					['foundOobGround'] = true,
					['dead'] = true,
				},
				[1] = {
					['name'] = 'Ercan Airbase Fuel Tank 3',
					['groupId'] = 50,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[4] = {
					['name'] = 'Ercan Airbase Fuel Tank 6',
					['groupId'] = 51,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[5] = {
					['name'] = 'Ercan Airbase Fuel Tank 7',
					['groupId'] = 52,
					['dead_last'] = false,
					['foundOobGround'] = true,
					['dead'] = true,
				},
				[7] = {
					['name'] = 'Ercan Airbase Ammo Shelter 2',
					['groupId'] = 54,
					['dead_last'] = false,
					['foundOobGround'] = true,
					['dead'] = true,
				},
			},
			['picture'] = {
				[1] = 'Ercan Airbase.png',
			},
			['class'] = 'static',
			['ATO'] = true,
			['attributes'] = {
				[1] = 'Structure',
			},
			['y'] = -218190.22555852,
			['x'] = 24632.062569,
			['alive'] = 62,
			['dead_last'] = 0,
			['foundOobGround'] = true,
			['priority'] = 6,
			['task'] = 'Strike',
			['firepower'] = {
				['min'] = 2,
				['max'] = 6,
			},
		},
		['Pinarbashi Airbase Strategics'] = {
			['elements'] = {
				[6] = {
					['name'] = 'Pinarbashi Airbase Ammo Shelter 1',
					['groupId'] = 8,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[2] = {
					['name'] = 'Pinarbashi Airbase Fuel Tank 2',
					['groupId'] = 4,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[8] = {
					['name'] = 'Pinarbashi Airbase Comm Center',
					['groupId'] = 10,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[3] = {
					['name'] = 'Pinarbashi Airbase Fuel Tank 3',
					['groupId'] = 5,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[1] = {
					['name'] = 'Pinarbashi Airbase Fuel Tank 1',
					['groupId'] = 3,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[4] = {
					['name'] = 'Pinarbashi Airbase Fuel Tank 4',
					['groupId'] = 6,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[5] = {
					['name'] = 'Pinarbashi Airbase Fuel Tank 5',
					['groupId'] = 7,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[7] = {
					['name'] = 'Pinarbashi Airbase Ammo Shelter 2',
					['groupId'] = 9,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
			},
			['picture'] = {
				[1] = 'Pinarbashi Airbase.png',
			},
			['class'] = 'static',
			['ATO'] = true,
			['attributes'] = {
				[1] = 'Structure',
			},
			['y'] = -238743.17459689,
			['x'] = 39022.490818531,
			['alive'] = 100,
			['dead_last'] = 0,
			['foundOobGround'] = true,
			['priority'] = 5,
			['task'] = 'Strike',
			['firepower'] = {
				['min'] = 2,
				['max'] = 6,
			},
		},
		['North Cyprus-Turkish Force 4'] = {
			['elements'] = {
				[1] = {
					['name'] = 'NCTF 4-1',
				},
				[2] = {
					['name'] = 'NCTF 4-2',
				},
				[4] = {
					['name'] = 'NCTF 4-4',
				},
				[8] = {
					['name'] = 'NCTF 4-8',
				},
				[16] = {
					['name'] = 'NCTF 4-16',
				},
				[17] = {
					['name'] = 'NCTF 4-17',
				},
				[9] = {
					['name'] = 'NCTF 4-9',
				},
				[18] = {
					['name'] = 'NCTF 4-18',
				},
				[5] = {
					['name'] = 'NCTF 4-5',
				},
				[10] = {
					['name'] = 'NCTF 4-10',
				},
				[20] = {
					['name'] = 'NCTF 4-20',
				},
				[21] = {
					['name'] = 'NCTF 4-21',
				},
				[11] = {
					['name'] = 'NCTF 4-11',
				},
				[22] = {
					['name'] = 'NCTF 4-22',
				},
				[3] = {
					['name'] = 'NCTF 4-3',
				},
				[6] = {
					['name'] = 'NCTF 4-6',
				},
				[12] = {
					['name'] = 'NCTF 4-12',
				},
				[24] = {
					['name'] = 'NCTF 4-24',
				},
				[13] = {
					['name'] = 'NCTF 4-13',
				},
				[7] = {
					['name'] = 'NCTF 4-7',
				},
				[14] = {
					['name'] = 'NCTF 4-14',
				},
				[15] = {
					['name'] = 'NCTF 4-15',
				},
				[19] = {
					['name'] = 'NCTF 4-19',
				},
				[23] = {
					['name'] = 'NCTF 4-23',
				},
			},
			['picture'] = {
				[1] = '',
			},
			['class'] = 'static',
			['ATO'] = true,
			['x'] = 0,
			['y'] = 0,
			['inactive'] = true,
			['attributes'] = {
				[1] = 'soft',
			},
			['dead_last'] = 0,
			['alive'] = 100,
			['priority'] = 15,
			['task'] = 'Strike',
			['firepower'] = {
				['min'] = 2,
				['max'] = 6,
			},
		},
		['CAP-2-Greek'] = {
			['radius'] = 25000,
			['refpoint'] = 'CAP-2-Greek',
			['text'] = 'above the southern mountains',
			['ATO'] = true,
			['y'] = -251890.59559944,
			['inactive'] = true,
			['attributes'] = {
				[1] = 'Air Forces',
			},
			['x'] = -9033.5114032155,
			['priority'] = 10,
			['task'] = 'CAP',
			['firepower'] = {
				['min'] = 2,
				['max'] = 4,
			},
		},
		['Paphos Airbase Alert'] = {
			['radius'] = 150000,
			['ATO'] = true,
			['inactive'] = false,
			['firepower'] = {
				['min'] = 2,
				['max'] = 4,
			},
			['attributes'] = {
			},
			['priority'] = 10,
			['base'] = 'Paphos Airbase',
			['task'] = 'Intercept',
		},
		['Airlift Paphos Airbase 3'] = {
			['ATO'] = true,
			['x'] = -18696.34668,
			['y'] = -314208.375,
			['inactive'] = false,
			['attributes'] = {
			},
			['task'] = 'Transport',
			['priority'] = 1,
			['destination'] = 'Paphos Airbase',
			['base'] = 'Kasteli Airbase',
			['firepower'] = {
				['min'] = 1,
				['max'] = 1,
			},
		},
		['North Cyprus Force 3'] = {
			['elements'] = {
				[1] = {
					['name'] = 'NCF 3-1',
					['groupId'] = 108,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[13] = {
					['name'] = 'NCF 3-13',
					['groupId'] = 120,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[7] = {
					['name'] = 'NCF 3-7',
					['groupId'] = 114,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[14] = {
					['name'] = 'NCF 3-14',
					['groupId'] = 121,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[2] = {
					['name'] = 'NCF 3-2',
					['groupId'] = 109,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[15] = {
					['name'] = 'NCF 3-15',
					['groupId'] = 122,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[8] = {
					['name'] = 'NCF 3-8',
					['groupId'] = 115,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[16] = {
					['name'] = 'NCF 3-16',
					['groupId'] = 123,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[9] = {
					['name'] = 'NCF 3-9',
					['groupId'] = 116,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[5] = {
					['name'] = 'NCF 3-5',
					['groupId'] = 112,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[10] = {
					['name'] = 'NCF 3-10',
					['groupId'] = 117,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[11] = {
					['name'] = 'NCF 3-11',
					['groupId'] = 118,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[3] = {
					['name'] = 'NCF 3-3',
					['groupId'] = 110,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[6] = {
					['name'] = 'NCF 3-6',
					['groupId'] = 113,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[12] = {
					['name'] = 'NCF 3-12',
					['groupId'] = 119,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[4] = {
					['name'] = 'NCF 3-4',
					['groupId'] = 111,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
			},
			['picture'] = {
				[1] = 'North Cyprus Columns.png',
			},
			['x'] = 19156.584139285,
			['class'] = 'static',
			['ATO'] = true,
			['foundOobGround'] = true,
			['y'] = -232908.59675089,
			['inactive'] = true,
			['attributes'] = {
				[1] = 'soft',
			},
			['dead_last'] = 0,
			['alive'] = 100,
			['priority'] = 8,
			['task'] = 'Strike',
			['firepower'] = {
				['min'] = 2,
				['max'] = 6,
			},
		},
		['North Cyprus-Turkish Force 1'] = {
			['elements'] = {
				[1] = {
					['name'] = 'NCTF 1-1',
					['groupId'] = 222,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[2] = {
					['name'] = 'NCTF 1-2',
					['groupId'] = 223,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[4] = {
					['name'] = 'NCTF 1-4',
					['groupId'] = 225,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[8] = {
					['name'] = 'NCTF 1-8',
					['groupId'] = 229,
					['dead_last'] = false,
					['foundOobGround'] = true,
					['dead'] = true,
				},
				[16] = {
					['name'] = 'NCTF 1-16',
					['groupId'] = 237,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[17] = {
					['name'] = 'NCTF 1-17',
					['groupId'] = 238,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[9] = {
					['name'] = 'NCTF 1-9',
					['groupId'] = 230,
					['dead_last'] = false,
					['foundOobGround'] = true,
					['dead'] = true,
				},
				[18] = {
					['name'] = 'NCTF 1-18',
					['groupId'] = 239,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[5] = {
					['name'] = 'NCTF 1-5',
					['groupId'] = 226,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[10] = {
					['name'] = 'NCTF 1-10',
					['groupId'] = 231,
					['dead_last'] = false,
					['foundOobGround'] = true,
					['dead'] = true,
				},
				[20] = {
					['name'] = 'NCTF 1-20',
					['groupId'] = 241,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[21] = {
					['name'] = 'NCTF 1-21',
					['groupId'] = 242,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[11] = {
					['name'] = 'NCTF 1-11',
					['groupId'] = 232,
					['dead_last'] = true,
					['foundOobGround'] = true,
					['dead'] = true,
				},
				[22] = {
					['name'] = 'NCTF 1-22',
					['groupId'] = 243,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[3] = {
					['name'] = 'NCTF 1-3',
					['groupId'] = 224,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[6] = {
					['name'] = 'NCTF 1-6',
					['groupId'] = 227,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[12] = {
					['name'] = 'NCTF 1-12',
					['groupId'] = 233,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[24] = {
					['name'] = 'NCTF 1-24',
					['groupId'] = 245,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[13] = {
					['name'] = 'NCTF 1-13',
					['groupId'] = 234,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[7] = {
					['name'] = 'NCTF 1-7',
					['groupId'] = 228,
					['dead_last'] = false,
					['foundOobGround'] = true,
					['dead'] = true,
				},
				[14] = {
					['name'] = 'NCTF 1-14',
					['groupId'] = 235,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[15] = {
					['name'] = 'NCTF 1-15',
					['groupId'] = 236,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[19] = {
					['name'] = 'NCTF 1-19',
					['groupId'] = 240,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[23] = {
					['name'] = 'NCTF 1-23',
					['groupId'] = 244,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
			},
			['picture'] = {
				[1] = 'NCTF-1.png',
			},
			['x'] = 24964.948880636,
			['class'] = 'static',
			['ATO'] = true,
			['foundOobGround'] = true,
			['y'] = -233392.0156654,
			['inactive'] = false,
			['attributes'] = {
				[1] = 'soft',
			},
			['dead_last'] = 4,
			['alive'] = 79,
			['priority'] = 18,
			['task'] = 'Strike',
			['firepower'] = {
				['min'] = 2,
				['max'] = 6,
			},
		},
		['EWR-Jaguar'] = {
			['class'] = 'vehicle',
			['ATO'] = true,
			['inactive'] = true,
			['name'] = 'EWR-Jaguar',
			['attributes'] = {
				[1] = 'soft',
			},
			['priority'] = 15,
			['task'] = 'Strike',
			['firepower'] = {
				['min'] = 2,
				['max'] = 6,
			},
		},
		['Turkish Artillery Force 1'] = {
			['name'] = 'Turkish Artillery Force 1',
			['task'] = 'Strike',
			['elements'] = {
				[1] = {
					['name'] = 'Turkish Artillery Force 1-1',
					['dead_last'] = false,
				},
				[2] = {
					['name'] = 'Turkish Artillery Force 1-2',
					['dead_last'] = false,
				},
				[3] = {
					['name'] = 'Turkish Artillery Force 1-3',
					['dead_last'] = false,
				},
				[4] = {
					['name'] = 'Turkish Artillery Force 1-4',
					['dead_last'] = false,
				},
				[5] = {
					['name'] = 'Turkish Artillery Force 1-5',
					['dead_last'] = false,
				},
				[6] = {
					['name'] = 'Turkish Artillery Force 1-6',
					['dead_last'] = false,
				},
				[7] = {
					['name'] = 'Turkish Artillery Force 1-7',
					['dead_last'] = false,
				},
				[8] = {
					['name'] = 'Turkish Artillery Force 1-8',
					['dead_last'] = false,
				},
				[9] = {
					['name'] = 'Turkish Artillery Force 1-9',
					['dead_last'] = false,
				},
				[10] = {
					['name'] = 'Turkish Artillery Force 1-10',
					['dead_last'] = false,
				},
			},
			['groupId'] = 247,
			['inactive'] = false,
			['class'] = 'vehicle',
			['ATO'] = true,
			['alive'] = 100,
			['y'] = -211135.76310928,
			['x'] = 26038.163908177,
			['attributes'] = {
				[1] = 'soft',
			},
			['dead_last'] = 0,
			['firepower'] = {
				['min'] = 2,
				['max'] = 4,
			},
			['priority'] = 7,
			['foundOobGround'] = true,
			['picture'] = {
				[1] = 'TurkishArtillery.png',
			},
		},
		['North Cyprus Force 4'] = {
			['elements'] = {
				[1] = {
					['name'] = 'NCF 4-1',
					['groupId'] = 162,
					['dead_last'] = false,
					['foundOobGround'] = true,
					['dead'] = true,
				},
				[13] = {
					['name'] = 'NCF 4-13',
					['groupId'] = 174,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[7] = {
					['name'] = 'NCF 4-7',
					['groupId'] = 168,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[14] = {
					['name'] = 'NCF 4-14',
					['groupId'] = 175,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[2] = {
					['name'] = 'NCF 4-2',
					['groupId'] = 163,
					['dead_last'] = false,
					['foundOobGround'] = true,
					['dead'] = true,
				},
				[15] = {
					['name'] = 'NCF 4-15',
					['groupId'] = 176,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[8] = {
					['name'] = 'NCF 4-8',
					['groupId'] = 169,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[16] = {
					['name'] = 'NCF 4-16',
					['groupId'] = 177,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[9] = {
					['name'] = 'NCF 4-9',
					['groupId'] = 170,
					['dead_last'] = false,
					['foundOobGround'] = true,
					['dead'] = true,
				},
				[5] = {
					['name'] = 'NCF 4-5',
					['groupId'] = 166,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[10] = {
					['name'] = 'NCF 4-10',
					['groupId'] = 171,
					['dead_last'] = false,
					['foundOobGround'] = true,
					['dead'] = true,
				},
				[11] = {
					['name'] = 'NCF 4-11',
					['groupId'] = 172,
					['dead_last'] = false,
					['foundOobGround'] = true,
					['dead'] = true,
				},
				[3] = {
					['name'] = 'NCF 4-3',
					['groupId'] = 164,
					['dead_last'] = false,
					['foundOobGround'] = true,
					['dead'] = true,
				},
				[6] = {
					['name'] = 'NCF 4-6',
					['groupId'] = 167,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[12] = {
					['name'] = 'NCF 4-12',
					['groupId'] = 173,
					['dead_last'] = false,
					['foundOobGround'] = true,
					['dead'] = true,
				},
				[4] = {
					['name'] = 'NCF 4-4',
					['groupId'] = 165,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
			},
			['picture'] = {
				[1] = 'North Cyprus Columns.png',
			},
			['x'] = 15623.095337749,
			['class'] = 'static',
			['ATO'] = true,
			['foundOobGround'] = true,
			['y'] = -234609.79502465,
			['inactive'] = true,
			['attributes'] = {
				[1] = 'soft',
			},
			['dead_last'] = 0,
			['alive'] = 56,
			['priority'] = 8,
			['task'] = 'Strike',
			['firepower'] = {
				['min'] = 2,
				['max'] = 6,
			},
		},
		['North Cyprus-Turkish Force 2'] = {
			['elements'] = {
				[1] = {
					['name'] = 'NCTF 2-1',
				},
				[2] = {
					['name'] = 'NCTF 2-2',
				},
				[4] = {
					['name'] = 'NCTF 2-4',
				},
				[8] = {
					['name'] = 'NCTF 2-8',
				},
				[16] = {
					['name'] = 'NCTF 2-16',
				},
				[17] = {
					['name'] = 'NCTF 2-17',
				},
				[9] = {
					['name'] = 'NCTF 2-9',
				},
				[18] = {
					['name'] = 'NCTF 2-18',
				},
				[5] = {
					['name'] = 'NCTF 2-5',
				},
				[10] = {
					['name'] = 'NCTF 2-10',
				},
				[20] = {
					['name'] = 'NCTF 2-20',
				},
				[21] = {
					['name'] = 'NCTF 2-21',
				},
				[11] = {
					['name'] = 'NCTF 2-11',
				},
				[22] = {
					['name'] = 'NCTF 2-22',
				},
				[3] = {
					['name'] = 'NCTF 2-3',
				},
				[6] = {
					['name'] = 'NCTF 2-6',
				},
				[12] = {
					['name'] = 'NCTF 2-12',
				},
				[24] = {
					['name'] = 'NCTF 2-24',
				},
				[13] = {
					['name'] = 'NCTF 2-13',
				},
				[7] = {
					['name'] = 'NCTF 2-7',
				},
				[14] = {
					['name'] = 'NCTF 2-14',
				},
				[15] = {
					['name'] = 'NCTF 2-15',
				},
				[19] = {
					['name'] = 'NCTF 2-19',
				},
				[23] = {
					['name'] = 'NCTF 2-23',
				},
			},
			['picture'] = {
				[1] = '',
			},
			['class'] = 'static',
			['ATO'] = true,
			['x'] = 0,
			['y'] = 0,
			['inactive'] = true,
			['attributes'] = {
				[1] = 'soft',
			},
			['dead_last'] = 0,
			['alive'] = 100,
			['priority'] = 19,
			['task'] = 'Strike',
			['firepower'] = {
				['min'] = 2,
				['max'] = 6,
			},
		},
		['Paphos Airbase Alert 3'] = {
			['radius'] = 150000,
			['ATO'] = true,
			['inactive'] = false,
			['firepower'] = {
				['min'] = 2,
				['max'] = 4,
			},
			['attributes'] = {
			},
			['priority'] = 10,
			['base'] = 'Paphos Airbase',
			['task'] = 'Intercept',
		},
		['North Cyprus Force 2'] = {
			['elements'] = {
				[1] = {
					['name'] = 'NCF 2-1',
					['groupId'] = 77,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[13] = {
					['name'] = 'NCF 2-13',
					['groupId'] = 89,
					['dead_last'] = false,
					['foundOobGround'] = true,
					['dead'] = true,
				},
				[7] = {
					['name'] = 'NCF 2-7',
					['groupId'] = 83,
					['dead_last'] = false,
					['foundOobGround'] = true,
					['dead'] = true,
				},
				[14] = {
					['name'] = 'NCF 2-14',
					['groupId'] = 90,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[2] = {
					['name'] = 'NCF 2-2',
					['groupId'] = 78,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[15] = {
					['name'] = 'NCF 2-15',
					['groupId'] = 91,
					['dead_last'] = false,
					['foundOobGround'] = true,
					['dead'] = true,
				},
				[8] = {
					['name'] = 'NCF 2-8',
					['groupId'] = 84,
					['dead_last'] = false,
					['foundOobGround'] = true,
					['dead'] = true,
				},
				[16] = {
					['name'] = 'NCF 2-16',
					['groupId'] = 92,
					['dead_last'] = false,
					['foundOobGround'] = true,
					['dead'] = true,
				},
				[9] = {
					['name'] = 'NCF 2-9',
					['groupId'] = 85,
					['dead_last'] = false,
					['foundOobGround'] = true,
					['dead'] = true,
				},
				[5] = {
					['name'] = 'NCF 2-5',
					['groupId'] = 81,
					['dead_last'] = false,
					['foundOobGround'] = true,
					['dead'] = true,
				},
				[10] = {
					['name'] = 'NCF 2-10',
					['groupId'] = 86,
					['dead_last'] = false,
					['foundOobGround'] = true,
					['dead'] = true,
				},
				[11] = {
					['name'] = 'NCF 2-11',
					['groupId'] = 87,
					['dead_last'] = false,
					['foundOobGround'] = true,
					['dead'] = true,
				},
				[3] = {
					['name'] = 'NCF 2-3',
					['groupId'] = 79,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[6] = {
					['name'] = 'NCF 2-6',
					['groupId'] = 82,
					['dead_last'] = false,
					['foundOobGround'] = true,
					['dead'] = true,
				},
				[12] = {
					['name'] = 'NCF 2-12',
					['groupId'] = 88,
					['dead_last'] = false,
					['foundOobGround'] = true,
					['dead'] = true,
				},
				[4] = {
					['name'] = 'NCF 2-4',
					['groupId'] = 80,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
			},
			['picture'] = {
				[1] = 'North Cyprus Columns.png',
			},
			['x'] = 21422.341367175,
			['class'] = 'static',
			['ATO'] = true,
			['foundOobGround'] = true,
			['y'] = -234646.96379431,
			['inactive'] = true,
			['attributes'] = {
				[1] = 'soft',
			},
			['dead_last'] = 0,
			['alive'] = 31,
			['priority'] = 8,
			['task'] = 'Strike',
			['firepower'] = {
				['min'] = 2,
				['max'] = 6,
			},
		},
		['Turkish Hawk battery 2'] = {
			['class'] = 'vehicle',
			['ATO'] = true,
			['inactive'] = true,
			['name'] = 'Turkish Hawk Battery 2',
			['attributes'] = {
				[1] = 'SAM',
			},
			['priority'] = 10,
			['task'] = 'Strike',
			['firepower'] = {
				['min'] = 2,
				['max'] = 4,
			},
		},
		['Turkish Naval Convoy 2'] = {
			['inactive'] = false,
			['elements'] = {
				[1] = {
					['name'] = 'Turkish Naval Convoy 2-1',
					['dead_last'] = false,
				},
				[2] = {
					['name'] = 'Turkish Naval Convoy 2-2',
					['dead_last'] = false,
				},
				[3] = {
					['name'] = 'Turkish Naval Convoy 2-3',
					['dead_last'] = false,
				},
				[4] = {
					['name'] = 'Turkish Naval Convoy 2-4',
					['dead_last'] = false,
				},
				[5] = {
					['name'] = 'Turkish Naval Convoy 2-5',
					['dead_last'] = false,
				},
			},
			['groupId'] = 338,
			['foundOobGround'] = true,
			['class'] = 'ship',
			['ATO'] = true,
			['alive'] = 100,
			['y'] = -120787.94327444,
			['x'] = 86337.416208017,
			['name'] = 'Turkish Naval Convoy 2',
			['dead_last'] = 0,
			['firepower'] = {
				['min'] = 2,
				['max'] = 4,
			},
			['priority'] = 7,
			['task'] = 'Anti-ship Strike',
			['attributes'] = {
				[1] = 'ship',
			},
		},
		['Paphos Airbase Alert 2'] = {
			['radius'] = 150000,
			['ATO'] = true,
			['inactive'] = false,
			['firepower'] = {
				['min'] = 2,
				['max'] = 4,
			},
			['attributes'] = {
			},
			['priority'] = 10,
			['base'] = 'Paphos Airbase',
			['task'] = 'Intercept',
		},
		['CAP-1-Greek'] = {
			['radius'] = 25000,
			['refpoint'] = 'CAP-1-Greek',
			['text'] = 'above the northern mountains',
			['ATO'] = true,
			['y'] = -263719.4355222,
			['inactive'] = false,
			['attributes'] = {
				[1] = 'Air Forces',
			},
			['x'] = 8148.4937254932,
			['priority'] = 10,
			['task'] = 'CAP',
			['firepower'] = {
				['min'] = 2,
				['max'] = 4,
			},
		},
		['Gecitkale Airbase'] = {
			['elements'] = {
				[7] = {
					['y'] = -197066.125,
					['x'] = 31708.072265625,
					['name'] = 'Gecitkale Airbase Fuel Center 3',
					['dead_last'] = false,
				},
				[1] = {
					['y'] = -197081.40625,
					['x'] = 31778.408203125,
					['name'] = 'Gecitkale Airbase Hangar 1',
					['dead_last'] = false,
				},
				[2] = {
					['y'] = -197275.140625,
					['x'] = 31780.9921875,
					['name'] = 'Gecitkale Airbase Hangar 2',
					['dead_last'] = false,
				},
				[4] = {
					['y'] = -197172.515625,
					['x'] = 31722.947265625,
					['name'] = 'Gecitkale Airbase HQ',
					['dead_last'] = false,
				},
				[8] = {
					['y'] = -196892.140625,
					['x'] = 31769.33203125,
					['name'] = 'Gecitkale Airbase Ammunition Center 1',
					['dead_last'] = false,
				},
				[9] = {
					['y'] = -196907.1875,
					['x'] = 31740.33984375,
					['name'] = 'Gecitkale Airbase Ammunition Center 2',
					['dead_last'] = false,
				},
				[5] = {
					['y'] = -197090.421875,
					['x'] = 31710.345703125,
					['name'] = 'Gecitkale Airbase Fuel Center 1',
					['dead_last'] = false,
				},
				[10] = {
					['y'] = -196881.953125,
					['x'] = 31739.53515625,
					['name'] = 'Gecitkale Airbase Ammunition Center 3',
					['dead_last'] = false,
				},
				[3] = {
					['y'] = -197333.5625,
					['x'] = 31690.203125,
					['name'] = 'Gecitkale Airbase Hangar 3',
					['dead_last'] = false,
				},
				[6] = {
					['y'] = -197077.125,
					['x'] = 31708.5546875,
					['name'] = 'Gecitkale Airbase Fuel Center 2',
					['dead_last'] = false,
				},
				[11] = {
					['y'] = -196895.890625,
					['x'] = 31708.921875,
					['name'] = 'Gecitkale Airbase Ammunition Center 4',
					['dead_last'] = false,
				},
			},
			['picture'] = {
				[1] = 'Gecitkale Airbase.png',
			},
			['ATO'] = true,
			['y'] = -197061.22443182,
			['x'] = 31732.513849432,
			['firepower'] = {
				['min'] = 2,
				['max'] = 6,
			},
			['dead_last'] = 0,
			['alive'] = 100,
			['priority'] = 5,
			['task'] = 'Strike',
			['attributes'] = {
				[1] = 'Structure',
			},
		},
		['Airlift Paphos Airbase 2'] = {
			['ATO'] = true,
			['x'] = -18696.34668,
			['y'] = -314208.375,
			['inactive'] = false,
			['attributes'] = {
			},
			['task'] = 'Transport',
			['priority'] = 1,
			['destination'] = 'Paphos Airbase',
			['base'] = 'Kasteli Airbase',
			['firepower'] = {
				['min'] = 1,
				['max'] = 1,
			},
		},
		['North Cyprus-Turkish Force 3'] = {
			['elements'] = {
				[1] = {
					['name'] = 'NCTF 3-1',
				},
				[2] = {
					['name'] = 'NCTF 3-2',
				},
				[4] = {
					['name'] = 'NCTF 3-4',
				},
				[8] = {
					['name'] = 'NCTF 3-8',
				},
				[16] = {
					['name'] = 'NCTF 3-16',
				},
				[17] = {
					['name'] = 'NCTF 3-17',
				},
				[9] = {
					['name'] = 'NCTF 3-9',
				},
				[18] = {
					['name'] = 'NCTF 3-18',
				},
				[5] = {
					['name'] = 'NCTF 3-5',
				},
				[10] = {
					['name'] = 'NCTF 3-10',
				},
				[20] = {
					['name'] = 'NCTF 3-20',
				},
				[21] = {
					['name'] = 'NCTF 3-21',
				},
				[11] = {
					['name'] = 'NCTF 3-11',
				},
				[22] = {
					['name'] = 'NCTF 3-22',
				},
				[3] = {
					['name'] = 'NCTF 3-3',
				},
				[6] = {
					['name'] = 'NCTF 3-6',
				},
				[12] = {
					['name'] = 'NCTF 3-12',
				},
				[24] = {
					['name'] = 'NCTF 3-24',
				},
				[13] = {
					['name'] = 'NCTF 3-13',
				},
				[7] = {
					['name'] = 'NCTF 3-7',
				},
				[14] = {
					['name'] = 'NCTF 3-14',
				},
				[15] = {
					['name'] = 'NCTF 3-15',
				},
				[19] = {
					['name'] = 'NCTF 3-19',
				},
				[23] = {
					['name'] = 'NCTF 3-23',
				},
			},
			['picture'] = {
				[1] = '',
			},
			['class'] = 'static',
			['ATO'] = true,
			['x'] = 0,
			['y'] = 0,
			['inactive'] = true,
			['attributes'] = {
				[1] = 'soft',
			},
			['dead_last'] = 0,
			['alive'] = 100,
			['priority'] = 19,
			['task'] = 'Strike',
			['firepower'] = {
				['min'] = 2,
				['max'] = 6,
			},
		},
	},
	['red'] = {
		['Cyprus Border Force 3'] = {
			['elements'] = {
				[7] = {
					['name'] = 'CBF 3-7',
					['groupId'] = 102,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[1] = {
					['name'] = 'CBF 3-1',
					['groupId'] = 96,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[2] = {
					['name'] = 'CBF 3-2',
					['groupId'] = 97,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[4] = {
					['name'] = 'CBF 3-4',
					['groupId'] = 106,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[8] = {
					['name'] = 'CBF 3-8',
					['groupId'] = 103,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[9] = {
					['name'] = 'CBF 3-9',
					['groupId'] = 104,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[5] = {
					['name'] = 'CBF 3-5',
					['groupId'] = 100,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[10] = {
					['name'] = 'CBF 3-10',
					['groupId'] = 105,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[3] = {
					['name'] = 'CBF 3-3',
					['groupId'] = 98,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[6] = {
					['name'] = 'CBF 3-6',
					['groupId'] = 101,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
			},
			['picture'] = {
				[1] = '',
			},
			['x'] = 20063.165825731,
			['class'] = 'static',
			['ATO'] = true,
			['foundOobGround'] = true,
			['y'] = -235114.26699233,
			['inactive'] = false,
			['attributes'] = {
				[1] = 'soft',
			},
			['dead_last'] = 0,
			['alive'] = 100,
			['priority'] = 9,
			['task'] = 'Strike',
			['firepower'] = {
				['min'] = 2,
				['max'] = 4,
			},
		},
		['Cyprus Defense Force 5'] = {
			['elements'] = {
				[7] = {
					['name'] = 'CDF 5-7',
					['groupId'] = 301,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[1] = {
					['name'] = 'CDF 5-1',
					['groupId'] = 295,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[2] = {
					['name'] = 'CDF 5-2',
					['groupId'] = 296,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[4] = {
					['name'] = 'CDF 5-4',
					['groupId'] = 298,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[8] = {
					['name'] = 'CDF 5-8',
					['groupId'] = 302,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[9] = {
					['name'] = 'CDF 5-9',
					['groupId'] = 303,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[5] = {
					['name'] = 'CDF 5-5',
					['groupId'] = 299,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[10] = {
					['name'] = 'CDF 5-10',
					['groupId'] = 304,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[3] = {
					['name'] = 'CDF 5-3',
					['groupId'] = 297,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[6] = {
					['name'] = 'CDF 5-6',
					['groupId'] = 300,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
			},
			['picture'] = {
				[1] = '',
			},
			['x'] = 32553.796311966,
			['class'] = 'static',
			['ATO'] = true,
			['task'] = 'Strike',
			['y'] = -298734.2453818,
			['inactive'] = false,
			['attributes'] = {
				[1] = 'soft',
			},
			['dead_last'] = 0,
			['alive'] = 100,
			['priority'] = 15,
			['foundOobGround'] = true,
			['firepower'] = {
				['min'] = 2,
				['max'] = 4,
			},
		},
		['Airlift Ercan Airbase'] = {
			['ATO'] = true,
			['y'] = -218240.28125,
			['x'] = 24250.327148,
			['attributes'] = {
			},
			['firepower'] = {
				['min'] = 1,
				['max'] = 1,
			},
			['task'] = 'Transport',
			['destination'] = 'Ercan Airbase',
			['base'] = 'Incirlik Airbase',
			['priority'] = 1,
		},
		['Paphos Airbase Strategics'] = {
			['elements'] = {
				[13] = {
					['name'] = 'Paphos Airbase Comm Center',
					['groupId'] = 32,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[7] = {
					['name'] = 'Paphos Airbase Ammo Shelter 1',
					['groupId'] = 26,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[1] = {
					['name'] = 'Paphos Airbase Fuel Tank 1',
					['groupId'] = 20,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[2] = {
					['name'] = 'Paphos Airbase Fuel Tank 2',
					['groupId'] = 21,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[4] = {
					['name'] = 'Paphos Airbase Fuel Tank 4',
					['groupId'] = 23,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[8] = {
					['name'] = 'Paphos Airbase Ammo Shelter 2',
					['groupId'] = 27,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[9] = {
					['name'] = 'Paphos Airbase Ammo Shelter 3',
					['groupId'] = 28,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[5] = {
					['name'] = 'Paphos Airbase Fuel Tank 5',
					['groupId'] = 24,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[10] = {
					['name'] = 'Paphos Airbase Ammo Shelter 4',
					['groupId'] = 29,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[3] = {
					['name'] = 'Paphos Airbase Fuel Tank 3',
					['groupId'] = 22,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[6] = {
					['name'] = 'Paphos Airbase Fuel Tank 6',
					['groupId'] = 25,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[12] = {
					['name'] = 'Paphos Airbase Ammo Shelter 6',
					['groupId'] = 31,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[11] = {
					['name'] = 'Paphos Airbase Ammo Shelter 5',
					['groupId'] = 30,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
			},
			['picture'] = {
				[1] = 'Paphos Airbase-East.png, Paphos Airbase-West.png',
			},
			['class'] = 'static',
			['ATO'] = true,
			['attributes'] = {
				[1] = 'Structure',
			},
			['y'] = -313234.10714136,
			['x'] = -19170.162007173,
			['alive'] = 100,
			['dead_last'] = 0,
			['foundOobGround'] = true,
			['priority'] = 7,
			['task'] = 'Strike',
			['firepower'] = {
				['min'] = 2,
				['max'] = 6,
			},
		},
		['Airlift Ercan Airbase 2'] = {
			['ATO'] = true,
			['x'] = 24250.327148,
			['y'] = -218240.28125,
			['inactive'] = false,
			['attributes'] = {
			},
			['task'] = 'Transport',
			['priority'] = 1,
			['destination'] = 'Ercan Airbase',
			['base'] = 'Incirlik Airbase',
			['firepower'] = {
				['min'] = 1,
				['max'] = 1,
			},
		},
		['EWR-Moonbeam'] = {
			['class'] = 'vehicle',
			['ATO'] = true,
			['inactive'] = true,
			['name'] = 'EWR-Moonbeam',
			['attributes'] = {
				[1] = 'soft',
			},
			['priority'] = 15,
			['task'] = 'Strike',
			['firepower'] = {
				['min'] = 2,
				['max'] = 6,
			},
		},
		['Cyprus Border Force 5'] = {
			['elements'] = {
				[7] = {
					['name'] = 'CBF 5-7',
					['groupId'] = 187,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[1] = {
					['name'] = 'CBF 5-1',
					['groupId'] = 181,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[2] = {
					['name'] = 'CBF 5-2',
					['groupId'] = 182,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[4] = {
					['name'] = 'CBF 5-4',
					['groupId'] = 184,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[8] = {
					['name'] = 'CBF 5-8',
					['groupId'] = 188,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[9] = {
					['name'] = 'CBF 5-9',
					['groupId'] = 189,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[5] = {
					['name'] = 'CBF 5-5',
					['groupId'] = 185,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[10] = {
					['name'] = 'CBF 5-10',
					['groupId'] = 190,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[3] = {
					['name'] = 'CBF 5-3',
					['groupId'] = 183,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[6] = {
					['name'] = 'CBF 5-6',
					['groupId'] = 186,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
			},
			['picture'] = {
				[1] = '',
			},
			['x'] = 16488.965215061,
			['class'] = 'static',
			['ATO'] = true,
			['foundOobGround'] = true,
			['y'] = -234374.92860868,
			['inactive'] = false,
			['attributes'] = {
				[1] = 'soft',
			},
			['dead_last'] = 0,
			['alive'] = 100,
			['priority'] = 9,
			['task'] = 'Strike',
			['firepower'] = {
				['min'] = 2,
				['max'] = 4,
			},
		},
		['Greek Expeditionary Force 2'] = {
			['elements'] = {
				[13] = {
					['name'] = 'GEF 2-13',
				},
				[7] = {
					['name'] = 'GEF 2-7',
				},
				[1] = {
					['name'] = 'GEF 2-1',
				},
				[2] = {
					['name'] = 'GEF 2-2',
				},
				[4] = {
					['name'] = 'GEF 2-4',
				},
				[8] = {
					['name'] = 'GEF 2-8',
				},
				[14] = {
					['name'] = 'GEF 2-14',
				},
				[9] = {
					['name'] = 'GEF 2-9',
				},
				[5] = {
					['name'] = 'GEF 2-5',
				},
				[10] = {
					['name'] = 'GEF 2-10',
				},
				[11] = {
					['name'] = 'GEF 2-11',
				},
				[3] = {
					['name'] = 'GEF 2-3',
				},
				[6] = {
					['name'] = 'GEF 2-6',
				},
				[12] = {
					['name'] = 'GEF 2-12',
				},
				[15] = {
					['name'] = 'GEF 2-15',
				},
			},
			['picture'] = {
				[1] = '',
			},
			['class'] = 'static',
			['ATO'] = true,
			['x'] = 0,
			['y'] = 0,
			['inactive'] = true,
			['attributes'] = {
				[1] = 'soft',
			},
			['dead_last'] = 0,
			['alive'] = 100,
			['priority'] = 15,
			['task'] = 'Strike',
			['firepower'] = {
				['min'] = 2,
				['max'] = 6,
			},
		},
		['Cyprus Defense Force 4'] = {
			['elements'] = {
				[7] = {
					['name'] = 'CDF 4-7',
					['groupId'] = 290,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[1] = {
					['name'] = 'CDF 4-1',
					['groupId'] = 284,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[2] = {
					['name'] = 'CDF 4-2',
					['groupId'] = 285,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[4] = {
					['name'] = 'CDF 4-4',
					['groupId'] = 287,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[8] = {
					['name'] = 'CDF 4-8',
					['groupId'] = 291,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[9] = {
					['name'] = 'CDF 4-9',
					['groupId'] = 292,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[5] = {
					['name'] = 'CDF 4-5',
					['groupId'] = 288,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[10] = {
					['name'] = 'CDF 4-10',
					['groupId'] = 293,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[3] = {
					['name'] = 'CDF 4-3',
					['groupId'] = 286,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[6] = {
					['name'] = 'CDF 4-6',
					['groupId'] = 289,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
			},
			['picture'] = {
				[1] = '',
			},
			['x'] = 9357.9608637227,
			['class'] = 'static',
			['ATO'] = true,
			['task'] = 'Strike',
			['y'] = -265798.18096998,
			['inactive'] = false,
			['attributes'] = {
				[1] = 'soft',
			},
			['dead_last'] = 0,
			['alive'] = 100,
			['priority'] = 15,
			['foundOobGround'] = true,
			['firepower'] = {
				['min'] = 2,
				['max'] = 4,
			},
		},
		['Cyprus Defense Force 1'] = {
			['elements'] = {
				[7] = {
					['name'] = 'CDF 1-7',
					['groupId'] = 257,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[1] = {
					['name'] = 'CDF 1-1',
					['groupId'] = 251,
					['dead_last'] = false,
					['foundOobGround'] = true,
					['dead'] = true,
				},
				[2] = {
					['name'] = 'CDF 1-2',
					['groupId'] = 252,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[4] = {
					['name'] = 'CDF 1-4',
					['groupId'] = 254,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[8] = {
					['name'] = 'CDF 1-8',
					['groupId'] = 258,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[9] = {
					['name'] = 'CDF 1-9',
					['groupId'] = 259,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[5] = {
					['name'] = 'CDF 1-5',
					['groupId'] = 255,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[10] = {
					['name'] = 'CDF 1-10',
					['groupId'] = 260,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[3] = {
					['name'] = 'CDF 1-3',
					['groupId'] = 253,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[6] = {
					['name'] = 'CDF 1-6',
					['groupId'] = 256,
					['dead_last'] = false,
					['foundOobGround'] = true,
					['dead'] = true,
				},
			},
			['picture'] = {
				[1] = '',
			},
			['x'] = -10241.316037592,
			['class'] = 'static',
			['ATO'] = true,
			['task'] = 'Strike',
			['y'] = -224580.71580592,
			['inactive'] = false,
			['attributes'] = {
				[1] = 'soft',
			},
			['dead_last'] = 0,
			['alive'] = 80,
			['priority'] = 19,
			['foundOobGround'] = true,
			['firepower'] = {
				['min'] = 2,
				['max'] = 4,
			},
		},
		['Greek Hawk Battery 1'] = {
			['class'] = 'vehicle',
			['ATO'] = true,
			['inactive'] = true,
			['name'] = 'Greek Hawk Battery 1',
			['attributes'] = {
				[1] = 'SAM',
			},
			['priority'] = 6,
			['task'] = 'Strike',
			['firepower'] = {
				['min'] = 2,
				['max'] = 6,
			},
		},
		['Cyprus Border Force 2'] = {
			['elements'] = {
				[7] = {
					['name'] = 'CBF 2-7',
					['groupId'] = 217,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[1] = {
					['name'] = 'CBF 2-1',
					['groupId'] = 211,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[2] = {
					['name'] = 'CBF 2-2',
					['groupId'] = 212,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[4] = {
					['name'] = 'CBF 2-4',
					['groupId'] = 214,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[8] = {
					['name'] = 'CBF 2-8',
					['groupId'] = 218,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[9] = {
					['name'] = 'CBF 2-9',
					['groupId'] = 219,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[5] = {
					['name'] = 'CBF 2-5',
					['groupId'] = 215,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[10] = {
					['name'] = 'CBF 2-10',
					['groupId'] = 220,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[3] = {
					['name'] = 'CBF 2-3',
					['groupId'] = 213,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[6] = {
					['name'] = 'CBF 2-6',
					['groupId'] = 216,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
			},
			['picture'] = {
				[1] = '',
			},
			['x'] = 16652.685100226,
			['class'] = 'static',
			['ATO'] = true,
			['foundOobGround'] = true,
			['y'] = -234710.59807184,
			['inactive'] = false,
			['attributes'] = {
				[1] = 'soft',
			},
			['dead_last'] = 0,
			['alive'] = 100,
			['priority'] = 9,
			['task'] = 'Strike',
			['firepower'] = {
				['min'] = 2,
				['max'] = 4,
			},
		},
		['Airlift Pinarbashi Airbase'] = {
			['ATO'] = true,
			['y'] = -238774.6875,
			['x'] = 38639.882813,
			['attributes'] = {
			},
			['firepower'] = {
				['min'] = 1,
				['max'] = 1,
			},
			['task'] = 'Transport',
			['destination'] = 'Pinarbashi Airbase',
			['base'] = 'Incirlik Airbase',
			['priority'] = 1,
		},
		['Larnaca Cyprus defenses'] = {
			['x'] = -11952.607853438,
			['elements'] = {
				[1] = {
					['name'] = 'Larnaca Cyprus defenses-1',
					['dead_last'] = false,
				},
				[2] = {
					['name'] = 'Larnaca Cyprus defenses-2',
					['dead_last'] = false,
				},
				[3] = {
					['name'] = 'Larnaca Cyprus defenses-3',
					['dead_last'] = false,
				},
				[4] = {
					['name'] = 'Larnaca Cyprus defenses-4',
					['dead_last'] = false,
				},
				[5] = {
					['name'] = 'Larnaca Cyprus defenses-5',
					['dead_last'] = false,
				},
				[6] = {
					['name'] = 'Larnaca Cyprus defenses-6',
					['dead_last'] = false,
				},
				[7] = {
					['name'] = 'Larnaca Cyprus defenses-7',
					['dead_last'] = false,
				},
				[8] = {
					['name'] = 'Larnaca Cyprus defenses-8',
					['dead_last'] = false,
				},
				[9] = {
					['name'] = 'Larnaca Cyprus defenses-9',
					['dead_last'] = false,
				},
				[10] = {
					['name'] = 'Larnaca Cyprus defenses-10',
					['dead_last'] = false,
				},
				[11] = {
					['name'] = 'Larnaca Cyprus defenses-11',
					['dead_last'] = false,
				},
				[12] = {
					['name'] = 'Larnaca Cyprus defenses-12',
					['dead_last'] = false,
				},
			},
			['groupId'] = 160,
			['foundOobGround'] = true,
			['class'] = 'vehicle',
			['ATO'] = true,
			['alive'] = 100,
			['y'] = -219508.70845348,
			['inactive'] = false,
			['name'] = 'Larnaca Cyprus defenses',
			['dead_last'] = 0,
			['attributes'] = {
				[1] = 'soft',
			},
			['priority'] = 8,
			['task'] = 'Strike',
			['firepower'] = {
				['min'] = 2,
				['max'] = 4,
			},
		},
		['Lakatamia Airbase'] = {
			['elements'] = {
				[6] = {
					['y'] = -234483.703125,
					['x'] = 19572.984375,
					['name'] = 'Lakatamia Airbase Fuel Center 1',
					['dead_last'] = false,
				},
				[2] = {
					['y'] = -234596.453125,
					['x'] = 19634.013671875,
					['name'] = 'Lakatamia Airbase Hangar 2',
					['dead_last'] = false,
				},
				[8] = {
					['y'] = -234570.28942871,
					['x'] = 19496.873535156,
					['name'] = 'Lakatamia Airbase HQ Center',
					['dead_last'] = false,
				},
				[3] = {
					['y'] = -234545.234375,
					['x'] = 19550.201171875,
					['name'] = 'Lakatamia Airbase Hangar 3',
					['dead_last'] = false,
				},
				[1] = {
					['y'] = -234754.40625,
					['x'] = 19646.927734375,
					['name'] = 'Lakatamia Airbase Hangar 1',
					['dead_last'] = false,
				},
				[4] = {
					['y'] = -234598.8125,
					['x'] = 19576.947265625,
					['name'] = 'Lakatamia Hangar 4',
					['dead_last'] = false,
				},
				[5] = {
					['y'] = -234495.171875,
					['x'] = 19516.8671875,
					['name'] = 'Lakatamia Hangar 5',
					['dead_last'] = false,
				},
				[7] = {
					['y'] = -234853.109375,
					['x'] = 19692.42578125,
					['name'] = 'Lakatamia Airbase Ammunition Center',
					['dead_last'] = false,
				},
			},
			['picture'] = {
				[1] = 'Lakatamia Airbase.png',
			},
			['ATO'] = true,
			['y'] = -234612.14750671,
			['x'] = 19585.905090332,
			['firepower'] = {
				['min'] = 2,
				['max'] = 6,
			},
			['dead_last'] = 0,
			['alive'] = 100,
			['priority'] = 10,
			['task'] = 'Strike',
			['attributes'] = {
				[1] = 'Structure',
			},
		},
		['Cyprus Defense Force 3'] = {
			['elements'] = {
				[7] = {
					['name'] = 'CDF 3-7',
					['groupId'] = 279,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[1] = {
					['name'] = 'CDF 3-1',
					['groupId'] = 273,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[2] = {
					['name'] = 'CDF 3-2',
					['groupId'] = 274,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[4] = {
					['name'] = 'CDF 3-4',
					['groupId'] = 276,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[8] = {
					['name'] = 'CDF 3-8',
					['groupId'] = 280,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[9] = {
					['name'] = 'CDF 3-9',
					['groupId'] = 281,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[5] = {
					['name'] = 'CDF 3-5',
					['groupId'] = 277,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[10] = {
					['name'] = 'CDF 3-10',
					['groupId'] = 282,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[3] = {
					['name'] = 'CDF 3-3',
					['groupId'] = 275,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[6] = {
					['name'] = 'CDF 3-6',
					['groupId'] = 278,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
			},
			['picture'] = {
				[1] = '',
			},
			['x'] = 11042.069429839,
			['class'] = 'static',
			['ATO'] = true,
			['task'] = 'Strike',
			['y'] = -250525.12754574,
			['inactive'] = false,
			['attributes'] = {
				[1] = 'soft',
			},
			['dead_last'] = 0,
			['alive'] = 100,
			['priority'] = 15,
			['foundOobGround'] = true,
			['firepower'] = {
				['min'] = 2,
				['max'] = 4,
			},
		},
		['Cyprus Border Force 4'] = {
			['elements'] = {
				[7] = {
					['name'] = 'CBF 4-7',
					['groupId'] = 133,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[1] = {
					['name'] = 'CBF 4-1',
					['groupId'] = 127,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[2] = {
					['name'] = 'CBF 4-2',
					['groupId'] = 128,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[4] = {
					['name'] = 'CBF 4-4',
					['groupId'] = 130,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[8] = {
					['name'] = 'CBF 4-8',
					['groupId'] = 134,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[9] = {
					['name'] = 'CBF 4-9',
					['groupId'] = 135,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[5] = {
					['name'] = 'CBF 4-5',
					['groupId'] = 131,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[10] = {
					['name'] = 'CBF 4-10',
					['groupId'] = 136,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[3] = {
					['name'] = 'CBF 4-3',
					['groupId'] = 129,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[6] = {
					['name'] = 'CBF 4-6',
					['groupId'] = 132,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
			},
			['picture'] = {
				[1] = '',
			},
			['x'] = 19643.378396579,
			['class'] = 'static',
			['ATO'] = true,
			['foundOobGround'] = true,
			['y'] = -234138.9552839,
			['inactive'] = false,
			['attributes'] = {
				[1] = 'soft',
			},
			['dead_last'] = 0,
			['alive'] = 100,
			['priority'] = 9,
			['task'] = 'Strike',
			['firepower'] = {
				['min'] = 2,
				['max'] = 4,
			},
		},
		['Greek Expeditionary Force 1'] = {
			['elements'] = {
				[13] = {
					['name'] = 'GEF 1-13',
				},
				[7] = {
					['name'] = 'GEF 1-7',
				},
				[1] = {
					['name'] = 'GEF 1-1',
				},
				[2] = {
					['name'] = 'GEF 1-2',
				},
				[4] = {
					['name'] = 'GEF 1-4',
				},
				[8] = {
					['name'] = 'GEF 1-8',
				},
				[14] = {
					['name'] = 'GEF 1-14',
				},
				[9] = {
					['name'] = 'GEF 1-9',
				},
				[5] = {
					['name'] = 'GEF 1-5',
				},
				[10] = {
					['name'] = 'GEF 1-10',
				},
				[11] = {
					['name'] = 'GEF 1-11',
				},
				[3] = {
					['name'] = 'GEF 1-3',
				},
				[6] = {
					['name'] = 'GEF 1-6',
				},
				[12] = {
					['name'] = 'GEF 1-12',
				},
				[15] = {
					['name'] = 'GEF 1-15',
				},
			},
			['picture'] = {
				[1] = '',
			},
			['class'] = 'static',
			['ATO'] = true,
			['x'] = 0,
			['y'] = 0,
			['inactive'] = true,
			['attributes'] = {
				[1] = 'soft',
			},
			['dead_last'] = 0,
			['alive'] = 100,
			['priority'] = 15,
			['task'] = 'Strike',
			['firepower'] = {
				['min'] = 2,
				['max'] = 6,
			},
		},
		['Greek Expeditionary Force 3'] = {
			['elements'] = {
				[13] = {
					['name'] = 'GEF 3-13',
				},
				[7] = {
					['name'] = 'GEF 3-7',
				},
				[1] = {
					['name'] = 'GEF 3-1',
				},
				[2] = {
					['name'] = 'GEF 3-2',
				},
				[4] = {
					['name'] = 'GEF 3-4',
				},
				[8] = {
					['name'] = 'GEF 3-8',
				},
				[14] = {
					['name'] = 'GEF 3-14',
				},
				[9] = {
					['name'] = 'GEF 3-9',
				},
				[5] = {
					['name'] = 'GEF 3-5',
				},
				[10] = {
					['name'] = 'GEF 3-10',
				},
				[11] = {
					['name'] = 'GEF 3-11',
				},
				[3] = {
					['name'] = 'GEF 3-3',
				},
				[6] = {
					['name'] = 'GEF 3-6',
				},
				[12] = {
					['name'] = 'GEF 3-12',
				},
				[15] = {
					['name'] = 'GEF 3-15',
				},
			},
			['picture'] = {
				[1] = '',
			},
			['class'] = 'static',
			['ATO'] = true,
			['x'] = 0,
			['y'] = 0,
			['inactive'] = true,
			['attributes'] = {
				[1] = 'soft',
			},
			['dead_last'] = 0,
			['alive'] = 100,
			['priority'] = 15,
			['task'] = 'Strike',
			['firepower'] = {
				['min'] = 2,
				['max'] = 6,
			},
		},
		['Airlift Ercan Airbase 3'] = {
			['ATO'] = true,
			['x'] = 24250.327148,
			['y'] = -218240.28125,
			['inactive'] = false,
			['attributes'] = {
			},
			['task'] = 'Transport',
			['priority'] = 1,
			['destination'] = 'Ercan Airbase',
			['base'] = 'Incirlik Airbase',
			['firepower'] = {
				['min'] = 1,
				['max'] = 1,
			},
		},
		['EWR-Eyeball'] = {
			['x'] = 3391.7327427695,
			['elements'] = {
				[1] = {
					['name'] = 'EWR-Eyeball-1',
					['dead_last'] = false,
				},
				[2] = {
					['name'] = 'EWR-Eyeball-2',
					['dead_last'] = false,
				},
				[3] = {
					['name'] = 'EWR-Eyeball-3',
					['dead_last'] = false,
				},
				[4] = {
					['name'] = 'EWR-Eyeball-4',
					['dead_last'] = false,
				},
				[5] = {
					['name'] = 'EWR-Eyeball-5',
					['dead_last'] = false,
				},
			},
			['groupId'] = 44,
			['foundOobGround'] = true,
			['class'] = 'vehicle',
			['ATO'] = true,
			['alive'] = 100,
			['y'] = -277962.99187681,
			['inactive'] = false,
			['name'] = 'EWR-Eyeball',
			['dead_last'] = 0,
			['attributes'] = {
				[1] = 'soft',
			},
			['priority'] = 20,
			['task'] = 'Strike',
			['firepower'] = {
				['min'] = 2,
				['max'] = 6,
			},
		},
		['Cyprus Defense Force 2'] = {
			['elements'] = {
				[7] = {
					['name'] = 'CDF 2-7',
					['groupId'] = 268,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[1] = {
					['name'] = 'CDF 2-1',
					['groupId'] = 262,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[2] = {
					['name'] = 'CDF 2-2',
					['groupId'] = 263,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[4] = {
					['name'] = 'CDF 2-4',
					['groupId'] = 265,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[8] = {
					['name'] = 'CDF 2-8',
					['groupId'] = 269,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[9] = {
					['name'] = 'CDF 2-9',
					['groupId'] = 270,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[5] = {
					['name'] = 'CDF 2-5',
					['groupId'] = 266,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[10] = {
					['name'] = 'CDF 2-10',
					['groupId'] = 271,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[3] = {
					['name'] = 'CDF 2-3',
					['groupId'] = 264,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[6] = {
					['name'] = 'CDF 2-6',
					['groupId'] = 267,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
			},
			['picture'] = {
				[1] = '',
			},
			['x'] = -2105.0307554887,
			['class'] = 'static',
			['ATO'] = true,
			['task'] = 'Strike',
			['y'] = -228555.63670467,
			['inactive'] = false,
			['attributes'] = {
				[1] = 'soft',
			},
			['dead_last'] = 0,
			['alive'] = 100,
			['priority'] = 15,
			['foundOobGround'] = true,
			['firepower'] = {
				['min'] = 2,
				['max'] = 4,
			},
		},
		['CAP-1-Turkish'] = {
			['radius'] = 50000,
			['refpoint'] = 'CAP-1-Turkish',
			['text'] = 'Near Ercan',
			['ATO'] = true,
			['y'] = -212334.31801357,
			['inactive'] = false,
			['attributes'] = {
			},
			['x'] = 15006.556433443,
			['priority'] = 20,
			['task'] = 'CAP',
			['firepower'] = {
				['min'] = 2,
				['max'] = 2,
			},
		},
		['Greek Naval Convoy'] = {
			['inactive'] = false,
			['elements'] = {
				[1] = {
					['name'] = 'Greek Naval Convoy-1',
					['dead_last'] = false,
				},
				[2] = {
					['name'] = 'Greek Naval Convoy-2',
					['dead_last'] = false,
				},
				[3] = {
					['name'] = 'Greek Naval Convoy-3',
					['dead_last'] = false,
				},
				[4] = {
					['name'] = 'Greek Naval Convoy-4',
					['dead_last'] = false,
				},
				[5] = {
					['name'] = 'Greek Naval Convoy-5',
					['dead_last'] = false,
				},
				[6] = {
					['name'] = 'Greek Naval Convoy-6',
					['dead_last'] = false,
				},
				[7] = {
					['name'] = 'Greek Naval Convoy-7',
					['dead_last'] = false,
				},
				[8] = {
					['name'] = 'Greek Naval Convoy-8',
					['dead_last'] = false,
				},
				[9] = {
					['name'] = 'Greek Naval Convoy-9',
					['dead_last'] = false,
				},
			},
			['groupId'] = 337,
			['foundOobGround'] = true,
			['class'] = 'ship',
			['ATO'] = true,
			['alive'] = 100,
			['y'] = -426498.16714441,
			['x'] = -23265.507418276,
			['name'] = 'Greek Naval Convoy',
			['dead_last'] = 0,
			['firepower'] = {
				['min'] = 2,
				['max'] = 4,
			},
			['priority'] = 8,
			['task'] = 'Anti-ship Strike',
			['attributes'] = {
				[1] = 'ship',
			},
		},
		['Lakatamia Airbase Strategics'] = {
			['elements'] = {
				[6] = {
					['name'] = 'Lakatamia Airbase Comm Center',
					['groupId'] = 19,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[2] = {
					['name'] = 'Lakatamia Airbase Fuel Tank 2',
					['groupId'] = 15,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[3] = {
					['name'] = 'Lakatamia Airbase Fuel Tank 3',
					['groupId'] = 16,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[1] = {
					['name'] = 'Lakatamia Airbase Fuel Tank 1',
					['groupId'] = 14,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[4] = {
					['name'] = 'Lakatamia Airbase Ammo Shelter 1',
					['groupId'] = 17,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[5] = {
					['name'] = 'Lakatamia Airbase Ammo Shelter 2',
					['groupId'] = 18,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
			},
			['picture'] = {
				[1] = 'Lakatamia Airbase.png',
			},
			['class'] = 'static',
			['ATO'] = true,
			['attributes'] = {
				[1] = 'Structure',
			},
			['y'] = -234577.98930364,
			['x'] = 19566.357286996,
			['alive'] = 100,
			['dead_last'] = 0,
			['foundOobGround'] = true,
			['priority'] = 10,
			['task'] = 'Strike',
			['firepower'] = {
				['min'] = 2,
				['max'] = 6,
			},
		},
		['Greek Expeditionary Force 4'] = {
			['elements'] = {
				[13] = {
					['name'] = 'GEF 4-13',
					['groupId'] = 318,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[7] = {
					['name'] = 'GEF 4-7',
					['groupId'] = 312,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[1] = {
					['name'] = 'GEF 4-1',
					['groupId'] = 306,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[2] = {
					['name'] = 'GEF 4-2',
					['groupId'] = 307,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[4] = {
					['name'] = 'GEF 4-4',
					['groupId'] = 309,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[8] = {
					['name'] = 'GEF 4-8',
					['groupId'] = 313,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[14] = {
					['name'] = 'GEF 4-14',
					['groupId'] = 319,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[9] = {
					['name'] = 'GEF 4-9',
					['groupId'] = 314,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[5] = {
					['name'] = 'GEF 4-5',
					['groupId'] = 310,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[10] = {
					['name'] = 'GEF 4-10',
					['groupId'] = 315,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[11] = {
					['name'] = 'GEF 4-11',
					['groupId'] = 316,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[3] = {
					['name'] = 'GEF 4-3',
					['groupId'] = 308,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[6] = {
					['name'] = 'GEF 4-6',
					['groupId'] = 311,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[12] = {
					['name'] = 'GEF 4-12',
					['groupId'] = 317,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[15] = {
					['name'] = 'GEF 4-15',
					['groupId'] = 320,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
			},
			['picture'] = {
				[1] = '',
			},
			['x'] = -10246.721612351,
			['class'] = 'static',
			['ATO'] = true,
			['task'] = 'Strike',
			['y'] = -292846.8181932,
			['inactive'] = false,
			['attributes'] = {
				[1] = 'soft',
			},
			['dead_last'] = 0,
			['alive'] = 100,
			['priority'] = 15,
			['foundOobGround'] = true,
			['firepower'] = {
				['min'] = 2,
				['max'] = 6,
			},
		},
		['Greek Naval Convoy 2'] = {
			['attributes'] = {
				[1] = 'ship',
			},
			['elements'] = {
				[1] = {
					['name'] = 'Naval-1-1',
					['dead_last'] = false,
				},
				[2] = {
					['name'] = 'Naval-1-2',
					['dead_last'] = false,
				},
				[3] = {
					['name'] = 'Naval-1-3',
					['dead_last'] = false,
				},
				[4] = {
					['name'] = 'Naval-1-4',
					['dead_last'] = false,
				},
				[5] = {
					['name'] = 'Naval-1-5',
					['dead_last'] = false,
				},
				[6] = {
					['name'] = 'Naval-1-6',
					['dead_last'] = false,
				},
				[7] = {
					['name'] = 'Naval-1-7',
					['dead_last'] = false,
				},
				[8] = {
					['name'] = 'Naval-1-8',
					['dead_last'] = false,
				},
				[9] = {
					['name'] = 'Naval-1-9',
					['dead_last'] = false,
				},
			},
			['groupId'] = 340,
			['task'] = 'Anti-ship Strike',
			['class'] = 'ship',
			['ATO'] = true,
			['firepower'] = {
				['min'] = 2,
				['max'] = 4,
			},
			['y'] = -520923.17004777,
			['x'] = -13191.085627819,
			['alive'] = 100,
			['dead_last'] = 0,
			['name'] = 'Greek Naval Convoy 2',
			['priority'] = 8,
			['foundOobGround'] = true,
			['inactive'] = false,
		},
		['Gecitkale Airbase Alert'] = {
			['radius'] = 150000,
			['ATO'] = true,
			['inactive'] = true,
			['firepower'] = {
				['min'] = 2,
				['max'] = 2,
			},
			['attributes'] = {
			},
			['priority'] = 10,
			['base'] = 'Gecitkale Airbase',
			['task'] = 'Intercept',
		},
		['Cyprus Border Force 1'] = {
			['elements'] = {
				[7] = {
					['name'] = 'CBF 1-7',
					['groupId'] = 155,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[1] = {
					['name'] = 'CBF 1-1',
					['groupId'] = 149,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[2] = {
					['name'] = 'CBF 1-2',
					['groupId'] = 150,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[4] = {
					['name'] = 'CBF 1-4',
					['groupId'] = 152,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[8] = {
					['name'] = 'CBF 1-8',
					['groupId'] = 156,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[9] = {
					['name'] = 'CBF 1-9',
					['groupId'] = 157,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[5] = {
					['name'] = 'CBF 1-5',
					['groupId'] = 153,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[10] = {
					['name'] = 'CBF 1-10',
					['groupId'] = 158,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[3] = {
					['name'] = 'CBF 1-3',
					['groupId'] = 151,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[6] = {
					['name'] = 'CBF 1-6',
					['groupId'] = 154,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
			},
			['picture'] = {
				[1] = '',
			},
			['x'] = 21914.585993284,
			['class'] = 'static',
			['ATO'] = true,
			['foundOobGround'] = true,
			['y'] = -240415.41897325,
			['inactive'] = false,
			['attributes'] = {
				[1] = 'soft',
			},
			['dead_last'] = 0,
			['alive'] = 100,
			['priority'] = 9,
			['task'] = 'Strike',
			['firepower'] = {
				['min'] = 2,
				['max'] = 4,
			},
		},
		['Cyprus Border Force 6'] = {
			['elements'] = {
				[7] = {
					['name'] = 'CBF 6-7',
					['groupId'] = 144,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[1] = {
					['name'] = 'CBF 6-1',
					['groupId'] = 138,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[2] = {
					['name'] = 'CBF 6-2',
					['groupId'] = 139,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[4] = {
					['name'] = 'CBF 6-4',
					['groupId'] = 141,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[8] = {
					['name'] = 'CBF 6-8',
					['groupId'] = 145,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[9] = {
					['name'] = 'CBF 6-9',
					['groupId'] = 146,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[5] = {
					['name'] = 'CBF 6-5',
					['groupId'] = 142,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[10] = {
					['name'] = 'CBF 6-10',
					['groupId'] = 147,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[3] = {
					['name'] = 'CBF 6-3',
					['groupId'] = 140,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
				[6] = {
					['name'] = 'CBF 6-6',
					['groupId'] = 143,
					['dead_last'] = false,
					['foundOobGround'] = true,
				},
			},
			['picture'] = {
				[1] = '',
			},
			['x'] = 13881.39588021,
			['class'] = 'static',
			['ATO'] = true,
			['foundOobGround'] = true,
			['y'] = -228720.54090693,
			['inactive'] = false,
			['attributes'] = {
				[1] = 'soft',
			},
			['dead_last'] = 0,
			['alive'] = 100,
			['priority'] = 9,
			['task'] = 'Strike',
			['firepower'] = {
				['min'] = 2,
				['max'] = 4,
			},
		},
		['Paphos Airbase'] = {
			['elements'] = {
				[1] = {
					['y'] = -312600.03222656,
					['x'] = -18970.557373047,
					['name'] = 'Paphos Airbase Hangar 1',
					['dead_last'] = false,
				},
				[2] = {
					['y'] = -313370.76660156,
					['x'] = -18443.332763672,
					['name'] = 'Paphos Airbase Hangar 2',
					['dead_last'] = false,
				},
				[4] = {
					['y'] = -313267.73095703,
					['x'] = -18592.135253906,
					['name'] = 'Paphos Airbase Hangar 4',
					['dead_last'] = false,
				},
				[8] = {
					['y'] = -314656.69482422,
					['x'] = -19434.475341797,
					['name'] = 'Paphos Airbase Hangar 8',
					['dead_last'] = false,
				},
				[16] = {
					['y'] = -312949.79418945,
					['x'] = -19562.781982422,
					['name'] = 'Paphos Airbase Hangar 16',
					['dead_last'] = false,
				},
				[17] = {
					['y'] = -314399.90625,
					['x'] = -18019.25,
					['name'] = 'Paphos Airbase Control Tower',
					['dead_last'] = false,
				},
				[9] = {
					['y'] = -314470.6809082,
					['x'] = -19417.127197266,
					['name'] = 'Paphos Airbase Hangar 9',
					['dead_last'] = false,
				},
				[18] = {
					['y'] = -314847.95922852,
					['x'] = -18985.5078125,
					['name'] = 'Paphos Airbase Fuel Center 1',
					['dead_last'] = false,
				},
				[5] = {
					['y'] = -313286.84545898,
					['x'] = -18635.128417969,
					['name'] = 'Paphos Airbase Hangar 5',
					['dead_last'] = false,
				},
				[10] = {
					['y'] = -314399.09716797,
					['x'] = -19372.338134766,
					['name'] = 'Paphos Airbase Hangar 10',
					['dead_last'] = false,
				},
				[20] = {
					['y'] = -314793.69116211,
					['x'] = -19044.806396484,
					['name'] = 'Paphos Airbase Fuel Center 3',
					['dead_last'] = false,
				},
				[21] = {
					['y'] = -314808.59179688,
					['x'] = -19064.6640625,
					['name'] = 'Paphos Airbase Fuel Center 4',
					['dead_last'] = false,
				},
				[11] = {
					['y'] = -314328.46728516,
					['x'] = -19446.130859375,
					['name'] = 'Paphos Airbase Hangar 11',
					['dead_last'] = false,
				},
				[22] = {
					['y'] = -314778.92260742,
					['x'] = -19014.573730469,
					['name'] = 'Paphos Airbase Fuel Center 5',
					['dead_last'] = false,
				},
				[3] = {
					['y'] = -313248.66479492,
					['x'] = -18549.159179688,
					['name'] = 'Paphos Airbase Hangar 3',
					['dead_last'] = false,
				},
				[6] = {
					['y'] = -314636.11132813,
					['x'] = -19215.415039063,
					['name'] = 'Paphos Airbase Hangar 6',
					['dead_last'] = false,
				},
				[12] = {
					['y'] = -314296.63623047,
					['x'] = -19445.470214844,
					['name'] = 'Paphos Airbase Hangar 12',
					['dead_last'] = false,
				},
				[24] = {
					['y'] = -311921.83557129,
					['x'] = -19182.064453125,
					['name'] = 'Paphos Airbase Ammunition Center 2',
					['dead_last'] = false,
				},
				[25] = {
					['y'] = -311991.56835938,
					['x'] = -19249.852539063,
					['name'] = 'Paphos Airbase Ammunition Center 3',
					['dead_last'] = false,
				},
				[13] = {
					['y'] = -314349.0234375,
					['x'] = -19423.604736328,
					['name'] = 'Paphos Airbase Hangar 13',
					['dead_last'] = false,
				},
				[26] = {
					['y'] = -311975.57275391,
					['x'] = -19188.873046875,
					['name'] = 'Paphos Airbase Ammunition Center 4',
					['dead_last'] = false,
				},
				[15] = {
					['y'] = -313093.27880859,
					['x'] = -19493.819335938,
					['name'] = 'Paphos Airbase Hangar 15',
					['dead_last'] = false,
				},
				[27] = {
					['y'] = -312123.74328613,
					['x'] = -19146.786376953,
					['name'] = 'Paphos Airbase Command Center 1',
					['dead_last'] = false,
				},
				[14] = {
					['y'] = -314361.12451172,
					['x'] = -19451.284912109,
					['name'] = 'Paphos Airbase Hangar 14',
					['dead_last'] = false,
				},
				[28] = {
					['y'] = -312174.23431396,
					['x'] = -19121.478759766,
					['name'] = 'Paphos Airbase Command Center 2',
					['dead_last'] = false,
				},
				[19] = {
					['y'] = -314853.44555664,
					['x'] = -19042.829833984,
					['name'] = 'Paphos Airbase Fuel Center 2',
					['dead_last'] = false,
				},
				[23] = {
					['y'] = -311951.76513672,
					['x'] = -19291.002441406,
					['name'] = 'Paphos Airbase Ammunition Center 1',
					['dead_last'] = false,
				},
				[7] = {
					['y'] = -314601.00341797,
					['x'] = -19231.55078125,
					['name'] = 'Paphos Airbase Hangar 7',
					['dead_last'] = false,
				},
			},
			['picture'] = {
				[1] = 'Paphos Airbase-East.png, Paphos Airbase-West.png',
			},
			['ATO'] = true,
			['y'] = -313662.04243469,
			['x'] = -19108.428606306,
			['firepower'] = {
				['min'] = 2,
				['max'] = 6,
			},
			['dead_last'] = 0,
			['alive'] = 100,
			['priority'] = 7,
			['task'] = 'Strike',
			['attributes'] = {
				[1] = 'Structure',
			},
		},
	},
}
