oob_air = {
	['blue'] = {
		[1] = {
			['number'] = 16,
			['type'] = 'F-14B',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Strike'] = false,
				['Fighter Sweep'] = false,
				['Escort'] = true,
				['CAP'] = true,
				['Intercept'] = true,
			},
			['skill'] = 'High',
			['liveryModex'] = {
				[100] = 'vf-143 pukin dogs cag',
				[110] = 'vf-143 pukin dogs low vis (1995)',
				[114] = 'vf-143 pukin dogs low vis',
			},
			['tasksCoef'] = {
				['Strike'] = 1,
				['Fighter Sweep'] = 1,
				['Escort'] = 1,
				['Laser Illumination'] = 1,
				['SEAD'] = 1,
				['CAP'] = 1,
				['Intercept'] = 1,
			},
			['player'] = false,
			['name'] = 'VF-143',
			['livery'] = {
				[1] = 'vf-143 pukin dogs low vis',
				[2] = 'vf-143 pukin dogs low vis (1995)',
			},
			['sidenumber'] = {
				[1] = 100,
				[2] = 115,
			},
			['base'] = 'CVN-74 John C. Stennis',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 16,
			},
		},
		[2] = {
			['number'] = 16,
			['type'] = 'F-14B',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Strike'] = false,
				['Fighter Sweep'] = false,
				['Escort'] = true,
				['CAP'] = true,
				['Intercept'] = true,
			},
			['skill'] = 'High',
			['liveryModex'] = {
				[100] = 'vf-101 red',
				[105] = 'vf-101 grim reapers low vis',
				[111] = 'vf-101 dark',
			},
			['tasksCoef'] = {
				['Strike'] = 1,
				['Fighter Sweep'] = 1,
				['Escort'] = 1,
				['Laser Illumination'] = 1,
				['SEAD'] = 1,
				['CAP'] = 1,
				['Intercept'] = 1,
			},
			['player'] = false,
			['name'] = 'VF-101',
			['livery'] = {
				[1] = 'vf-101 grim reapers low vis',
				[2] = 'vf-101 dark',
			},
			['sidenumber'] = {
				[1] = 100,
				[2] = 115,
			},
			['base'] = 'CVN-71 Theodore Roosevelt',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 16,
			},
		},
		[3] = {
			['number'] = 12,
			['type'] = 'S-3B Tanker',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Refueling'] = true,
			},
			['skill'] = 'High',
			['sidenumber'] = {
				[1] = 430,
				[2] = 450,
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 12,
			},
			['name'] = '175 ARW',
			['livery'] = '',
			['base'] = 'CVN-71 Theodore Roosevelt',
		},
		[4] = {
			['number'] = 16,
			['type'] = 'FA-18C_hornet',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Strike'] = true,
				['Fighter Sweep'] = false,
				['Escort'] = true,
				['SEAD'] = true,
				['Anti-ship Strike'] = true,
				['CAP'] = true,
				['Intercept'] = false,
			},
			['skill'] = 'High',
			['liveryModex'] = {
				[200] = 'vfa-106 high visibility',
			},
			['tasksCoef'] = {
				['Strike'] = 1.5,
				['Fighter Sweep'] = 0.2,
				['Escort'] = 0.5,
				['Laser Illumination'] = 1,
				['SEAD'] = 2,
				['Anti-ship Strike'] = 2,
				['CAP'] = 0.2,
				['Intercept'] = 1,
			},
			['player'] = false,
			['name'] = 'VFA-106',
			['livery'] = 'vfa-106',
			['sidenumber'] = {
				[1] = 200,
				[2] = 215,
			},
			['base'] = 'CVN-71 Theodore Roosevelt',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 16,
			},
		},
		[5] = {
			['number'] = 4,
			['type'] = 'AV8BNA',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Strike'] = true,
				['Anti-ship Strike'] = true,
				['SEAD'] = false,
			},
			['skill'] = 'High',
			['liveryModex'] = {
				[100] = 'vma-311d',
			},
			['tasksCoef'] = {
				['Strike'] = 3,
				['Fighter Sweep'] = 0.2,
				['Escort'] = 0.5,
				['Laser Illumination'] = 1,
				['SEAD'] = 1,
				['Anti-ship Strike'] = 2,
				['CAP'] = 0.2,
				['Intercept'] = 1,
			},
			['inactive'] = false,
			['name'] = 'VMA 311',
			['player'] = true,
			['livery'] = 'vma-311',
			['sidenumber'] = {
				[1] = 100,
				[2] = 103,
			},
			['base'] = 'LHA_Tarawa',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 4,
			},
		},
		[6] = {
			['number'] = 30,
			['inactive'] = true,
			['name'] = 'VMA 331',
			['type'] = 'AV8BNA',
			['tasks'] = {
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 30,
			},
			['base'] = 'Reserves',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
		},
		[7] = {
			['number'] = 28,
			['type'] = 'FA-18C_hornet',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 28,
			},
			['name'] = 'R/VMFA-312',
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[8] = {
			['number'] = 12,
			['type'] = 'B-52H',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Strike'] = true,
			},
			['skill'] = 'High',
			['sidenumber'] = {
				[1] = 20,
				[2] = 50,
			},
			['inactive'] = false,
			['name'] = '69 BS',
			['livery'] = 'usaf standard',
			['base'] = 'Dyess AFB',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 12,
			},
		},
		[9] = {
			['number'] = 16,
			['type'] = 'FA-18C_hornet',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Strike'] = true,
				['Fighter Sweep'] = false,
				['Escort'] = false,
				['SEAD'] = true,
				['Anti-ship Strike'] = false,
				['CAP'] = false,
				['Intercept'] = true,
			},
			['skill'] = 'High',
			['liveryModex'] = {
				[200] = 'vmfa-312 high visibility',
			},
			['tasksCoef'] = {
				['Strike'] = 1.5,
				['Fighter Sweep'] = 0.2,
				['Escort'] = 0.5,
				['Laser Illumination'] = 1,
				['SEAD'] = 2,
				['Anti-ship Strike'] = 2,
				['CAP'] = 0.2,
				['Intercept'] = 1,
			},
			['player'] = false,
			['name'] = 'VMFA-312',
			['livery'] = 'vmfa-312',
			['sidenumber'] = {
				[1] = 200,
				[2] = 215,
			},
			['base'] = 'CVN-74 John C. Stennis',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 16,
			},
		},
		[10] = {
			['number'] = 24,
			['type'] = 'F-14B',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'High',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 24,
			},
			['name'] = 'R/VF-101',
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[11] = {
			['number'] = 12,
			['type'] = 'S-3B Tanker',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Refueling'] = true,
			},
			['skill'] = 'High',
			['sidenumber'] = {
				[1] = 400,
				[2] = 429,
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 12,
			},
			['name'] = '174 ARW',
			['livery'] = '',
			['base'] = 'CVN-71 Theodore Roosevelt',
		},
		[12] = {
			['number'] = 1,
			['type'] = 'E-2C',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
			},
			['skill'] = 'High',
			['inactive'] = true,
			['name'] = 'R/VAW-125',
			['base'] = 'Reserves',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 1,
			},
		},
		[13] = {
			['number'] = 30,
			['type'] = 'F-14B',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'High',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 30,
			},
			['name'] = 'R/VF-143',
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[14] = {
			['number'] = 28,
			['type'] = 'F/A-18C',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 28,
			},
			['name'] = 'R/VFA-106',
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[15] = {
			['number'] = 10,
			['type'] = 'S-3B Tanker',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
			},
			['skill'] = 'High',
			['inactive'] = true,
			['name'] = 'R/174 ARW',
			['base'] = 'Reserves',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 10,
			},
		},
		[16] = {
			['number'] = 8,
			['type'] = 'E-2C',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['AWACS'] = true,
			},
			['skill'] = 'High',
			['sidenumber'] = {
				[1] = 600,
				[2] = 609,
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 8,
			},
			['name'] = 'VAW-125',
			['livery'] = '',
			['base'] = 'CVN-71 Theodore Roosevelt',
		},
	},
	['red'] = {
		[1] = {
			['number'] = 8,
			['type'] = 'MiG-31',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['CAP'] = true,
				['Fighter Sweep'] = true,
				['Escort'] = true,
				['Intercept'] = true,
			},
			['skill'] = 'high',
			['sidenumber'] = {
				[1] = 200,
				[2] = 245,
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 8,
			},
			['name'] = '174.IAP-PVO',
			['livery'] = {
				[1] = '',
			},
			['base'] = 'Mozdok',
		},
		[2] = {
			['number'] = 10,
			['type'] = 'MiG-29A',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['CAP'] = true,
				['Fighter Sweep'] = true,
				['Escort'] = true,
				['Intercept'] = true,
			},
			['skill'] = 'Random',
			['sidenumber'] = {
				[1] = 10,
				[2] = 45,
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 10,
			},
			['name'] = '19.IAP',
			['livery'] = {
				[1] = '',
			},
			['base'] = 'Batumi',
		},
		[3] = {
			['number'] = 12,
			['type'] = 'Su-24M',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['Strike'] = false,
				['Anti-ship Strike'] = true,
				['SEAD'] = false,
				['Laser Illumination'] = false,
			},
			['skill'] = 'high',
			['sidenumber'] = {
				[1] = 350,
				[2] = 385,
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 12,
			},
			['name'] = '559.BAP',
			['livery'] = '',
			['base'] = 'Senaki-Kolkhi',
		},
		[4] = {
			['number'] = 24,
			['type'] = 'Su-27',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'Random',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 24,
			},
			['name'] = 'R/3.IAP',
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[5] = {
			['number'] = 24,
			['type'] = 'Tu-142',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'high',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 24,
			},
			['name'] = 'R/79.TBAP',
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[6] = {
			['number'] = 12,
			['type'] = 'Su-27',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['CAP'] = true,
				['Fighter Sweep'] = true,
				['Escort'] = true,
				['Intercept'] = true,
			},
			['skill'] = 'Random',
			['sidenumber'] = {
				[1] = 150,
				[2] = 195,
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 12,
			},
			['name'] = '3.IAP',
			['livery'] = '',
			['base'] = 'Kutaisi',
		},
		[7] = {
			['number'] = 4,
			['type'] = 'A-50',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['AWACS'] = true,
			},
			['skill'] = 'high',
			['sidenumber'] = {
				[1] = 800,
				[2] = 805,
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 4,
			},
			['name'] = '2457 SDRLO',
			['livery'] = {
				[1] = '',
			},
			['base'] = 'Nalchik',
		},
		[8] = {
			['number'] = 24,
			['type'] = 'MiG-29A',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'Random',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 24,
			},
			['name'] = 'R/31.IAP',
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[9] = {
			['number'] = 6,
			['type'] = 'Tu-22M3',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['Strike'] = false,
				['Anti-ship Strike'] = true,
			},
			['skill'] = 'high',
			['sidenumber'] = {
				[1] = 600,
				[2] = 645,
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 6,
			},
			['name'] = '52.TBAP',
			['livery'] = {
				[1] = '',
			},
			['base'] = 'Mineralnye-Vody',
		},
		[10] = {
			['number'] = 6,
			['type'] = 'Su-24MR',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['Reconnaissance'] = true,
			},
			['skill'] = 'High',
			['sidenumber'] = {
				[1] = 400,
				[2] = 410,
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 6,
			},
			['name'] = '11.RAP',
			['livery'] = 'af standard',
			['base'] = 'Maykop-Khanskaya',
		},
		[11] = {
			['number'] = 24,
			['type'] = 'Su-25TM',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'Random',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 24,
			},
			['name'] = 'R/368.ShAP',
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[12] = {
			['number'] = 24,
			['type'] = 'Tu-22M3',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'high',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 24,
			},
			['name'] = 'R/52.TBAP',
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[13] = {
			['number'] = 24,
			['type'] = 'MiG-31',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'high',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 24,
			},
			['name'] = 'R/174.IAP-PVO',
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[14] = {
			['number'] = 18,
			['type'] = 'Su-24M',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'high',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 18,
			},
			['name'] = 'R/559.BAP',
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[15] = {
			['number'] = 12,
			['type'] = 'MiG-29A',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['CAP'] = true,
				['Fighter Sweep'] = true,
				['Escort'] = true,
				['Intercept'] = true,
			},
			['skill'] = 'Random',
			['sidenumber'] = {
				[1] = 100,
				[2] = 145,
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 12,
			},
			['name'] = '28.IAP',
			['livery'] = '',
			['base'] = 'Gudauta',
		},
		[16] = {
			['number'] = 24,
			['type'] = 'Su-24M',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'high',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 24,
			},
			['name'] = 'R/959.BAP',
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[17] = {
			['number'] = 24,
			['type'] = 'MiG-29A',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'Random',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 24,
			},
			['name'] = 'R/28.IAP',
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[18] = {
			['number'] = 12,
			['type'] = 'Su-24M',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['Strike'] = false,
				['Anti-ship Strike'] = true,
				['SEAD'] = false,
			},
			['skill'] = 'high',
			['sidenumber'] = {
				[1] = 420,
				[2] = 445,
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 12,
			},
			['name'] = '959.BAP',
			['livery'] = '',
			['base'] = 'Kutaisi',
		},
		[19] = {
			['number'] = 16,
			['type'] = 'Su-25TM',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['Strike'] = false,
				['Anti-ship Strike'] = true,
				['SEAD'] = false,
			},
			['skill'] = 'Random',
			['sidenumber'] = {
				[1] = 300,
				[2] = 345,
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 16,
			},
			['name'] = '368.ShAP',
			['livery'] = '',
			['base'] = 'Kobuleti',
		},
		[20] = {
			['number'] = 24,
			['type'] = 'MiG-29A',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'Random',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 24,
			},
			['name'] = 'R/19.IAP',
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[21] = {
			['number'] = 12,
			['type'] = 'MiG-29A',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['CAP'] = true,
				['Fighter Sweep'] = true,
				['Escort'] = true,
				['Intercept'] = true,
			},
			['skill'] = 'Random',
			['sidenumber'] = {
				[1] = 50,
				[2] = 95,
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 12,
			},
			['name'] = '31.IAP',
			['livery'] = '',
			['base'] = 'Sukhumi',
		},
		[22] = {
			['number'] = 6,
			['type'] = 'Tu-142',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['Strike'] = false,
				['Anti-ship Strike'] = true,
			},
			['skill'] = 'high',
			['sidenumber'] = {
				[1] = 600,
				[2] = 645,
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 6,
			},
			['name'] = '79.TBAP',
			['livery'] = {
				[1] = '',
			},
			['base'] = 'Tbilissi-Lochini',
		},
	},
}
TypeAlias = {
}
