oob_air = {
	['blue'] = {
		[1] = {
			['number'] = 16,
			['type'] = 'F-14B',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Strike'] = false,
				['Fighter Sweep'] = true,
				['Escort'] = true,
				['CAP'] = false,
				['Intercept'] = true,
			},
			['skill'] = 'High',
			['player'] = true,
			['name'] = 'VF-101',
			['livery'] = {
				[1] = 'VF-101 Grim Reapers Low Vis',
				[2] = 'VF-101 Dark',
			},
			['base'] = 'CVN-71 Theodore Roosevelt',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 16,
			},
		},
		[2] = {
			['number'] = 24,
			['type'] = 'F-16C_50',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'United Arab Emirates',
			['tasks'] = {
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 24,
			},
			['name'] = '2nd Shaheen Squadron Res',
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[3] = {
			['number'] = 9,
			['type'] = 'KC135MPRS',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
			},
			['skill'] = 'High',
			['inactive'] = true,
			['name'] = 'R/171 ARW',
			['base'] = 'Reserves',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 9,
			},
		},
		[4] = {
			['number'] = 28,
			['type'] = 'F/A-18C',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 28,
			},
			['name'] = 'R/VFA-131',
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[5] = {
			['number'] = 18,
			['type'] = 'M-2000C',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'United Arab Emirates',
			['tasks'] = {
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 18,
			},
			['name'] = '71st FS Res',
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[6] = {
			['number'] = 30,
			['inactive'] = true,
			['name'] = 'VMA 331',
			['type'] = 'AV8BNA',
			['tasks'] = {
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 30,
			},
			['base'] = 'Reserves',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
		},
		[7] = {
			['number'] = 32,
			['type'] = 'SA342M',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'high',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 32,
			},
			['name'] = '3eme RHA',
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[8] = {
			['number'] = 16,
			['type'] = 'FA-18C_hornet',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Strike'] = false,
				['Fighter Sweep'] = false,
				['Escort'] = false,
				['SEAD'] = true,
				['Anti-ship Strike'] = false,
				['CAP'] = false,
				['Intercept'] = true,
			},
			['skill'] = 'High',
			['player'] = false,
			['name'] = 'VFA-192',
			['livery'] = 'VFA-192',
			['base'] = 'CVN-74 John C. Stennis',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 16,
			},
		},
		[9] = {
			['number'] = 16,
			['type'] = 'F-14B',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Strike'] = false,
				['Fighter Sweep'] = false,
				['Escort'] = false,
				['CAP'] = true,
				['Intercept'] = true,
			},
			['skill'] = 'High',
			['sidenumber'] = {
				[1] = 300,
				[2] = 315,
			},
			['player'] = false,
			['name'] = 'VF-32',
			['livery'] = {
				[1] = 'VF-32 Fighting Swordsmen 101',
				[2] = 'VF-32 Fighting Swordsmen 102',
				[3] = 'VF-32 Fighting Swordsmen 103',
			},
			['base'] = 'CVN-74 John C. Stennis',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 16,
			},
		},
		[10] = {
			['number'] = 1,
			['type'] = 'CH-47D',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Transport'] = true,
			},
			['skill'] = 'High',
			['helicopter'] = true,
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 1,
			},
			['name'] = '41 TAS',
			['livery'] = '',
			['base'] = 'LHA_Nassau',
		},
		[11] = {
			['number'] = 12,
			['type'] = 'F-16C_50',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'United Arab Emirates',
			['tasks'] = {
				['Strike'] = true,
				['Fighter Sweep'] = true,
				['Escort'] = true,
				['Laser Illumination'] = false,
				['SEAD'] = false,
				['CAP'] = true,
				['Intercept'] = true,
			},
			['skill'] = 'High',
			['player'] = false,
			['name'] = '2nd Shaheen Squadron',
			['livery'] = 'UAE',
			['base'] = 'Dubai Intl',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 12,
			},
		},
		[12] = {
			['number'] = 4,
			['type'] = 'E-2C',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['AWACS'] = true,
			},
			['skill'] = 'High',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 4,
			},
			['name'] = 'VAW-125',
			['livery'] = 'VAW-125 Tigertails',
			['base'] = 'CVN-71 Theodore Roosevelt',
		},
		[13] = {
			['number'] = 12,
			['type'] = 'M-2000C',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'United Arab Emirates',
			['tasks'] = {
				['Strike'] = true,
				['Fighter Sweep'] = true,
				['Escort'] = true,
				['CAP'] = true,
				['Intercept'] = true,
			},
			['skill'] = 'High',
			['player'] = false,
			['name'] = '71st FS',
			['livery'] = {
				[1] = 'UAE Air Force',
			},
			['base'] = 'Al Dhafra AB',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 12,
			},
		},
		[14] = {
			['number'] = 6,
			['type'] = 'S-3B Tanker',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Refueling'] = true,
			},
			['skill'] = 'High',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 6,
			},
			['name'] = '174 ARW',
			['livery'] = '',
			['base'] = 'CVN-71 Theodore Roosevelt',
		},
		[15] = {
			['number'] = 18,
			['type'] = 'A-10C_2',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 18,
			},
			['name'] = '74th FS Res',
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[16] = {
			['number'] = 24,
			['type'] = 'F-14B',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'High',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 24,
			},
			['name'] = 'R/VF-101',
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[17] = {
			['number'] = 4,
			['type'] = 'A-10C_2',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Strike'] = true,
				['Fighter Sweep'] = false,
				['Escort'] = false,
				['CAP'] = false,
				['Anti-ship Strike'] = true,
			},
			['skill'] = 'High',
			['player'] = false,
			['name'] = '74th FS',
			['livery'] = {
				[1] = '74th fs moody afb, georgia (ft)',
			},
			['base'] = 'Sharjah Intl',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 4,
			},
		},
		[18] = {
			['number'] = 6,
			['type'] = 'KC-135',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
			},
			['skill'] = 'High',
			['inactive'] = true,
			['name'] = 'R/175 ARW',
			['base'] = 'Reserves',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 6,
			},
		},
		[19] = {
			['number'] = 6,
			['type'] = 'CH-47D',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
			},
			['skill'] = 'High',
			['inactive'] = true,
			['name'] = 'R/41 TAS',
			['base'] = 'Reserves',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 6,
			},
		},
		[20] = {
			['number'] = 4,
			['type'] = 'SA342M',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'France',
			['tasks'] = {
				['Strike'] = true,
			},
			['skill'] = 'high',
			['helicopter'] = true,
			['player'] = false,
			['name'] = '4eme RHA',
			['livery'] = {
				[1] = '',
			},
			['base'] = 'Jazirat al Hamra FARP',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 4,
			},
		},
		[21] = {
			['number'] = 30,
			['type'] = 'F-14B',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'High',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 30,
			},
			['name'] = 'R/VF-32',
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[22] = {
			['number'] = 28,
			['type'] = 'FA-18C_hornet',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 28,
			},
			['name'] = 'R/VFA-192',
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[23] = {
			['number'] = 3,
			['type'] = 'KC135MPRS',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Refueling'] = true,
			},
			['skill'] = 'High',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 3,
			},
			['name'] = '171 ARW',
			['livery'] = '',
			['base'] = 'Dubai Intl',
		},
		[24] = {
			['number'] = 16,
			['type'] = 'FA-18C_hornet',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Strike'] = true,
				['Fighter Sweep'] = true,
				['Escort'] = true,
				['SEAD'] = true,
				['Anti-ship Strike'] = true,
				['CAP'] = false,
				['Intercept'] = true,
			},
			['skill'] = 'High',
			['player'] = false,
			['name'] = 'VFA-131',
			['livery'] = 'VFA-131',
			['base'] = 'CVN-71 Theodore Roosevelt',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 16,
			},
		},
		[25] = {
			['number'] = 3,
			['type'] = 'E-3A',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['AWACS'] = true,
			},
			['skill'] = 'High',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 3,
			},
			['name'] = '7 ACCS',
			['livery'] = 'usaf standard',
			['base'] = 'Al Maktoum Intl',
		},
		[26] = {
			['number'] = 3,
			['type'] = 'KC-135',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Refueling'] = true,
			},
			['skill'] = 'High',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 3,
			},
			['name'] = '175 ARW',
			['livery'] = '',
			['base'] = 'Al Dhafra AB',
		},
		[27] = {
			['number'] = 10,
			['type'] = 'S-3B Tanker',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
			},
			['skill'] = 'High',
			['inactive'] = true,
			['name'] = 'R/174 ARW',
			['base'] = 'Reserves',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 10,
			},
		},
		[28] = {
			['number'] = 8,
			['type'] = 'E-2C',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
			},
			['skill'] = 'High',
			['inactive'] = true,
			['name'] = 'R/VAW-125',
			['base'] = 'Reserves',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 8,
			},
		},
		[29] = {
			['number'] = 4,
			['type'] = 'AV8BNA',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Strike'] = true,
				['SEAD'] = false,
			},
			['skill'] = 'High',
			['player'] = false,
			['name'] = 'VMA 311',
			['livery'] = 'VMA-311',
			['base'] = 'LHA_Tarawa',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 4,
			},
		},
	},
	['red'] = {
		[1] = {
			['number'] = 24,
			['type'] = 'F-5E-3',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'Random',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 24,
			},
			['name'] = '141 TFS',
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[2] = {
			['number'] = 10,
			['type'] = 'F-5E-3',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Iran',
			['tasks'] = {
				['Strike'] = true,
				['Fighter Sweep'] = true,
				['Escort'] = true,
				['CAP'] = true,
				['Intercept'] = true,
			},
			['skill'] = 'high',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 10,
			},
			['name'] = '21-3 TFS',
			['livery'] = 'IR IRIAF Camo',
			['base'] = 'Bandar e Jask airfield',
		},
		[3] = {
			['number'] = 24,
			['type'] = 'F-14A-135-GR',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'High',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 24,
			},
			['name'] = '82 TFS',
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[4] = {
			['number'] = 24,
			['type'] = 'F-4E',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'Random',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 24,
			},
			['name'] = '31 TFS',
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[5] = {
			['number'] = 22,
			['type'] = 'F-5E-3',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'high',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 22,
			},
			['name'] = '22-2 TFS',
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[6] = {
			['number'] = 2,
			['type'] = 'F-5E-3',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Iran',
			['tasks'] = {
				['Strike'] = true,
				['Fighter Sweep'] = true,
				['Escort'] = true,
				['CAP'] = true,
				['Intercept'] = true,
			},
			['skill'] = 'high',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 2,
			},
			['name'] = '21-2 TFS',
			['livery'] = 'IR IRIAF Camo',
			['base'] = 'Qeshm Island',
		},
		[7] = {
			['number'] = 24,
			['type'] = 'F-4E',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'Random',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 24,
			},
			['name'] = '11 TFS',
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[8] = {
			['number'] = 4,
			['type'] = 'AH-1W',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Iran',
			['tasks'] = {
				['Escort'] = false,
				['Strike'] = true,
			},
			['skill'] = 'high',
			['helicopter'] = true,
			['player'] = false,
			['name'] = '50 Squadron',
			['livery'] = {
				[1] = 'I.R.I.A.A',
			},
			['base'] = 'Al Ima FARP',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 4,
			},
		},
		[9] = {
			['number'] = 2,
			['type'] = 'F-5E-3',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Iran',
			['tasks'] = {
				['Strike'] = true,
				['Fighter Sweep'] = true,
				['Escort'] = true,
				['CAP'] = true,
				['Intercept'] = true,
			},
			['skill'] = 'high',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 2,
			},
			['name'] = '21 TFS',
			['livery'] = 'IR IRIAF Camo',
			['base'] = 'Sirri Island',
		},
		[10] = {
			['number'] = 4,
			['type'] = 'F-4E',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Iran',
			['tasks'] = {
				['CAP'] = true,
				['Fighter Sweep'] = true,
				['Escort'] = true,
				['Intercept'] = true,
			},
			['skill'] = 'Random',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 4,
			},
			['name'] = '23 TFS',
			['livery'] = 'IRIAF Asia Minor',
			['base'] = 'Bandar Abbas Intl',
		},
		[11] = {
			['number'] = 4,
			['type'] = 'F-4E',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Iran',
			['tasks'] = {
				['Strike'] = true,
				['Fighter Sweep'] = true,
				['Escort'] = true,
				['SEAD'] = true,
				['CAP'] = true,
				['Intercept'] = false,
			},
			['skill'] = 'Random',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 4,
			},
			['name'] = '91 TFS',
			['livery'] = 'IRIAF Asia Minor',
			['base'] = 'Bandar Abbas Intl',
		},
		[12] = {
			['number'] = 16,
			['type'] = 'AH-1W',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'high',
			['helicopter'] = true,
			['inactive'] = true,
			['name'] = '51 Squadron Res',
			['base'] = 'Reserves',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 16,
			},
		},
		[13] = {
			['number'] = 4,
			['type'] = 'KC135MPRS',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Iran',
			['tasks'] = {
				['Refueling'] = true,
			},
			['skill'] = 'High',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 4,
			},
			['name'] = 'Tanker sqd',
			['livery'] = {
				[1] = 'IRIAF',
			},
			['base'] = 'Shiraz Intl',
		},
		[14] = {
			['number'] = 22,
			['type'] = 'F-5E-3',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'high',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 22,
			},
			['name'] = '22-4 TFS',
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[15] = {
			['number'] = 18,
			['type'] = 'MiG-29A',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'high',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 18,
			},
			['name'] = '52 TFS',
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[16] = {
			['number'] = 36,
			['type'] = 'F-5E-3',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'high',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 36,
			},
			['name'] = '22-3 TFS',
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[17] = {
			['number'] = 4,
			['type'] = 'F-14A-135-GR',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Iran',
			['tasks'] = {
				['CAP'] = true,
				['Fighter Sweep'] = true,
				['Escort'] = true,
				['Intercept'] = true,
			},
			['skill'] = 'High',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 4,
			},
			['name'] = '81 TFS',
			['livery'] = {
				[1] = 'IRIAF Blue-Gray',
			},
			['base'] = 'Lar Airbase',
		},
		[18] = {
			['number'] = 18,
			['type'] = 'F-14A-135-GR',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'High',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 18,
			},
			['name'] = '84 TFS',
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[19] = {
			['number'] = 4,
			['type'] = 'MiG-29A',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Iran',
			['tasks'] = {
				['CAP'] = true,
				['Fighter Sweep'] = true,
				['Escort'] = true,
				['Intercept'] = true,
			},
			['skill'] = 'high',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 4,
			},
			['name'] = '51 TFS',
			['livery'] = {
				[1] = 'IRIAF blue-grey',
			},
			['base'] = 'Bandar Abbas Intl',
		},
		[20] = {
			['number'] = 4,
			['type'] = 'F-14A-135-GR',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Iran',
			['tasks'] = {
				['CAP'] = true,
				['Fighter Sweep'] = true,
				['Escort'] = true,
				['Intercept'] = true,
			},
			['skill'] = 'High',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 4,
			},
			['name'] = '83 TFS',
			['livery'] = {
				[1] = 'IRIAF Blue-Gray',
			},
			['base'] = 'Shiraz Intl',
		},
		[21] = {
			['number'] = 22,
			['type'] = 'F-5E-3',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'high',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 22,
			},
			['name'] = '22 TFS',
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[22] = {
			['number'] = 6,
			['type'] = 'Su-24M',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Iran',
			['tasks'] = {
				['Strike'] = true,
				['Anti-ship Strike'] = false,
				['SEAD'] = true,
				['Laser Illumination'] = false,
			},
			['skill'] = 'high',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 6,
			},
			['name'] = '72 TFS',
			['livery'] = 'Iranian Air Force',
			['base'] = 'Shiraz Intl',
		},
		[23] = {
			['number'] = 36,
			['type'] = 'Su-24M',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'high',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 36,
			},
			['name'] = '73 TFS',
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[24] = {
			['number'] = 4,
			['type'] = 'F-5E-3',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Iran',
			['tasks'] = {
				['Strike'] = true,
				['Fighter Sweep'] = true,
				['Escort'] = true,
				['CAP'] = true,
				['Intercept'] = false,
			},
			['skill'] = 'Random',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 4,
			},
			['name'] = '41 TFS',
			['livery'] = 'IR IRIAF Camo',
			['base'] = 'Bandar Abbas Intl',
		},
		[25] = {
			['number'] = 2,
			['type'] = 'F-5E-3',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Iran',
			['tasks'] = {
				['Strike'] = true,
				['Fighter Sweep'] = true,
				['Escort'] = true,
				['CAP'] = true,
				['Intercept'] = true,
			},
			['skill'] = 'high',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 2,
			},
			['name'] = '21-4 TFS',
			['livery'] = 'IR IRIAF Camo',
			['base'] = 'Khasab',
		},
		[26] = {
			['number'] = 16,
			['type'] = 'AH-1W',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'high',
			['helicopter'] = true,
			['inactive'] = true,
			['name'] = '50 Squadron Res',
			['base'] = 'Reserves',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 16,
			},
		},
		[27] = {
			['number'] = 2,
			['type'] = 'AH-1W',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Iran',
			['tasks'] = {
				['Escort'] = false,
				['Strike'] = true,
			},
			['skill'] = 'high',
			['helicopter'] = true,
			['player'] = false,
			['name'] = '51 Squadron',
			['livery'] = {
				[1] = 'I.R.I.A.A',
			},
			['base'] = 'Khasab',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 2,
			},
		},
	},
}
